### ISSUE TITLE
Omni v2 implementation is inconsistent about return value

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#109]
In the Omni AM API v2 implementation, the return from getversion includes all three items returned by the API (code, value, error) but all of the other commands just return value.

We should be consistent.

On the upside, returning just value makes a lot of interoperating code just work.

On the downside, you can't see what the error codes were.  

 _Imported from trac ticket [#109](http://trac.gpolab.bbn.com/gcf/ticket/109),  created by sedwards on 01-26-2012 at 20:53, last modified: 01-30-2012 at 13:52_

**Comment by tcmitchell** [comment]
I think this boils down to normalizing the output from the aggregate. The current v2 implementation in omni normalizes to v1 returns by extracting the "value" from the v2 response. This minimized disruption in the rest of the code, but at the cost of some information loss in error cases. The short term fix is to make GetVersion match the other calls.

In the future the return value can be normalized to v2 by converting a v1 return into a complex structure and handling that complex structure in the outer layers of omni.


_Trac comment by tmitchel (github user: tcmitchell) on 01-30-2012 at 11:08_

**Comment by seledwards** [comment]
Grabbing this ticket.

_Trac comment by sedwards (github user: seledwards) on 01-30-2012 at 11:20_

**Comment by seledwards** [comment]
I made GetVersion match the other calls and checked it in.

Closing.

_Trac comment by sedwards (github user: seledwards) on 01-30-2012 at 13:52_
