### ISSUE TITLE
Omni leaves self-signed cert when sfa cert download fails

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#11]
If a user does not have an SFA cert and omni attempts to download it, a temporary self-signed cert is created in the specified file. If the SFA cert download fails the temporary self-signed cert is left in place, but it cannot be used for any omni commands. The user is never re-prompted to download their SFA cert.

 _Imported from trac ticket [#11](http://trac.gpolab.bbn.com/gcf/ticket/11),  created by tmitchel on 09-27-2010 at 21:37, last modified: 09-30-2010 at 15:14_

**Comment by ahelsing** [comment]
Now deletes the self-signed cert if the procedure fails.

_Trac comment by jkarlin on 09-29-2010 at 16:18_
