### ISSUE TITLE
If users attribute is empty in omni_config, omni exits without a useful error

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-tools#116]
If the users attribute in the [omni] section is left empty, omni exits with not a very useful error :
```
INFO:omni:Loading config file /home/nriga/.gcf/omni_config
Traceback (most recent call last):
  File "/home/nriga/gcf/src/omni.py", line 2531, in <module>
    sys.exit(main())
  File "/home/nriga/gcf/src/omni.py", line 2524, in main
    framework, config, args, opts = initialize(argv)
  File "/home/nriga/gcf/src/omni.py", line 2135, in initialize
    config = load_config(opts, logger)
  File "/home/nriga/gcf/src/omni.py", line 2065, in load_config
    for (key,val) in confparser.items(user.strip()):
  File "/usr/lib/python2.6/ConfigParser.py", line 328, in items
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: ''
```

Try and catch this case and print something useful to the user. 

 _Imported from trac ticket [#116](http://trac.gpolab.bbn.com/gcf/ticket/116),  created by nriga on 02-07-2012 at 14:10, last modified: 02-09-2012 at 16:27_

**Comment by seledwards** [comment]
The relevant code in omni.py is:

```
    if 'users' in config['omni']:
        for user in config['omni']['users'].split(','):
            d = {}
            for (key,val) in confparser.items(user.strip()):
                d[key] = val
            config['users'].append(d)
```

Fixing this should just be a matter of testing whether `user.strip()` is an empty string before doing the `for` loop.

_Trac comment by sedwards (github user: seledwards) on 02-07-2012 at 14:18_

**Comment by innnkkki** [comment]
I have already fixed this but apparantly never pressed save to the ticket. 

So the code now looks like 
```
 if 'users' in config['omni']:
        if config['omni']['users'].strip() is not _ :
            for user in config['omni']['users'].split(','):
                if user.strip() is not _ :
                    d = {}
                    for (key,val) in confparser.items(user.strip()):
                        d[key] = val
                    config['users'].append(d)
```


This fixes two bugs : 
   1. an empty users list
   2. the case that a comma is not followed by a user, e.g. 
       * users = inki,
       * users = inki, , nriga



_Trac comment by nriga (github user: innnkkki) on 02-09-2012 at 16:27_
