### ISSUE TITLE
cred_util throws xmlrpclib.Fault exceptions

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#120]
```
  File "/opt/foam/lib/geni/util/cred_util.py", line 252, in verify
    raise xmlrpclib.Fault(fault_code, fault_string)
```

This is pretty annoying if you're using gcf as a library - there's no useful information in this exception to be able to handle it unless you parse the string values.  GCF should throw a more-specific exception in the core and then translate it into an XMLRPC Fault if it reaches the xmlrpc API boundary.

 _Imported from trac ticket [#120](http://trac.gpolab.bbn.com/gcf/ticket/120),  created by nick.bastin on 02-14-2012 at 15:06, last modified: 04-09-2013 at 09:55_

**Comment by tcmitchell** [comment]
I'm not sure why an exception gets thrown in this situation. The lack of matching credentials does not strike me as an "exceptional" situation requiring a thrown exception to be handled by the caller. The verify function could return an empty list signifying no credentials matched the input parameters (gid, target_urn, privileges). This gives verify "boolean" semantics (an empty list is evaluated as false, a non-empty list is evaluated as true).

If we really think this situation warrants an exception I agree that verify should not be throwing an XML-RPC Fault - it has no way of knowing whether it was invoked by an XML-RPC service.

_Trac comment by tmitchel (github user: tcmitchell) on 02-15-2012 at 10:10_
