### ISSUE TITLE
'omni -o' should create a zero-length file if there's no output

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#133]
When omni is run with '-o', but doesn't get any output (e.g. from a 'sliverstatus' because the AM is down), it doesn't create an output file. It'd be convenient if it did, to make it easier to detect problems simply by looking at the output files (especially when running a bunch of commands in a loop against a bunch of aggregates).

 _Imported from trac ticket [#133](http://trac.gpolab.bbn.com/gcf/ticket/133),  created by sedwards on 04-30-2012 at 12:43, last modified: 10-17-2014 at 15:44_

**Comment by seledwards** [comment]
Listing myself as the reporter.

_Trac comment by sedwards (github user: seledwards) on 04-21-2014 at 13:27_

**Comment by ahelsing** [comment]
I think this is debatable.

_Trac comment by ahelsing on 10-17-2014 at 15:44_
