### ISSUE TITLE
Document update procedure for gcf

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-tools#140]
Currently I don't think we have a recommended procedure for updating the gcf software between releases (or I couldn't find it:-)

I think we should at least have a documented procedure for installing and updating gcf
(replace old installation, create simlinks, etc...)

The best thing to do would be to actually make a package of the software so that then they can ran update on it and just update it. 

 _Imported from trac ticket [#140](http://trac.gpolab.bbn.com/gcf/ticket/140),  created by nriga on 05-24-2012 at 14:59, last modified: 10-17-2014 at 15:44_

**Comment by innnkkki** [comment]
Chaos just mentioned to me that she has worked with Ubuntu and CentOS packages and she can help us make a package if we decide to go that way. 

_Trac comment by nriga (github user: innnkkki) on 05-24-2012 at 15:04_

**Comment by ahelsing** [comment]
Yes.

2 comments:
 1. Installation is currently just 'untar & configure'. So updating doesn't mean much.
 2. There was a previous effort (2 years ago?) to use python egg packages. See the 3 top level files in git setup-lib, setup-servers, etc. That code has not been exercised in years.


_Trac comment by ahelsing on 05-24-2012 at 15:10_

**Comment by innnkkki** [comment]
Replying to [ahelsing](comment:2):
> Yes.
> 
> 2 comments:
>  1. Installation is currently just 'untar & configure'. So updating doesn't mean much.

Yes, but many people have setup PATH, PYTHONPATH or have their omni_config under the gcf directory
and all this would break if the just untar a new version, especially if you have setup PATH. 

I think it is worthwhile to just document some steps for inexperienced users. 


>  2. There was a previous effort (2 years ago?) to use python egg packages. See the 3 top level files in git setup-lib, setup-servers, etc. That code has not been exercised in years.


_Trac comment by nriga (github user: innnkkki) on 05-24-2012 at 15:14_

**Comment by seledwards** [comment]
I just had to walk someone through installing and configuring omni on jabber.

He tried running `make install` and that didn't work, but it put some files in various places on his system.  Very misleading.  

I just wanted to add a vote for "make omni a package".

And Chaos reminds me she's volunteered to help.


_Trac comment by sedwards (github user: seledwards) on 07-13-2012 at 12:09_

**Comment by ahelsing** [comment]
We have this: http://trac.gpolab.bbn.com/gcf/wiki/QuickStart#Upgrade

That's good enough for me, and so far, for most users.

A package is still a nice idea.


_Trac comment by ahelsing on 10-17-2014 at 15:44_
