### ISSUE TITLE
Add RenewSlice implementation to framework_sfa

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#15]
Implement the renew slice capability in framework_sfa using the appropriate SFA commands.

 _Imported from trac ticket [#15](http://trac.gpolab.bbn.com/gcf/ticket/15),  created by tmitchel on 09-29-2010 at 09:31, last modified: 09-30-2010 at 15:15_

**Comment by tcmitchell** [comment]
This looks like it would be a Registry.UpdateSlice call, with 'expires' in the slice_fields. The expiration datetime object needs to be converted to a unix timestamp. Maybe something like:
```
>>> epoch = datetime.datetime(1970, 1, 1)
>>> dt = datetime.datetime(2010, 10, 15, 13, 12, 11)
>>> td = dt - epoch
>>> secs = td.seconds + td.days * 24 * 3600
```

_Trac comment by tmitchel (github user: tcmitchell) on 09-29-2010 at 13:07_

**Comment by ahelsing** [comment]
Done!

_Trac comment by jkarlin on 09-29-2010 at 16:14_
