### ISSUE TITLE
Implement AM API v3 in gcf-am.py

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#156]
Teach the gcf aggregate manager how to speak GENI AM API v3.

 _Imported from trac ticket [#156](http://trac.gpolab.bbn.com/gcf/ticket/156),  created by tmitchel on 08-02-2012 at 15:28, last modified: 08-30-2012 at 13:18_

**Comment by ahelsing** [comment]
The GCF AM now speaks AM API v3, if you request it. Default is v2

_Trac comment by ahelsing on 08-30-2012 at 13:18_
