### ISSUE TITLE
Allow more flexible AM API version control

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#160]
An idea which came up on IRC today: The ability (via either command line or config file, ideally) to specify what versions you'd prefer to use; or, what version to use no matter what. These would be two different settings, and you can probably only specify one, or you get an error.

 _Imported from trac ticket [#160](http://trac.gpolab.bbn.com/gcf/ticket/160),  created by jbs on 08-27-2012 at 16:48, last modified: 04-21-2014 at 13:32_

**Comment by ahelsing** [comment]
For example, if you said to use version 1 or 2, and the AM only speaks version 2, it'd go ahead and use version 2; whereas if you said to use version 3, it would give you an error; but if you said you insist on using version 3, it would try (even though this is very unlikely to work; but it'd be useful in doing deliberately hinky things to test AM compliance).

_Trac comment by jbs on 08-27-2012 at 16:49_

**Comment by seledwards** [comment]
`--devmode` allows you to force a particular version of the AM API.  And to force a lot of other things as well to support testing and the like.

_Trac comment by sedwards (github user: seledwards) on 08-27-2012 at 16:59_

**Comment by ahelsing** [comment]
I think --devmode is good enough for what I had in mind here, and if anyone else wants more than that, they can open a new ticket.

_Trac comment by jbs on 04-21-2014 at 13:32_
