### ISSUE TITLE
Add support for ProtoGENI CreateImage

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#186]
ProtoGENI has a new image creation feature. There is a test script called `createimage.py`. Port that functionality into omni by adding a method to [src/omnilib/frameworks/framework_pg.py](../tree/master/src/omnilib/frameworks/framework_pg.py) and adding an appropriate omni command to invoke it.

See `list_my_ssh_keys()` for an example of a similar feature.

 _Imported from trac ticket [#186](http://trac.gpolab.bbn.com/gcf/ticket/186),  created by tmitchel on 09-05-2012 at 17:54, last modified: 09-06-2013 at 10:50_

**Comment by tcmitchell** [comment]
This probably also needs a 'Not Implemented' method in [src/omnilib/frameworks/framework_base.py.](../tree/master/src/omnilib/frameworks/framework_base.py.) Again, see `list_my_ssh_keys()`.

_Trac comment by tmitchel (github user: tcmitchell) on 09-05-2012 at 17:55_

**Comment by ahelsing** [comment]
createimage script is here: 
http://git-public.flux.utah.edu/gitweb.cgi?p=emulab-devel.git;a=blob;f=protogeni/test/createimage.py;h=9a2c82f98a333ce6497a54526114f7499300c94c;hb=HEAD

_Trac comment by ahelsing on 11-29-2012 at 13:38_

**Comment by ahelsing** [comment]
Explanation of arguments and returns are here:

http://www.protogeni.net/trac/protogeni/wiki/ImageHowTo


_Trac comment by ahelsing on 11-29-2012 at 13:41_

**Comment by ahelsing** [comment]
Hmm. Looking more closely it appears this is a function at the PG AM implementation. So 
 1. the experimenter has to identify both the sliver urn of the node, and the AM hosting that node, and 
 2. this probably goes not in framework_pg but in amhandler - and just isn't implemented except at PG AMs of a certain vintage (and how do we cleanly determine that?)



_Trac comment by ahelsing on 11-29-2012 at 14:23_

**Comment by ahelsing** [comment]
Started an implementation in amhandler, without any attempt to see if this is a PG AM as yet.
So far, I just get `Fault -32600: 'Internal Error executing CreateImage'`

I emailed Leigh.

_Trac comment by ahelsing on 12-03-2012 at 15:56_

**Comment by ahelsing** [comment]
Much back and forth with Leigh.
I've cleaned up the arguments (they should be AM API style).
I'm still getting a missing argument error.


_Trac comment by ahelsing on 12-04-2012 at 11:57_

**Comment by ahelsing** [comment]
Image is now being successfully created. However, the PG implementation does not correctly respond with the new image URN and URL (so it can be used later).

committing what I have. Subsequent edits will be to clean up the return string.

_Trac comment by ahelsing on 12-04-2012 at 16:22_

**Comment by ahelsing** [comment]
Created a new ticket for supporting deleteimage at some point.

There's nothing else we can do on this ticket at the moment. Once PG fixes their AM API implementation, this _may_ just work. Hold this ticket open to fix any issues that may arise.


_Trac comment by ahelsing on 12-06-2012 at 12:06_

**Comment by ahelsing** [comment]
in and released with 2.2

_Trac comment by ahelsing on 01-30-2013 at 10:45_
