### ISSUE TITLE
omni.py listresources output file naming is inconsistent

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-tools#196]
The omni output file naming is inconsistent for listresources output files. Some examples listresources run at PG Utah  and the resulting output file names:
```
$ omni.py listresources -a https://www.emulab.net/protogeni/xmlrpc/am/1.0 -V1 -o
   =>  rspec-www-emulab-net-protogeni-xmlrpc-am-1-0.xml

$ omni.py listresources -a https://www.emulab.net/protogeni/xmlrpc/am -V1 -o
   =>  rspec-www-emulab-net-12369-protogeni-xmlrpc-am-1-0.xml

$ omni.py listresources -a https://www.emulab.net/protogeni/xmlrpc/am/2.0 -o
    =>   rspec-www-emulab-net-protogeniv2.xml

$ omni.py listresources -a https://www.emulab.net/protogeni/xmlrpc/am/3.0 -V3 -o
    =>  rspec-www-emulab-net-protogeni-xmlrpc-am-3-0.xml
```

 _Imported from trac ticket [#196](http://trac.gpolab.bbn.com/gcf/ticket/196),  created by lnevers on 09-27-2012 at 11:34, last modified: 05-18-2015 at 10:46_

**Comment by ahelsing** [comment]
This is a PG AM only issue.
Fixed on master.


_Trac comment by ahelsing on 09-27-2012 at 12:51_
