### ISSUE TITLE
Sliverstatus output presentaion is confusing and long

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-tools#197]
This is an enhancement request, sorry for the long-winded description, as I make my case.

In recent testing I have found that the overall geni_status for a sliver has moved from the end of command the output to the beginning of the command output. Here is an example from August 21 using GCF 1.6.2:
```
                    'geni_status': 'ready',
                     'geni_urn': 'urn:publicid:IDN+utah.geniracks.net+sliver+7861',
                     'geni_status': 'ready',
                     'geni_urn': 'urn:publicid:IDN+utah.geniracks.net+sliver+7856',
                     'geni_status': 'ready',
                     'geni_urn': 'urn:publicid:IDN+utah.geniracks.net+sliver+7857',
                     'geni_status': 'ready',
                     'geni_urn': 'urn:publicid:IDN+utah.geniracks.net+sliver+7858',
 'geni_status': 'ready',
 'geni_urn': 'urn:publicid:IDN+pgeni.gpolab.bbn.com+slice+2vmslice1',
```

Here is an example from September 27 using gcf-2.0:
```
$ egrep "geni_urn|geni_status" lninsta-2-sliverstatus-utah-geniracks-net-protogeniv2.json 
  "geni_status": "ready", 
  "geni_urn": "urn:publicid:IDN+pgeni.gpolab.bbn.com+slice+lninsta-2", 
      "geni_urn": "urn:publicid:IDN+utah.geniracks.net+sliver+10402", 
      "geni_status": "ready"
      "geni_urn": "urn:publicid:IDN+utah.geniracks.net+sliver+10397", 
      "geni_status": "ready"
      "geni_urn": "urn:publicid:IDN+utah.geniracks.net+sliver+10399", 
      "geni_status": "ready"
      "geni_urn": "urn:publicid:IDN+utah.geniracks.net+sliver+10398", 
      "geni_status": "ready"
```

Up to recently, the last "geni_status" string in the output was the state information for the sliver, so at first, I completely missed this change and interpreted the last geni_status as the overall sliver status. Note: The output above does not capture the additional confusion caused by the URN being listed about 40 lines before, in a non-resized window (80x24) only the following is shown:
```
              }
            ]
          }
        ]
      }, 
      "geni_error": "", 
      "geni_status": "ready"
    }
  ], 
  "pg_expires": "2012-09-27T19:04:26"
}
INFO:omni: ------------------------------------------------------------
INFO:omni: Completed sliverstatus:

  Options as run:
		aggregate: ['ig-utah']
		framework: pg
		getversionCacheName: /home/lnevers/.gcf/get_version_cache.json

  Args: sliverstatus lninsta

  Result Summary: Slice urn:publicid:IDN+pgeni.gpolab.bbn.com+slice+lninsta expires within 1 day(s) on 2012-09-27 19:04:26 UTC
Returned status of slivers on 1 of 1 possible aggregates. 
INFO:omni: ============================================================
$ 
``` 

With the current change the key details (sliver ready/notready/failed/etc) are the the top of the output, which is usually very long (2 VMs and 1 lan generates 734 lines of output in a gcf2.0 sliverstatus), and scrolling back over 700 lines to see "geni_status" "ready" seems like too much scrolling.  

Request: Is it possible for the omni to provide the overall sliver status as part of the command summary?

 _Imported from trac ticket [#197](http://trac.gpolab.bbn.com/gcf/ticket/197),  created by lnevers on 09-27-2012 at 12:17, last modified: 10-03-2012 at 14:26_

**Comment by ahelsing** [comment]
Adding test like this to the Result Summary for v1+v2 AMs:
```
Slice urn:publicid:IDN+geni:gpo:gcf+slice+ahtest at AM http://localhost:8001 has overall SliverStatus: ready.
```

Still working on the v3+ equivalent.

_Trac comment by ahelsing on 10-01-2012 at 12:53_

**Comment by ahelsing** [comment]
Sample v3 output:
```
Slice urn:publicid:IDN+geni:gpo:gcf+slice+ahtest expires in <= 3 hours on 2012-10-03 19:59:29 UTC
Retrieved Status on 2 slivers in slice urn:publicid:IDN+geni:gpo:gcf+slice+ahtest at http://localhost:8001:
  All slivers expire on '2012-10-03T18:20:17.729257'.
  All slivers are in allocation state geni_allocated.
  All slivers are in operational state geni_pending_allocation.

Returned status of slivers on 1 of 1 possible aggregates.
```


_Trac comment by ahelsing on 10-03-2012 at 14:26_
