### ISSUE TITLE
README-accept-AMAPI.txt gives incorrect instructions for delegateSliceCred.py

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-tools#199]
The command help (-h) for the delegateSliceCred.py states:
```
delegateSliceCred.py 
	--cert <filename of your cert, eg ~/.gcf/plc-jdoe-cert.pem>
	--key <filename of your key, eg ~/.gcf/plc-jdoe-key.pem>
	--slicecred <filename of saved slice credential to delegate,
		eg mySliceCred.xml>
	--delegeegid <filename of co-workers cert you want to delegate to>
```
While the README-accept-AMAPI.txt starting on line 232 states the opposite?
```
         $ $GCF/src/delegateSliceCred.py --cert path/to/their/cert.pem \
              --key path/to/their/key.pem --delegeegid path/to/your/gid_file.pem \
              --slicecred delegSlice-cred.xml
```

The help "--cert" and "--key" states "your keys", while the README states "their" cert.
The help "--delegeeid" states "your co-worker", while the READM states "your cert.

The README-accept-AMAPI.txt should be updated to match the --help, which is correct.

 _Imported from trac ticket [#199](http://trac.gpolab.bbn.com/gcf/ticket/199),  created by lnevers on 10-02-2012 at 08:44, last modified: 10-02-2012 at 09:06_

**Comment by ahelsing** [comment]
The acceptance README is giving instructions for your colleague to delegate THEIR slice credential to YOU.
So the cert and key is THEIR cert and key, and YOU are the delegee.

I'll try to clear up that text.


_Trac comment by ahelsing on 10-02-2012 at 08:54_

**Comment by luisanevers** [comment]
The delegee perspective makes sense for the README-accept-AMAPI.txt.

Thinking back, I realized that the AM API test area is the only area that provides full delegation instructions, and I keep referring to it, when I want to delegate a slice.

There are no delegation instructions in the other READMEs other than telling the reader to look at the "--help", same as true on the wiki.


_Trac comment by lnevers (github user: luisanevers) on 10-02-2012 at 09:06_
