### ISSUE TITLE
Print Warning about mismatch versions in the summary

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-tools#200]
When the URL provided does not support V2, the summary output looks like:
```
 Result Summary: Got no resources on slice pharos.  
INFO:omni: ============================================================
```

Which may lead people to believe that they have no resources in this aggregate. 

Roll the warning 
```
WARNING:omni:Requested API version 2, but AM http://myplc.gpolab.bbn.com:12346/ uses version 1. This aggregate does not advertise other versions.
```

in the summary

 _Imported from trac ticket [#200](http://trac.gpolab.bbn.com/gcf/ticket/200),  created by nriga on 10-02-2012 at 15:12, last modified: 10-03-2012 at 12:30_

**Comment by ahelsing** [comment]
Unfortunately the message we want is produced in _checkValidClient. And that does not return a message. And its caller often just raises an exception. So both would have to change. Only then do we get to the top level method that constructs the return summary (the retVal variable).

So doable, and a good idea, but it will take a little work.


_Trac comment by ahelsing on 10-02-2012 at 15:30_

**Comment by ahelsing** [comment]
I think I have this working. We can play with the log messages we use over time.


_Trac comment by ahelsing on 10-03-2012 at 12:30_
