### ISSUE TITLE
readyToLogin.py run against a url of the wrong version of AM API doesn't work

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#207]
In the GEC15, Experimenter Drop In Session, saw the following error.

If you run:

```
readyToLogin.py -V 1 -a AMv2url
```

where AMv2url is the v2 URL of the AM.

Then readyToLogin.py fails and doesn't give a helpful error.

 _Imported from trac ticket [#207](http://trac.gpolab.bbn.com/gcf/ticket/207),  created by sedwards on 10-24-2012 at 18:06, last modified: 12-16-2012 at 11:17_
   CCing: nriga@...

**Comment by innnkkki** [comment]
As of [da48dd152b07385ddef563032ee86d0d40f478dc](https://github.com/GENI-NSF/geni-tools/commit/da48dd152b07385ddef563032ee86d0d40f478dc) this is fixed. Probably due to the changes of automatically switching to right AM URL. 

_Trac comment by nriga (github user: innnkkki) on 12-16-2012 at 11:17_
