### ISSUE TITLE
readyToLogin.py should not show the details of the sliverstatus

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-tools#209]
These are 2 enhancement requests:

1. The readyToLogin.py script should not show the sliverstatus command output, which has become increasingly longer and more difficult to ready, instead it should simply show the summary for the sliver:

```
================================================================================
LOGIN INFO for AM: http://utah.geniracks.net/protogeni/xmlrpc/am/2.0
================================================================================

VM-1's geni_status is: ready (am_status:ready) 
User lnevers logins to VM-1 using:
	xterm -e ssh -p 35386  -i /home/lnevers/.ssh/id_rsa lnevers@pc5.utah.geniracks.net &

VM-4's geni_status is: ready (am_status:ready) 
User lnevers logins to VM-4 using:
	xterm -e ssh -p 35389  -i /home/lnevers/.ssh/id_rsa lnevers@pc5.utah.geniracks.net &

VM-3's geni_status is: ready (am_status:ready) 
User lnevers logins to VM-3 using:
	xterm -e ssh -p 35388  -i /home/lnevers/.ssh/id_rsa lnevers@pc5.utah.geniracks.net &

VM-2's geni_status is: ready (am_status:ready) 
User lnevers logins to VM-2 using:
	xterm -e ssh -p 35387  -i /home/lnevers/.ssh/id_rsa lnevers@pc5.utah.geniracks.net &
```

2. Additionally, there should be an option to just execute the xterm commands to connect to the nodes when the sliver is ready. I am finding they I keep re-issuing the command while waiting for resources, and when the resources are ready, I have to cut-n-paste each of the xterm commands, which are on separate lines and have to be copy-n-pasted separately.

 _Imported from trac ticket [#209](http://trac.gpolab.bbn.com/gcf/ticket/209),  created by lnevers on 11-07-2012 at 15:26, last modified: 12-16-2012 at 11:13_

**Comment by innnkkki** [comment]
MOdified omni.py to have more command line arguments to set the log levels:
 --info, --warn, --error

and set the loglevel to ward from readyToLogin.py script. 

Fixed at [da48dd152b07385ddef563032ee86d0d40f478dc](https://github.com/GENI-NSF/geni-tools/commit/da48dd152b07385ddef563032ee86d0d40f478dc)

_Trac comment by nriga (github user: innnkkki) on 12-16-2012 at 11:13_
