### ISSUE TITLE
If the SSL cert is an empty file, connections hang and generate no error messages

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#210]
If the cert for the `gcf-am.py` is an empty file then connections to it via omni just hang.  There are no messages in any log files (`gcf-am`, `omni`, or `apache` if run via the portal).  

Current code checks to make sure the cert exists.  Also check to make sure the cert is of non-zero size.

This comes up lots of different places in the code.

Check: `gcf-am`, `gcf-ch`, `secureXMLRPCServer`, `omni.py` and maybe others.

 _Imported from trac ticket [#210](http://trac.gpolab.bbn.com/gcf/ticket/210),  created by sedwards on 11-09-2012 at 13:19, last modified: 12-07-2012 at 10:01_

**Comment by ahelsing** [comment]
there were a lot of places, but I believe I caught them all

_Trac comment by ahelsing on 12-07-2012 at 10:01_
