### ISSUE TITLE
Provision must take geni_rspec_version

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#216]
Provision in AM API v3 is being modified.

Previously, there was no way for the AM to know what RSpec format to use (besides try to remember what it did for Allocate previously).

Now AM API v3 requires the geni_rspec_version option.

Modify the gcf-am, omni, and acceptance tests appropriately

 _Imported from trac ticket [#216](http://trac.gpolab.bbn.com/gcf/ticket/216),  created by ahelsing on 12-04-2012 at 16:59, last modified: 01-07-2013 at 10:26_

**Comment by ahelsing** [comment]
ticket #217 tracks acceptance test enhancements. I do not want to include these immediately, because suddenly PG and PLC will fail the tests.


_Trac comment by ahelsing on 12-05-2012 at 10:33_

**Comment by ahelsing** [comment]
Omni now supplies the geni_rspec_version option (and refuses to call provision if you ask for an RSpec format that is not supported).

gcf-am in v3 expects the option, complains if it is missing or malformed or you request something that isn't supported

v3 provision works with gcf-am and PG


_Trac comment by ahelsing on 12-05-2012 at 10:55_

**Comment by luisanevers** [comment]
Trying to verify this change and not sure how to verify. I have tried the following with the gcf-am V3:
 1. Created a slice and allocated resources with v.02 rspec
 2. Provisioned the sliver ($ omni.py allocate -a https://127.0.0.1:8001/ 89bb  -V3 ~/gcf-test/emulab-v0.2.rspec)

At this point expected some message telling me somthing about the rspec version, but the sliver was allocated successfully returning a V3 manifest.

What am I missing? Is V0.2 still supported?


_Trac comment by lnevers (github user: luisanevers) on 01-07-2013 at 08:00_

**Comment by ahelsing** [comment]
The gcf-am is not picky about request rspecs that you send it. So it should have complained that it didn't understand v0.2 RSpecs, but it didn't.

The allocate command you gave is fine.

Then you call provision. And that is the spot where Omni now supplies the geni_rspec_version option to the AM.

If you include the RSpec type on the commandline, you should see more output:
```
$ omni.py provision -a  https://127.0.0.1:8001/ 89bb -V3 --devmode -t ProtoGENI 2 
```

This should give something like this:
```
  Options as run:
		aggregate: ['https://127.0.0.1:8001/']
		api_version: 3
		devmode: True
		rspectype: ('ProtoGENI', '2')

  Args: provision ahtest rspec-request-local-v0.2.xml

  Result Summary: Provision of slivers in slice urn:publicid:IDN+geni:gpo:gcf+slice+89bb at https://localhost:8001 failed: AM https://localhost:8001 didnt support required RSpec format ProtoGENI 2, but continuing.  (Error from Aggregate: code 4: Bad Version: requested RSpec type protogeni is not a valid option.)
Provision slivers in slice urn:publicid:IDN+geni:gpo:gcf+slice+89bb failed at https://localhost:8001 
```


_Trac comment by ahelsing on 01-07-2013 at 10:26_
