### ISSUE TITLE
Fix python declaration in files to work on mac

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#226]
`omni-configure.py` and `omni.py` assume that your
python is at `/usr/bin/python` so you currently have to either:
  * always invoke them using python, e.g. `python src/omni-configure.py` and `python src/omni.py`
  * modify the first line in each of the files to `#!/usr/local/bin/python`

We should modify the `#!` appropriately so this just works without modification.

 _Imported from trac ticket [#226](http://trac.gpolab.bbn.com/gcf/ticket/226),  created by sedwards on 12-20-2012 at 10:42, last modified: 04-04-2013 at 14:57_

**Comment by ahelsing** [comment]
Opinions vary on whether this is good, but the conventional thing to do is to put:
```/usr/bin/env python
```
in the shebang, on the theory that every *nix OS has promised to put env in /usr/bin.

_Trac comment by chaos on 12-20-2012 at 10:45_

**Comment by tcmitchell** [comment]
Several scripts ([src/gen-certs.py](../tree/master/src/gen-certs.py), [src/gcf-ch.py](../tree/master/src/gcf-ch.py), and others) use the "`#!/usr/bin/env python`" syntax. We should be consistent with that across the other scripts that are intended to be run on the command line by a user.

_Trac comment by tmitchel (github user: tcmitchell) on 01-04-2013 at 11:02_
