### ISSUE TITLE
gcf-am not properly checking user credentials on ListResources

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#228]
If I supply an valid but untrusted credential to `ListResources` via the `--usercredfile` option, I get the following error:

```
No resources from AM http://localhost:8001: <Fault Insufficient privileges: "No credential was found with appropriate privileges.
    Tried urn:publicid:IDN+geni:gpo:gcf+user+alice.
    Last failure: Couldn't validate credential for caller urn:publicid:IDN+geni:gpo:gcf+user+alice with target urn:publicid:IDN+geni:gpo:gcf+user+alice with any of 1 known root certs: CredentialNotVerifiable: u'Credential [ Grant [ OU: None, CN: geni//gpo//gcf.user.alice, SubjectAltName: URI:urn:publicid:IDN+geni:gpo:gcf+user+alice ] rights on [ OU: None, CN: geni//gpo//gcf.user.alice, SubjectAltName: URI:urn:publicid:IDN+geni:gpo:gcf+user+alice ] until 2012-01-10 18:27:18 ] expired at 2012-01-10T18:27:18'"> (missing result) 
```

This used the `untrusted-usercred.xml` file in `gcf/acceptance_test/AM_API`.

If instead the credential is a file containing arbitrary text (in this case the literal string `nothing`), the command succeeds.

I tried this with the v1 version of the am.  I haven't tried with other versions.

 _Imported from trac ticket [#228](http://trac.gpolab.bbn.com/gcf/ticket/228),  created by sedwards on 12-21-2012 at 11:18, last modified: 12-27-2012 at 16:08_

**Comment by seledwards** [comment]
Here's the command I ran:
```$ ~/gcf/src/omni.py -a http://localhost:8001 listresources -V 1 --usercredfile untrusted-usercred.xml -t ProtoGENI 2 --raise-error-on-v2-amapi-error
```

_Trac comment by sedwards (github user: seledwards) on 12-21-2012 at 11:21_

**Comment by ahelsing** [comment]
Run this with `--debug` and you will see what is happening.
Omni notices that you did not supply a valid user credential in that file, so it does not use it. Instead, it queries your CH for your user credential.
The tests that Omni does to ensure it got a valid user credential are pretty basic: It parses the XML, and tries to extract a target_urn from a credential element from a signed-credential element. If it cannot do that, it deems this an invalid credential.

To confirm, I get the same behavior talking to the AM API v3 ProtoGENI Utah aggregate.

_Trac comment by ahelsing on 12-27-2012 at 16:08_
