### ISSUE TITLE
acceptance tests fail for v1 AMs

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#229]
Nick Bastin reports the following error when running the acceptance tests against the FOAM AM which only speaks v1.

```
It appears that the acceptance tests can no longer be run on V1
aggregates (or at least, they can't pass them) - is this intended?

Most of my failures can be traced to listresources expecting a valid
return rspec even if there are bad credentials:

======================================================================
FAIL: test_ListResources_untrustedCredential (__main__.Test)
test_ListResources_untrustedCredential: Passes if 'ListResources' FAILS to
----------------------------------------------------------------------
Traceback (most recent call last):
 File "./am_api_accept.py", line 579, in test_ListResources_untrustedCredential
   usercredfile=self.options_copy.untrusted_usercredfile)
 File "/usr/lib/python2.7/unittest/case.py", line 476, in assertRaises
   callableObj(*args, **kwargs)
 File "./am_api_accept.py", line 593, in subtest_ListResources
   slicecredfile=slicecredfile, typeOnly=typeOnly )
 File "./am_api_accept.py", line 718, in subtest_query_rspec
   self.options_copy.rspeclint)
 File "/home/nbastin/Development/gcf/src/omni_unittest.py", line 287,
in assertRspec
   self.assertIsNotNone( rspec, "RSpec returned from '%s' is
unexpectedly 'None'" % AMAPI_call )
 File "/home/nbastin/Development/gcf/src/omni_unittest.py", line 175,
in assertIsNotNone
   raise NotNoneAssertionError, msg
NotNoneAssertionError: RSpec returned from 'ListResources' is
unexpectedly 'None'
----------------------------------------------------------------------

V1 never guaranteed that you would get, well, anything, if your
credentials are bad.
```

I was able to reproduce this with a gcf-am.py running in v1.  Luisa has been using the test against v2 and v3 AMs and reports no issues with the tests.

 _Imported from trac ticket [#229](http://trac.gpolab.bbn.com/gcf/ticket/229),  created by sedwards on 12-21-2012 at 16:38, last modified: 01-08-2013 at 16:55_
   CCing: nick.bastin@...

**Comment by seledwards** [comment]
First, I was able to reproduce this using the gcf-am.py and this is indeed a bug.

After some poking, I was able to determine that this bug first appeared in gcf-2.0 when we did a major revamp of omni and added v3 to the acceptance tests.  I don't know how we missed this before.

In particular there are several tests that fail similarly. 

As Nick notes in his email, `test_ListResources_untrustedCredential` fails because the AM returns `None` instead of an RSpec in the case of a failure.  Allowing `NotNoneAssertionError` fixes this bug.

Testing against foam1.gpolab.bbn.com showed similar issues with `test_ListResources_badCredential_alteredObject` and `test_ListResources_badCredential_malformedXML`.

I'm checking in fixes to those on a branch `fixingv1accept`.

_Trac comment by sedwards (github user: seledwards) on 12-21-2012 at 16:49_

**Comment by seledwards** [comment]
To run against FOAM in the GPO lab:

```
./am_api_accept.py -c ~/.gcf/omni_config -a https://foam1.gpolab.bbn.com:3626/foam/gapi/1  -V 1 --sleep-time 0 
```

_Trac comment by sedwards (github user: seledwards) on 12-21-2012 at 17:44_

**Comment by ahelsing** [comment]
I believe a similar fix is required for `subtest_ListResources_slice_with_usercred` (test by running `test_CreateSliver`) and for `subtest_ListResources_wrongSlice` (run from `test_CreateSliverWorkflow_multiSlice`)

Note though that this appears to allow a v2 AM to return None instead of the proper AM API error code. A little refactoring would be required to catch that properly (like 2 assertRaises calls, depending on the API version)

I confirmed that Sarah's fixes allow tests to work at PGv1 and PGv2.

_Trac comment by ahelsing on 12-28-2012 at 13:19_

**Comment by seledwards** [comment]
Ok.  These fixes (and some others) are in on the branch.  Will merge with master in a smidge.

_Trac comment by sedwards (github user: seledwards) on 01-08-2013 at 11:06_

**Comment by seledwards** [comment]
Done.  Closing.

_Trac comment by sedwards (github user: seledwards) on 01-08-2013 at 16:55_
