### ISSUE TITLE
Acceptance tests: compare times to nearest second

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#231]
The acceptance tests compare timestamps for absolute equality. At some AMs - at least PLC - times are rounded to the nearest second. So to ensure success, we should compare times only to the nearest second. See assertTimestampsEqual

Additionally, we should only request sliver renewals that are whole seconds.

anywhere we grab 'now' it should look like this:
```
      now = datetime.datetime.utcnow().replace(microsecond=0)
```

 _Imported from trac ticket [#231](http://trac.gpolab.bbn.com/gcf/ticket/231),  created by ahelsing on 01-07-2013 at 14:20, last modified: 01-08-2013 at 16:54_

**Comment by seledwards** [comment]
Replaced all 3 uses of `utcnow` with a new method in `omni_unittest.py` called `now_in_seconds()` which implements the above code.

Changed `assertTimestampEquals` to check if the two times are within 1 second of each other.

_Trac comment by sedwards (github user: seledwards) on 01-08-2013 at 11:42_

**Comment by seledwards** [comment]
Done. Closing.

_Trac comment by sedwards (github user: seledwards) on 01-08-2013 at 16:54_
