### ISSUE TITLE
Wrong slice URN generates confusing error

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#243]
Using invalid slice URN `urn:publicid:IDN+portal:JBS+slice+jbstmp` instead of `urn:publicid:IDN+panther:JBS+slice+jbstmp` prompted the following error:

```
ERROR:omni.pgch:Failed to create new PG slice urn:publicid:IDN+portal:JBS+slice+jbstmp: local variable 'project_name' referenced before assignment (code 1)
```

Make this error be clearer.

 _Imported from trac ticket [#243](http://trac.gpolab.bbn.com/gcf/ticket/243),  created by sedwards on 02-11-2013 at 17:03, last modified: 05-29-2013 at 09:40_

**Comment by luisanevers** [comment]
Please elaborate on how the urn was used, not obvious from description how to validate resolution

_Trac comment by lnevers (github user: luisanevers) on 05-29-2013 at 08:45_

**Comment by ahelsing** [comment]
Call 'createslice' using your portal account.

Supply this URN:
`urn:publicid:IDN+portal:lnproject+slice+lntmp`

Note the use of 'portal' where it should say 'panther'.

(Substitute of course your project name for 'lnproject')


_Trac comment by ahelsing on 05-29-2013 at 09:02_

**Comment by luisanevers** [comment]
Verified, thank you.

_Trac comment by lnevers (github user: luisanevers) on 05-29-2013 at 09:40_
