### ISSUE TITLE
Inconsistent put from listmyslices operation in omni when using  Geniportal credentials

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#245]
1. When i do a listmyslices operation like below (using my geniportal credentials)

nasir@uw:~$ /opt/gcf/src/omni.py -c /tmp/my.cfg listmyslices urn:publicid:IDN+panther+user+nasir
INFO:omni:Loading config file /tmp/my.cfg
INFO:omni:Using control framework portal
INFO:omni:User 'urn:publicid:IDN+panther+user+nasir' has slice(s):
    hs1
INFO:omni: ------------------------------------------------------------
INFO:omni: Completed listmyslices:

  Options as run:
        configfile: /tmp/my.cfg
        framework: portal

  Args: listmyslices urn:publicid:IDN+panther+user+nasir

  Result Summary: Found 1 slice(s) for user 'urn:publicid:IDN+panther+user+nasir'.
 
INFO:omni: ============================================================

Omni lists my slicenames only and no urns which leads to my next question

2. Is there a way to find out using omni, the URN for such a slice  ?  I cannot assume that " urn:publicid:IDN+panther+slice+hs1" is valid because it does not have the project name in its domain section .
It would be good if omni /Genidesktop just reports back all my slice names with the complete URNs (with the proper projectname-slicename combinations)

 _Imported from trac ticket [#245](http://trac.gpolab.bbn.com/gcf/ticket/245),  created by nasir on 02-27-2013 at 12:12, last modified: 03-27-2013 at 12:08_

**Comment by seledwards** [comment]
This was supposed to be fixed in ticket #317. 

_Trac comment by sedwards (github user: seledwards) on 02-27-2013 at 13:36_

**Comment by seledwards** [comment]
Replying to [sedwards](comment:2):
> This was supposed to be fixed in ticket #317. 

Sorry, that's #317 on the portal/ch trac system: http://trac.gpolab.bbn.com/proto-ch/ticket/317

_Trac comment by sedwards (github user: seledwards) on 02-27-2013 at 13:44_

**Comment by ahelsing** [comment]
Well i still see slicenames reported as one string instead of a URN

 INFO:omni:User 'urn:publicid:IDN+panther+user+nasir' has slice(s):
    hs1

Its almost impossible to identify which slicename is associated with which project to form the correct slice URN, in order to query the AM for manifest. (Particuarly in the case where a single user is associated with multiple project names.)

_Trac comment by nasir on 03-11-2013 at 16:43_

**Comment by ahelsing** [comment]
Yes, the issue exists. We are using the PG Resolve call basically. Elsewhere we only show the slice name (for PG SAs), so we just need to do a usability / consistency design that works here.


_Trac comment by ahelsing on 03-11-2013 at 16:47_

**Comment by ahelsing** [comment]
I will make listmyslices print slice URNs, not names


_Trac comment by ahelsing on 03-26-2013 at 14:55_

**Comment by ahelsing** [comment]
listmyslices now returns the full URN

EG:
```
INFO:omni:User 'ahelsing' has slice(s): 
	urn:publicid:IDN+panther:ahscaletest+slice+ahtest
INFO:omni: ------------------------------------------------------------
```

This should work now, with Omni 2.2.1

This is also true for all other SAs in Omni 2.3.



_Trac comment by ahelsing on 03-27-2013 at 12:08_
