### ISSUE TITLE
BUSY result detection checks wrong slots

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#247]
In dossl, is_busy_result looks in old style protogeni codes, not the new AM API v2 geni_code slots. So busy results are never detected.

 _Imported from trac ticket [#247](http://trac.gpolab.bbn.com/gcf/ticket/247),  created by ahelsing on 02-27-2013 at 16:25, last modified: 05-29-2013 at 09:53_

**Comment by luisanevers** [comment]
Please elaborate on how this can be verified.

_Trac comment by lnevers (github user: luisanevers) on 05-29-2013 at 09:03_

**Comment by ahelsing** [comment]
Unfortunately it is hard. 
A bunch of rapid calls to createsliver/sliverstatus/renewsliver/listresources/etc at a ProtoGENI/InstaGENI node _might_ elicit this behavior.
If the fix fails, Omni will respond immediately with an error indicating the resource/slice/sliver was busy.
If the fix works, you'll see log messages indicating omni is sleeping for 10 seconds and trying again (up to 3 times).


_Trac comment by ahelsing on 05-29-2013 at 09:10_

**Comment by seledwards** [comment]
I'm pretty sure I've seen this behavior (or something very similar).

Try alternating createsliver and deletesliver on the same slice with the same rspec a few times (just reserve a VM, delete it, rinse and repeat).

_Trac comment by sedwards (github user: seledwards) on 05-29-2013 at 09:32_

**Comment by luisanevers** [comment]
Reproduced with sliverstatus and listresources for sliver, but only saw two messages about "Retrying in 10 seconds", I assume there is no third message, omni exits at that poing. Sample below

```
INFO:omni:Status of Slice urn:publicid:IDN+panther:ln-prj+slice+lnslice1:
INFO:omni.pgch:Detected busy result for SliverStatus of urn:publicid:IDN+panther:ln-prj+slice+lnslice1 at https://boss.instageni.gpolab.bbn.com:12369/protogeni/xmlrpc/am/2.0. Retrying in 10 seconds.
INFO:omni.pgch:Detected busy result for SliverStatus of urn:publicid:IDN+panther:ln-prj+slice+lnslice1 at https://boss.instageni.gpolab.bbn.com:12369/protogeni/xmlrpc/am/2.0. Retrying in 10 seconds.
INFO:omni: ------------------------------------------------------------
INFO:omni: Completed sliverstatus:

  Options as run:
		aggregate: ['ig-gpo']
		framework: portal
		output: True
		project: ln-prj

  Args: sliverstatus lnslice1

  Result Summary: Slice urn:publicid:IDN+panther:ln-prj+slice+lnslice1 expires within 1 day(s) on 2013-05-29 21:44:01 UTC

Failed to get SliverStatus on lnslice1 at AM https://boss.instageni.gpolab.bbn.com:12369/protogeni/xmlrpc/am/2.0: Error from Aggregate: code 14. protogeni AM code: 14: resource is busy; try again later (PG log url - look here for details on any failures: https://boss.instageni.gpolab.bbn.com/spewlogfile.php3?logfile=649149ae4ab24944936683903d9ed71c).

```

_Trac comment by lnevers (github user: luisanevers) on 05-29-2013 at 09:47_

**Comment by ahelsing** [comment]
Right, that is the expected behavior. It tries a total of 3 times.

_Trac comment by ahelsing on 05-29-2013 at 09:53_
