### ISSUE TITLE
PG CH/SA calls should log error_log URL

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#251]
Calls to the PG CH/SA also include a protogeni_error_url. Include that in logs / returns.

 _Imported from trac ticket [#251](http://trac.gpolab.bbn.com/gcf/ticket/251),  created by ahelsing on 03-01-2013 at 12:18, last modified: 05-29-2013 at 10:54_

**Comment by ahelsing** [comment]
EG resolve slice gives
```
{
  'output': '', 
  'protogeni_error_log': 'urn:publicid:IDN+emulab.net+log+e8d2be28fa12e65662d38d2ee9362f66', 
  'code': 0, 
  'value': {'creator_uuid': ... g'}, 
  'protogeni_error_url': 'https://www.emulab.net/spewlogfile.php3?logfile=e8d2be28fa12e65662d38d2ee9362f66'
}
```


_Trac comment by ahelsing on 03-01-2013 at 12:20_

**Comment by ahelsing** [comment]
Leigh notes that if there is no server side error, the URL will be broken, but we should include the URL anyhow.

_Trac comment by ahelsing on 04-08-2013 at 15:41_

**Comment by luisanevers** [comment]
Please elaborate, which commands use the resolve slice?


_Trac comment by lnevers (github user: luisanevers) on 05-29-2013 at 10:34_

**Comment by ahelsing** [comment]
You should see this for any clearinghouse command where there is an error or if you use --debug

EG
getusercred
getslicecred
createslice
renewslice

Note this works only at a newer PG based SA - so not at pgeni


_Trac comment by ahelsing on 05-29-2013 at 10:54_
