### ISSUE TITLE
readyToLogin.py fails for exogeni bare metal nodes

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-tools#253]
In a scenario where two ExoGENI bare metal nodes are part of a sliver, the script readyToLogin.py fails as follows:

$ readyToLogin.py -a eg-sm EG-EXP-1
ERROR:omni.protogeni:Call for Get Slice Cred for slice urn:publicid:IDN+pgeni.gpolab.bbn.com+slice+EG-EXP-1 failed.: Exception: PG Slice urn:publicid:IDN+pgeni.gpolab.bbn.com+slice+EG-EXP-1 does not exist.
ERROR:omni.protogeni:    ..... Run with --debug for more information
ERROR:omni:Cannot do listresources for urn:publicid:IDN+pgeni.gpolab.bbn.com+slice+EG-EXP-1: Could not get slice credential: Exception: PG Slice urn:publicid:IDN+pgeni.gpolab.bbn.com+slice+EG-EXP-1 does not exist.
ERROR: There was an error executing listresources, review the logs.
}}}

The sliverstatus shows the overall status as ready and the listresources does include login information.  Attaching the request rspec and the manifest rspec.

 _Imported from trac ticket [#253](http://trac.gpolab.bbn.com/gcf/ticket/253),  created by lnevers on 03-11-2013 at 09:02, last modified: 03-11-2013 at 09:56_

**Comment by luisanevers** [comment]
_lnevers (luisanevers) attached [EG-EXP-1-2baremetal.rspec](http://trac.gpolab.bbn.com/gcf/attachment/ticket/253/EG-EXP-1-2baremetal.rspec) on 03-11-2013 at 09:03_

**Comment by luisanevers** [comment]
_lnevers (luisanevers) attached [IG-EXP-1-manifest-rspec-geni-renci-org-11443-orca.xml](http://trac.gpolab.bbn.com/gcf/attachment/ticket/253/IG-EXP-1-manifest-rspec-geni-renci-org-11443-orca.xml) on 03-11-2013 at 09:03_

**Comment by ahelsing** [comment]
Your manifest is for IG-EXP-1.
listmyslices at pgeni for lnevers shows there is no EG-EXP-1 slice.
I do see these though:
```
	urn:publicid:IDN+pgeni.gpolab.bbn.com+slice+EG-EXP-2-exp1
	urn:publicid:IDN+pgeni.gpolab.bbn.com+slice+IG-EXP-1
```
The error logs above say your slice has expired or never existed.

Can you verify that your slice exists?



_Trac comment by ahelsing on 03-11-2013 at 09:33_

**Comment by luisanevers** [comment]
AARGGHH!!! I am updating earlier test results for ExoGENI (EG) acceptance tests and after a week of testing InstaGENI (IG) my finger have not made the switch :-). Sorry closing ticket.


_Trac comment by lnevers (github user: luisanevers) on 03-11-2013 at 09:56_
