### ISSUE TITLE
Add new Aggregates to the  agg_nick_cache

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-tools#258]
Update the production aggregates in the `agg_nick_cache`.

 1. Update the file `gcf/agg_nick_cache.base`
 2. Upload a version of this file as `agg_nick_cache` to [http://trac.gpolab.bbn.com/gcf/attachment/wiki/Omni/agg_nick_cache] which is an attachment to the [Omni page](http://trac.gpolab.bbn.com/gcf/wiki/Omni)

 _Imported from trac ticket [#258](http://trac.gpolab.bbn.com/gcf/ticket/258),  created by lnevers on 04-08-2013 at 11:03, last modified: 02-04-2014 at 23:37_
   CCing: nriga@...

**Comment by ahelsing** [comment]
Heidi says we aren't allowed to include these until the site operator gives the official thumbs up. So far, that means only Kentucky.

_Trac comment by ahelsing on 04-08-2013 at 15:51_

**Comment by luisanevers** [comment]
I will keep adding the aggregates as they come up, just to track their URLs in one list.  I will add status for Operator thumbs up, if I hear about it.



_Trac comment by lnevers (github user: luisanevers) on 04-08-2013 at 15:53_

**Comment by ahelsing** [comment]
ig-ky added to the sample files and omni-configure

_Trac comment by ahelsing on 04-08-2013 at 16:13_

**Comment by ahelsing** [comment]
note that additions go in omni_config.sample, acceptance_tests/AM_API/omni_config.sample, and src/omni-configure.py

_Trac comment by ahelsing on 04-09-2013 at 10:08_

**Comment by seledwards** [comment]
Do we need to do anything on this ticket for our release this week?

_Trac comment by sedwards (github user: seledwards) on 05-20-2013 at 11:31_

**Comment by ahelsing** [comment]
Heidi says we should add IG-GATech and IG-Kettering to the official lists

_Trac comment by ahelsing on 05-21-2013 at 13:01_

**Comment by seledwards** [comment]
Looks like Aaron added these.

_Trac comment by sedwards (github user: seledwards) on 05-23-2013 at 17:57_

**Comment by ahelsing** [comment]
Keep this ticket open for future additions.

_Trac comment by ahelsing on 05-24-2013 at 10:26_

**Comment by luisanevers** [comment]
Adding Princeton, which is currently undergoing Confirmation Testing that may be completed today:
```
ig-princeton=,https://instageni.cs.princeton.edu:12369/protogeni/xmlrpc/am
ig-of-princeton=,https://foam.instageni.cs.princeton.edu:3626/foam/gapi/1
```

Clemson is also an upcoming InstaGENI sites that should undergo Confirmation Testing soon:
```
ig-clemson=,https://instageni.clemson.edu:12369/protogeni/xmlrpc/am
ig-of-clemson=,https://foam.instageni.clemson.edu:3626/foam/gapi/1
```


_Trac comment by lnevers (github user: luisanevers) on 05-24-2013 at 10:38_

**Comment by luisanevers** [comment]
The GA Tech and the Kettering nick names do not exist in the omni_config from the portal bundle.  Should the omni_config in gcf deliver the same nick_names as the portal omni_config?

Also New Site Confirmation tests have been completed for Princeton, which can be added to omni_config.

_Trac comment by lnevers (github user: luisanevers) on 05-29-2013 at 09:52_

**Comment by tcmitchell** [comment]
Note that according to http://groups.geni.net/geni/wiki/GENIProduction clemson, princeton, and gatech have not been deemed production aggregates as of August 22, 2013.

_Trac comment by tmitchel (github user: tcmitchell) on 08-23-2013 at 09:22_

**Comment by ahelsing** [comment]
Just to confirm, they are still not production, but at least they are progressing.  We'll let you know when they pass the threshold.

_Trac comment by tupty on 08-23-2013 at 09:35_

**Comment by ahelsing** [comment]
Per Heidi on syseng ticket 5297, add these nicknames (and use this format for future rack aggregates):
```
gpo-ig

gpo-eg

kettering-ig

northwestern-ig

renci-eg

uky-ig

uky-pg

utah-ig

utah-pg
```


_Trac comment by ahelsing on 08-26-2013 at 14:40_

**Comment by seledwards** [comment]
Updating this ticket to reflect that due to #352, aggregate info is now located in `agg_nick_cache`.

When we are ready, I think we can roll this ticket to the next release number.

_Trac comment by sedwards (github user: seledwards) on 09-03-2013 at 17:17_

**Comment by ahelsing** [comment]
Sarah
 - please add the nicknames listed in comment 15
 - please add the URNs for the EG racks, ig-of-kettering, ig-of-uky, ig-of-bbn, ig-of-utah and plc. AM URNs can be found on the aggregate pages (thanks to Luisa)

_Trac comment by ahelsing on 09-04-2013 at 08:30_

**Comment by seledwards** [comment]
I added these and uplaoded the latest `agg_nick_cache` file.


_Trac comment by sedwards (github user: seledwards) on 09-04-2013 at 15:22_

**Comment by ahelsing** [comment]
This is ongoing. Useless any more as a ticket.

_Trac comment by ahelsing on 02-04-2014 at 23:37_
