### ISSUE TITLE
nicknames for RSpecs

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#265]
If we had nicknames for rspecs (like we do for AMs) we could make omni easier to use.

`omni_config` could have a mapping between a nickname (`vm`) and an rspec (either a path to a file distributed with omni or a url to download the rspec from).  Custom rspecs could be added to the omni_config by pointing to a file on the file system.
```
[nicknames](rspec)
vm = http://...../onevm_rspec.xml
2vm = http://...../twovm_rspec.xml
awesomespecialtopology = /home/jdoe/.gcf/rspecs/awesometopo_rspec.xml
```

If we were really awesome, we'd integrate this with the portal so that the default rspecs in the `omni_config` were the same as the public ones on the portal.

 _Imported from trac ticket [#265](http://trac.gpolab.bbn.com/gcf/ticket/265),  created by sedwards on 05-03-2013 at 17:52, last modified: 06-04-2013 at 16:30_
   CCing: nriga@...

**Comment by seledwards** [comment]
I think the omni_config should have a new section [rspec_nicknames] which allows you to specify nicknames in a couple of different ways.

Here's an example...

```
========== EXAMPLE BEGIN ===========
[rspec_nicknames]
nikysawesometopology = http://www.mywebserver.edu/geni/rspecs/awesome.rspec
nsdi-topology-12 = /home/nriga/geni/rspecs/myrspecfile.rspec

default_rspec_server = http://rspecs.geni.net
default_rspec_extension = rspec
========== EXAMPLE END ===========
```

When you made an omni call, it would continue to look like this:
	`omni.py createsliver mySlice <rspec_definition>`

And <rspec_definition> would be interpreted in the following order:
1. is a URL 
	* ie starts with "http://", "https://", or "ftp://"
2. is a file on the local system 
	* ie os.path.exists(<rspec_definition>) is true
3. is a nickname specified in the omni_config 
	* eg in the above example is one of `nikysawesometopology` or `nsdi-topology-1` above
4. is a file on a server defined as: <default_rspec_server>/<rspec_definition>.<default_rspec_extension> 
	* eg so if we ran:
		omni.py createsliver mySlice foo
	  using the omni_config defined above, we would find the file at: 
		http:/rspecs.geni.net/foo.rspec

Currently we do the first two of these (well, if it's not a url we assume it's a file and try to open it).  I'm proposing we add the next two.

In the medium term, if GENI/GPO decided to run a webserver with some standard rspecs (perhaps based on the public rspecs in the portal), we could make the default_rspec_server point to that by default.  But even if we didn't run an official webserver, folks could run their own webserver with some rspecs. 

PS Current handling of rspecs is in readFile() in gcf/src/omnilib/util/files.py

_Trac comment by sedwards (github user: seledwards) on 05-24-2013 at 22:38_

**Comment by ahelsing** [comment]
Suggestion: Make default_rspec_server be default_rspec_location instead, and parse it like 1 and 2 -- if it starts with (http|https|ftp)://, figure it's a URL; or if os.path.exists, figure it's a local directory.

_Trac comment by jbs on 05-24-2013 at 22:51_

**Comment by seledwards** [comment]
Done. Including jbs' suggestion about `default_rspec_location`.

Also changing `readFromLocalFile()` to expand `~` in paths using:
```
    filename = os.path.expanduser( filename )
```

Do we like this?  Any subtle changes anyone wants?

_Trac comment by sedwards (github user: seledwards) on 05-24-2013 at 23:29_

**Comment by seledwards** [comment]
To test need to try each of:
 * `createsliver`
 * `allocate`

For each of: 
 * rspec is a url
 * rspec is a file
 * rspec is a nickname (defined in the `omni_config`)
 * rpsec is a stored in the default_location

That's 8 combinations.

_Trac comment by sedwards (github user: seledwards) on 05-24-2013 at 23:50_

**Comment by seledwards** [comment]
Also nickname and default_location can each be a url or a filename.

This is basically done except for merging and any minor changes folks want.

_Trac comment by sedwards (github user: seledwards) on 05-29-2013 at 22:53_

**Comment by seledwards** [comment]
Merged onto master.

Resummarizing testing needed for this ticket...

To test need to try each of:
   * createsliver
   * allocate 

Also test:
   * rspec is a url
   * rspec is a file
for each of:
   * rspec is specified on the commandline 
   * rspec is a nickname (defined in the omni_config)
   * rpsec is a stored in the default_location 

That's potentially 12 combinations that need testing.  But we can probably prune that down a bit.

_Trac comment by sedwards (github user: seledwards) on 06-04-2013 at 16:30_
