### ISSUE TITLE
Rid omni-configure.py of having to use the -f portal flag for the portal case

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#271]
To run `omni-configure.py` with portal certificates, requires using the `-f portal` flag.  Make this not be the case.

 _Imported from trac ticket [#271](http://trac.gpolab.bbn.com/gcf/ticket/271),  created by sedwards on 05-20-2013 at 11:36, last modified: 05-23-2013 at 18:03_
   CCing: nriga@...

**Comment by seledwards** [comment]
Niky and I talked about this and we believe that there is a fundamental problem here.  Because the portal and other CHs use different default files (`omni-bundle.zip` vs just the cert and key) and a user may have both, we can't know which we should use to generate the `omni_config` without being told.

The best we can do is pick the default carefully.

_Trac comment by sedwards (github user: seledwards) on 05-20-2013 at 15:29_

**Comment by seledwards** [comment]
Niky, Aaron, and I discussed it and we like having the default be portal to match the anticipated SignMeUp switchover.

_Trac comment by sedwards (github user: seledwards) on 05-20-2013 at 16:58_

**Comment by innnkkki** [comment]
Fixed in commit [1ec2705030a0bc0dc38472944e68b1bdcb28cf93](https://github.com/GENI-NSF/geni-tools/commit/1ec2705030a0bc0dc38472944e68b1bdcb28cf93)

_Trac comment by nriga (github user: innnkkki) on 05-23-2013 at 18:03_
