### ISSUE TITLE
Update READMEs to match changes to gcf wiki

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#272]
We updated the gcf wiki.  Make sure those changes get incorporated back into the git repo.

 _Imported from trac ticket [#272](http://trac.gpolab.bbn.com/gcf/ticket/272),  created by sedwards on 05-20-2013 at 11:39, last modified: 06-04-2013 at 14:01_

**Comment by innnkkki** [comment]
Took a stab at this. 

Modified README-omni.txt, INSTALL.txt, INSTALL.centos

Added README-gcf.txt, INSTALL.ubuntu, INSTALL.fedora, INSTALL.centos, INSTALL.macos

_Trac comment by nriga (github user: innnkkki) on 05-29-2013 at 22:22_

**Comment by seledwards** [comment]
Niky did this.  Done.

_Trac comment by sedwards (github user: seledwards) on 06-04-2013 at 14:01_
