### ISSUE TITLE
Allow omni to query for slice membership and public keys and load onto slivers

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#278]
Since the Portal/CH allows for slice membership, omni could query the CH for the members of a slice and their public keys and load said public keys on slivers when they are created.

 _Imported from trac ticket [#278](http://trac.gpolab.bbn.com/gcf/ticket/278),  created by sedwards on 05-23-2013 at 11:46, last modified: 02-04-2014 at 23:36_
   CCing: nriga@..., jbs@...

**Comment by ahelsing** [comment]
I suspect the right thing here is to include the relevant stuff as an attribute in the dictionary returned by Resolve, even though PG itself doesn't do so. The alternative would be a new method.

_Trac comment by ahelsing on 05-23-2013 at 13:11_

**Comment by ahelsing** [comment]
See #491

_Trac comment by ahelsing on 02-04-2014 at 23:36_
