### ISSUE TITLE
Update clearpassphrase.py to handle privately held SSL certs

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#280]
If the user does a CSR their cert/private key may be in a different spot.

 _Imported from trac ticket [#280](http://trac.gpolab.bbn.com/gcf/ticket/280),  created by sedwards on 05-23-2013 at 16:56, last modified: 05-24-2013 at 19:23_
   CCing: nriga@...

**Comment by innnkkki** [comment]
Fixed at commit : [f014e8c2783841a13f39f7ef2cb661767d938799](https://github.com/GENI-NSF/geni-tools/commit/f014e8c2783841a13f39f7ef2cb661767d938799)

 Modified the script so that it works with the private key for the SSL cert i
    not part of the SSL cert file.
    
    Detailed modifications are:
      - replaced option -p with -k to specify a path for the private key that
      corresponds to the SSL cert
      - replaced option -k with -e to specify the path for the private SSH key
      - added option -c to specify an omni_config file.
      - be default the script works with an omni_config file where it parses
        the selected framework and users and finds the key for the SSL cert and 
        of the private SSH keys that are available on the system and removes the
        passphrases
      - if not options are specified it tries to find a default omni_config
        the order is the same as in omni.py
      - you can either run the script with an omni_config file or with
        the -k or -e options. If both -c and -k or -e options are specified, -c
        takes precedence. If -k or -e are specified without the -c, then those
        keys are decrypted, but the default omni_config is not looked at.


_Trac comment by nriga (github user: innnkkki) on 05-24-2013 at 19:23_
