### ISSUE TITLE
Make the label of the SA/CH type a variable in framework_pg

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#281]
framework_pgch says it is talking to 'PG' and it would be nice for this to say 'GENI Clearinghouse' or similar. If framework_pg made that a variable to be over-ridden, this would just work.

 _Imported from trac ticket [#281](http://trac.gpolab.bbn.com/gcf/ticket/281),  created by ahelsing on 05-23-2013 at 17:05, last modified: 05-29-2013 at 11:30_
   CCing: nriga@...

**Comment by luisanevers** [comment]
Used all clearinghouse/slice authority omni commands and did not fine "GENI Clearinghouse", did find "INFO:omni:Using control framework portal". Is this the change implemented for this ticket?

_Trac comment by lnevers (github user: luisanevers) on 05-29-2013 at 11:07_

**Comment by ahelsing** [comment]
That string appears in places where it used to say "PG". So if you do not see that, then the fix is in.

Try, EG:

`omni.py renewslice nosuchslice`


_Trac comment by ahelsing on 05-29-2013 at 11:19_

**Comment by luisanevers** [comment]
Ran suggested command:
```
$ omni.py renewslice nosuchslice 2013-05-31
INFO:omni:Loading config file /home/lnevers/.gcf/omni_config
INFO:omni:Using control framework portal
WARNING:omni.pgch:Cannot renew slice. Unable to get slice credential for slice urn:publicid:IDN+panther:ln-prj+slice+nosuchslice: Slice or user not found
WARNING:omni:Failed to renew slice nosuchslice
ERROR:omni.pgch:Call for Get Slice Cred for slice urn:publicid:IDN+panther:ln-prj+slice+nosuchslice failed.: Exception: GENI Clearinghouse Slice urn:publicid:IDN+panther:ln-prj+slice+nosuchslice does not exist.
ERROR:omni.pgch:    ..... Run with --debug for more information
INFO:omni: ------------------------------------------------------------
INFO:omni: Completed renewslice:

  Options as run:
		framework: portal
		project: ln-prj

  Args: renewslice nosuchslice 2013-05-31

  Result Summary: Failed to renew slice nosuchslice
 
INFO:omni: ============================================================
```}

Do not see "PG" fix is verified

_Trac comment by lnevers (github user: luisanevers) on 05-29-2013 at 11:30_
