### ISSUE TITLE
Remove typos from omni-configure.py -h

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#282]
The help message has some typos.

Clarify which certs and keys are SSL certs and keys.

 _Imported from trac ticket [#282](http://trac.gpolab.bbn.com/gcf/ticket/282),  created by sedwards on 05-23-2013 at 17:37, last modified: 05-24-2013 at 19:37_
   CCing: nriga@...

**Comment by innnkkki** [comment]
Fixed at [0a1c0fd8696f73103ee148dd64cc5e65eeceed6b](https://github.com/GENI-NSF/geni-tools/commit/0a1c0fd8696f73103ee148dd64cc5e65eeceed6b)

_Trac comment by nriga (github user: innnkkki) on 05-24-2013 at 19:37_
