### ISSUE TITLE
If your SSH private key is not same of your SSL private key, generate one for use with some tools.

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#283]
If your SSH private key is not same of your SSL private key, generate one for use with some tools.

 _Imported from trac ticket [#283](http://trac.gpolab.bbn.com/gcf/ticket/283),  created by sedwards on 05-23-2013 at 18:05, last modified: 05-30-2013 at 08:24_

**Comment by innnkkki** [comment]
Fixed at commit [9afa135a4f51da1a61f4186bd30f40eef05eb4d7](https://github.com/GENI-NSF/geni-tools/commit/9afa135a4f51da1a61f4186bd30f40eef05eb4d7)

_Trac comment by nriga (github user: innnkkki) on 05-24-2013 at 20:02_

**Comment by luisanevers** [comment]
Please elaborate on how this change can be verified

_Trac comment by lnevers (github user: luisanevers) on 05-30-2013 at 08:24_
