### ISSUE TITLE
remote-execute fails with options has not attribute include_keys

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#291]
Calling remote-execute gives an error:
```
Traceback (most recent call last):
  File "/home/lnevers/gcf-2.3-rc3/examples/remote-execute.py", line 160, in <module>
    sys.exit(main())
  File "/home/lnevers/gcf-2.3-rc3/examples/remote-execute.py", line 141, in main
    loginInfoDict, keyList = readyToLogin.main_no_print(argv=argv, opts=options, slicen = slicename)
  File "/home/lnevers/gcf-2.3-rc3/examples/readyToLogin.py", line 569, in main_no_print
    keyList = findUsersAndKeys( options.include_keys )
AttributeError: Values instance has no attribute 'include_keys'
(follow-up: ↓ 29 )
```

Apparently the added include_keys to the options parser in readyToLogin is not being added or preserved somehow.

 _Imported from trac ticket [#291](http://trac.gpolab.bbn.com/gcf/ticket/291),  created by ahelsing on 05-30-2013 at 16:34, last modified: 05-30-2013 at 18:49_

**Comment by innnkkki** [comment]
Fixed in [bb78f255de5729f5aa0e4176b088fc7e81f19df1](https://github.com/GENI-NSF/geni-tools/commit/bb78f255de5729f5aa0e4176b088fc7e81f19df1)

Added the option to the getParser() function, since this is
    called by all scripts that include readyToLogin.


_Trac comment by nriga (github user: innnkkki) on 05-30-2013 at 18:49_
