### ISSUE TITLE
framework_pgch should not require a project if URN is given

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#293]
If a full URN is supplied, we do not need a project name on the command line nor a default project in the omni_config.

Currently however we require that. That is wrong.

 _Imported from trac ticket [#293](http://trac.gpolab.bbn.com/gcf/ticket/293),  created by ahelsing on 06-05-2013 at 16:42, last modified: 06-12-2013 at 17:28_
   CCing: nasir@...

**Comment by seledwards** [comment]
This is a problem in `slice_name_to_urn()` in `framework_pgch.py`.  It explicitly checks that either a `default_project` is defined in the `omni_config` or `-r` is passed on the command line.

Instead, you should allow the URN checks to succeed if a slice URN is provided but a project is not.  And delay checking for a project for the case where you have provided a name and must construct the URN from that name.


_Trac comment by sedwards (github user: seledwards) on 06-05-2013 at 18:03_

**Comment by seledwards** [comment]
Fixed. 

Here is what I did to test...

I created a slice (`urn:publicid:IDN+ch.geni.net:tutorial+slice+foobar`).

I also created two omni_configs. One with a default_project configured (`omni_config.nye`) and the other without (`omni_config.nye.nodefaultproject`).

I tried to `getslicecred` for several cases.

As expected, with no project defined and no slice URN, the command failed.

```
$ ./omni.py -c ~/.gcf/omni_config.nye.nodefaultproject -o  getslicecred foobar
INFO:omni:Loading config file /Users/sedwards/.gcf/omni_config.nye.nodefaultproject
INFO:omni:Using control framework portal
Traceback (most recent call last):
  File "./omni.py", line 865, in <module>
    sys.exit(main())
  File "./omni.py", line 852, in main
    API_call(framework, config, args, opts, verbose=opts.verbose)
  File "./omni.py", line 483, in API_call
    result = handler._handle(args)
  File "/Users/sedwards/projects/GENI/code/gcf/src/omnilib/handler.py", line 78, in _handle
    return getattr(self.chhandler, call)(args[1:])
  File "/Users/sedwards/projects/GENI/code/gcf/src/omnilib/chhandler.py", line 448, in getslicecred
    urn = self.framework.slice_name_to_urn(name)
  File "/Users/sedwards/projects/GENI/code/gcf/src/omnilib/frameworks/framework_pgch.py", line 166, in slice_name_to_urn
    raise Exception("Invalid configuration: no default project defined")
Exception: Invalid configuration: no default project defined
```

As expected, with no project defined and a slice URN, the command succeeded.

```
 ./omni.py -c ~/.gcf/omni_config.nye.nodefaultproject -o  getslicecred urn:publicid:IDN+ch.geni.net:tutorial+slice+foobar

INFO:omni:Loading config file /Users/sedwards/.gcf/omni_config.nye.nodefaultproject
INFO:omni:Using control framework portal
INFO:omni:Slice urn:publicid:IDN+ch.geni.net:tutorial+slice+foobar expires within 1 day on 2013-06-06 05:36:46 UTC
INFO:omni:Retrieved slice cred for slice urn:publicid:IDN+ch.geni.net:tutorial+slice+foobar
INFO:omni:Wrote slice urn:publicid:IDN+ch.geni.net:tutorial+slice+foobar credential to file 'urn:publicid:IDN+ch.geni.net:tutorial+slice+foobar-cred.xml'
INFO:omni: ------------------------------------------------------------
INFO:omni: Completed getslicecred:

  Options as run:
		configfile: /Users/sedwards/.gcf/omni_config.nye.nodefaultproject
		framework: portal
		output: True

  Args: getslicecred urn:publicid:IDN+ch.geni.net:tutorial+slice+foobar

  Result Summary: Saved slice urn:publicid:IDN+ch.geni.net:tutorial+slice+foobar cred to file urn:publicid:IDN+ch.geni.net:tutorial+slice+foobar-cred.xml
INFO:omni: ============================================================
```

And likewise the several others tests succeeded in a similar fashion.

They are:
 * with a default_project defined and a slice URN, the command succeeded:
```
$ ./omni.py -c ~/.gcf/omni_config.nye -o  getslicecred urn:publicid:IDN+ch.geni.net:tutorial+slice+foobar
```
 * with a default_project defined and only a slice name, the command succeeded:
```
$ ./omni.py -c ~/.gcf/omni_config.nye -o  getslicecred foobar
```
 * with a project defined with `-r` and only a slice name, the command succeeded:
```
$ ./omni.py -c ~/.gcf/omni_config.nye.nodefaultproject -o  getslicecred foobar
```



_Trac comment by sedwards (github user: seledwards) on 06-05-2013 at 18:13_
