### ISSUE TITLE
omni_config aggregates parameter is sensitive to whitespace

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#31]
If there is whitespace in the aggregates parameter in omni_config the value is not interpreted properly. This may simply be a matter of stripping whitespace after the value is split.

 _Imported from trac ticket [#31](http://trac.gpolab.bbn.com/gcf/ticket/31),  created by tmitchel on 10-14-2010 at 10:19, last modified: 10-20-2010 at 15:05_

**Comment by ahelsing** [comment]
Fixed in HEAD - now stripping WS


_Trac comment by ahelsing on 10-20-2010 at 12:53_
