### ISSUE TITLE
Make CF settable with an environment variable

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#315]
It'd be neat if you could pick your Omni CF with an environment variable -- the equivalent of editing your omni_config to change default_cf, but without having to actually edit the file. Useful for scripting things that want to vary what CF is used, for example, especially copy-and-paste type "scripting" where you want a single command line to work for any CF.

 _Imported from trac ticket [#315](http://trac.gpolab.bbn.com/gcf/ticket/315),  created by jbs on 07-05-2013 at 16:51, last modified: 02-13-2014 at 08:07_

**Comment by ahelsing** [comment]
_nick.bastin attached [315.diff](http://trac.gpolab.bbn.com/gcf/attachment/ticket/315/315.diff) on 12-07-2013 at 05:40_

**Comment by ahelsing** [comment]
There is a commandline argument to specify the CF and over-riding the omni_config default_cf. Wouldn't that let your scripting thing work?


_Trac comment by ahelsing on 08-05-2013 at 11:04_

**Comment by ahelsing** [comment]
Yeah, it's less scripts per se (which can use '-f' just fine), and more the copy-and-paste type stuff I do a lot of, in which I don't generally specify a '-f' at all. But I suppose I could, and I suspect that no one else cares much about this, so maybe I should just cope. (grin)

I think that if no one else has ever expressed any interest in this sort of thing, it's fine to close it as wontfix.

_Trac comment by jbs on 08-05-2013 at 11:08_

**Comment by ahelsing** [comment]
Patch attached that adds this functionality.

_Trac comment by nick.bastin on 12-07-2013 at 05:40_

**Comment by ahelsing** [comment]
To do: testing, and document in README-omni

_Trac comment by ahelsing on 12-07-2013 at 09:27_

**Comment by luisanevers** [comment]
Verified new environment variable GENI_FRAMEWORK for omni and README-omni.txt in version gcf-2.5-021214pm.

_Trac comment by lnevers (github user: luisanevers) on 02-13-2014 at 08:07_
