### ISSUE TITLE
am_api_accept.py should include a test for get_ch_version

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#316]
The gcf API acceptance test framework should include a test which runs get_ch_version and makes sure its output looks okay.

 _Imported from trac ticket [#316](http://trac.gpolab.bbn.com/gcf/ticket/316),  created by chaos on 07-08-2013 at 14:29, last modified: 07-08-2013 at 17:02_

**Comment by seledwards** [comment]
Test added in commit:
```
commit [7ab67aff7c5c214229cf28856e25145d6aac484f](https://github.com/GENI-NSF/geni-tools/commit/7ab67aff7c5c214229cf28856e25145d6aac484f)
Merge: dfaaaec bb51eba
Author: Sarah Edwards <sedwards@bbn.com>
Date:   Mon Jul 8 15:29:35 2013 -0400

    Merge branch 'tkt316-get_ch_version-test' into develop
```

_Trac comment by sedwards (github user: seledwards) on 07-08-2013 at 15:30_

**Comment by ahelsing** [comment]
FYI: this works against ch.geni.net, but reports failure against emulab.net, even though emulab.net does respond to the `get_ch_version` call.  (I assume the return value is different and this is not unexpected, but i wanted to mention it just in case.)

For my purposes, working against ch.geni.net is sufficient for now.

_Trac comment by chaos on 07-08-2013 at 16:27_

**Comment by seledwards** [comment]
Ah!  Because I checked for the "api" field and that it was a float.  Maybe that's not what PG returns.  This is easy to fix if we want to.

_Trac comment by sedwards (github user: seledwards) on 07-08-2013 at 17:02_
