### ISSUE TITLE
omni uses default config file if specified config file does not exist

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#32]
If a config file is specified by the -c option and it does not exist, omni does not report any warning or error. Instead it silently falls back to one of the default locations.

If the user specifies a config file that does not exist it should report the issue to the user so that it can be corrected. In this case, omni should probably exit rather than use a config file other than the one specified on the command line.

 _Imported from trac ticket [#32](http://trac.gpolab.bbn.com/gcf/ticket/32),  created by tmitchel on 10-28-2010 at 11:44, last modified: 11-09-2010 at 18:23_

**Comment by seledwards** [comment]
commit [7c7876e0870339994917c6182dbda1939f67de76](https://github.com/GENI-NSF/geni-tools/commit/7c7876e0870339994917c6182dbda1939f67de76)
Author: Sarah Edwards <sedwards@localhost.localdomain>
Date:   Tue Nov 9 00:31:22 2010 -0500

   Fix for Trac #32.

   If configfile defined in command line does not exist, then exit with an error message.

Summary of changes:
src/omni.py |    7 ++++++-
1 files changed, 6 insertions(+), 1 deletions(-)

_Trac comment by sedwards (github user: seledwards) on 11-09-2010 at 18:23_
