### ISSUE TITLE
explicitly include framework files to support py2exe

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#322]
Omni dynamically determines what framework_?.py file to load. As a result those files are not explicitly referenced/included.
And that means that py2exe doesn't include the files.

Explicitly including the files would solve this.

 _Imported from trac ticket [#322](http://trac.gpolab.bbn.com/gcf/ticket/322),  created by ahelsing on 07-16-2013 at 11:52, last modified: 08-08-2013 at 12:53_
   CCing: epittore@...

**Comment by ahelsing** [comment]
IE in omni.py the following works:
```
99a100,116
> #####
> ###following added for py2exe
> #####
> import omnilib.frameworks.frameworks.framework_apg
> import omnilib.frameworks.frameworks.framework_base
> import omnilib.frameworks.frameworks.framework_gcf
> import omnilib.frameworks.frameworks.framework_gch
> import omnilib.frameworks.frameworks.framework_gib
> import omnilib.frameworks.frameworks.framework_of
> import omnilib.frameworks.frameworks.framework_pg
> import omnilib.frameworks.frameworks.framework_pgch
> import omnilib.frameworks.frameworks.framework_sfa
>
> #####
> ###end py2exe additions
> #####
```

Alternatively, perhaps `import omnilib.frameworks` or similar would work.



_Trac comment by ahelsing on 07-16-2013 at 12:14_

**Comment by luisanevers** [comment]
Verified in gcf-2.4-preview8

_Trac comment by lnevers (github user: luisanevers) on 08-08-2013 at 12:53_
