### ISSUE TITLE
stitching: limit DCN retries to 2 or 3

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#332]
Chad says OSCARS failures are fewer but not gone. So don't retry the exact same thing 10 times - but maybe 2 or 3.

Related, eventually we may want some messages that always mean this particular VLAN combination will never work.

 _Imported from trac ticket [#332](http://trac.gpolab.bbn.com/gcf/ticket/332),  created by ahelsing on 08-05-2013 at 11:44, last modified: 08-08-2013 at 12:51_

**Comment by luisanevers** [comment]
Verified in gcf-2.4-preview8

_Trac comment by lnevers (github user: luisanevers) on 08-08-2013 at 12:48_

**Comment by luisanevers** [comment]
Verified that ION retry is 3 times in gcf-2.4-preview8

_Trac comment by lnevers (github user: luisanevers) on 08-08-2013 at 12:51_
