### ISSUE TITLE
renew to now or past should be an error

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#337]
Renewing your sliver to now or the past is almost certainly not what you intended. Either the resources are expired already, or this appears to be asking them to be expired - for which you should just call delete.

Raise an error if the user tries this.

 _Imported from trac ticket [#337](http://trac.gpolab.bbn.com/gcf/ticket/337),  created by ahelsing on 08-05-2013 at 16:19, last modified: 08-08-2013 at 12:57_

**Comment by luisanevers** [comment]
Verified with gcf-2.4-preview8. A renew to a past date report and error:

```
GENI Clearinghouse SA said: Invalid expiration time "2013-08-07T00:00:00". Cannot shorten slice expiration
```


_Trac comment by lnevers (github user: luisanevers) on 08-08-2013 at 12:57_
