### ISSUE TITLE
Querying the CH for list of AMs and their nicknames

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#348]
Instead of having a static list of AMs in the omni_config, we should query the CH for a list of AMs and their nicknames.

See [proto-ch 770](http://trac.gpolab.bbn.com/proto-ch/ticket/770) for the ticket on adding the necessary feature to the clearinghouse.

 _Imported from trac ticket [#348](http://trac.gpolab.bbn.com/gcf/ticket/348),  created by sedwards on 08-23-2013 at 13:05, last modified: 08-23-2013 at 14:55_
   CCing: gpo-expt-support@...

**Comment by tcmitchell** [comment]
omni supports `listaggregates` to fetch the current list of aggregates from the configured clearinghouse. If no aggregate is specified on the command line for many commands, the full list fetched from the clearinghouse is used (sliverstatus, renewsliver, deletesliver, listresources w/slice).

Nicknames are not available at any existing clearinghouses.


_Trac comment by tmitchel (github user: tcmitchell) on 08-23-2013 at 13:16_

**Comment by seledwards** [comment]
I'm closing this for the moment.  I spoke with Tom and we have a simple alternative I'd like to discuss with folks.

_Trac comment by sedwards (github user: seledwards) on 08-23-2013 at 14:55_
