### ISSUE TITLE
In readyToLogin, add support for multiple usernames at ExoGENI nodes

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#366]
ExoGENI just added the ability to create multiple usernames.  Add support for this in readyToLogin.py

 _Imported from trac ticket [#366](http://trac.gpolab.bbn.com/gcf/ticket/366),  created by sedwards on 09-11-2013 at 14:34, last modified: 09-17-2013 at 09:58_
   CCing: gpo-expt-support@...

**Comment by seledwards** [comment]
_sedwards (seledwards) attached [readyToLogin.2.py](http://trac.gpolab.bbn.com/gcf/attachment/ticket/366/readyToLogin.2.py) on 09-17-2013 at 09:57_

**Comment by ahelsing** [comment]
_ahelsing attached [readyToLogin.py](http://trac.gpolab.bbn.com/gcf/attachment/ticket/366/readyToLogin.py) on 09-13-2013 at 15:40_

**Comment by seledwards** [comment]
Just need to add a loop for the `<login>` tags in the manifest.

_Trac comment by sedwards (github user: seledwards) on 09-11-2013 at 14:35_

**Comment by ahelsing** [comment]
Hmm, so one question about this: If I use readyToLogin on a sliver with multiple logins, do I get an ssh_config fragment for all of them, or just one?

It seems to me like it'd be useful to be able to get just one, since if I'm creating accounts for multiple people, I probably don't have their private keys, and thus don't want ssh_config entries for them...

_Trac comment by jbs on 09-11-2013 at 14:37_

**Comment by seledwards** [comment]
Also have `getKeysforUser()` treat `orca` and `protogeni` AMs the same.

_Trac comment by sedwards (github user: seledwards) on 09-11-2013 at 17:37_

**Comment by seledwards** [comment]
Check that we're finding all keys and that status is still being printed.

_Trac comment by sedwards (github user: seledwards) on 09-12-2013 at 09:33_

**Comment by ahelsing** [comment]
There is no code in the script currently to get status for EG nodes.

2 ways that could be fixed:
 1. Parse the geni_sliver_info RSpec extension
 2. Supplement the information from the manifest with information from sliverstatus

I'm attaching a version of the script that
 - has the geni_sliver_info namespace hard coded, but manages to parse node status from that
 - has an untested method for using sliverstatus to get the status for a client_id
 - has a bunch of commented out printouts
 - fixes a couple error string printouts

In my own test scenario (not Luisa's) all my 3 users with their varying #s of keys are printed.


_Trac comment by ahelsing on 09-13-2013 at 15:39_

**Comment by luisanevers** [comment]
Replying to [ahelsing](comment:6):

> In my own test scenario (not Luisa's) all my 3 users with their varying #s of keys are printed.

In the latest case the user information is printed, but the remote-execute.py fails:
```
lnevers@sendaria:~/gcf-2.4-rc4$ readyToLogin.py -a eg-gpo lntest

...
For more login info, see the section entitled:
	 'Providing a private key to ssh' in 'readyToLogin.py -h'
User lnevers1 logs in to VM-1 using:
	ssh -i /home/lnevers1/.ssh/id_rsa lnevers1@192.1.242.18
User lnevers2 logs in to VM-1 using:
	ssh -i /home/lnevers2/.ssh/id_rsa lnevers2@192.1.242.18
User lnevers logs in to VM-1 using:
	ssh -i /home/lnevers/.ssh/geni_cert_portal_key lnevers@192.1.242.18
User lnevers1 logs in to VM-2 using:
	ssh -i /home/lnevers1/.ssh/id_rsa lnevers1@192.1.242.21
User lnevers2 logs in to VM-2 using:
	ssh -i /home/lnevers2/.ssh/id_rsa lnevers2@192.1.242.21
User lnevers logs in to VM-2 using:
	ssh -i /home/lnevers/.ssh/geni_cert_portal_key lnevers@192.1.242.21
lnevers@sendaria:~/gcf-2.4-rc4$ remote-execute.py -a eg-gpo lntest -m uptime

Find login Info for hosts in slice lntest
Key file [/home/lnevers/.ssh/luisa-mac-id_rsa] does NOT exist.
Key file [/home/lnevers/.ssh/sendaria-id_rsa] does NOT exist.
Key file [/home/lnevers/.ssh/arendia_id_rsa] does NOT exist.
Key file [/home/lnevers/.ssh/niky-geni_key] does NOT exist.
Key file [/home/lnevers/.ssh/scorpia-id_rsa] does NOT exist.
Key file [/home/lnevers/.ssh/niky-geni_key] does NOT exist.
There is no status information for a node. This script might fail. 
There is no status information for a node. This script might fail. 
There is no status information for a node. This script might fail. 
There is no status information for a node. This script might fail. 
There is no status information for a node. This script might fail. 
There is no status information for a node. This script might fail. 
There is no status information for a node. This script might fail. 
There is no status information for a node. This script might fail. 
Send command uptime to VM-1
Enter passphrase for key '/home/lnevers1/.ssh/id_rsa': 
```
Notice that I am running as lnevers, but the lnever1 information is being used.



_Trac comment by lnevers (github user: luisanevers) on 09-13-2013 at 15:47_

**Comment by seledwards** [comment]
Luisa, can you move the new `readyToLogin.py` from the `~/gcf-2.4-rc4` directory to the `~/gcf-2.4-rc4/examples` directory and try `remote-execute.py` again?

_Trac comment by sedwards (github user: seledwards) on 09-16-2013 at 13:32_

**Comment by luisanevers** [comment]
Replying to [sedwards](comment:8):
> Luisa, can you move the new `readyToLogin.py` from the `~/gcf-2.4-rc4` directory to the `~/gcf-2.4-rc4/examples` directory and try `remote-execute.py` again?

Both scripts are in examples directory, I am not sure what you want me to try:
```
lnevers@sendaria:~/gcf-2.4-rc4$ which readyToLogin.py
/home/lnevers/gcf-2.4-rc4/examples/readyToLogin.py
lnevers@sendaria:~/gcf-2.4-rc4$ which remote-execute.py
/home/lnevers/gcf-2.4-rc4/examples/remote-execute.py
```

Unless you meant to attach a new readyToLogin.py?  

_Trac comment by lnevers (github user: luisanevers) on 09-16-2013 at 13:42_

**Comment by seledwards** [comment]
Nope sorry.  I misread your original note.

_Trac comment by sedwards (github user: seledwards) on 09-16-2013 at 15:05_

**Comment by luisanevers** [comment]
The version of readyToLogin attached to this ticket was tested with gcf2.4 rc3, but was not checked in to gcf 2.4 rc4.  Sarah will check in missing changes.

Ran gcf 2.4 rc4 with the file attached to this ticket and here is the current output
for the remote-execute.py failure:
```
lnevers@sendaria:~/gcf-2.4-rc4/examples$ remote-execute.py -a eg-gpo lnnewer -m uptime
Find login Info for hosts in slice lnnewer
Key file [/home/lnevers/.ssh/luisa-mac-id_rsa] does NOT exist.
Key file [/home/lnevers/.ssh/sendaria-id_rsa] does NOT exist.
Key file [/home/lnevers/.ssh/arendia_id_rsa] does NOT exist.
Key file [/home/lnevers/.ssh/niky-geni_key] does NOT exist.
Key file [/home/lnevers/.ssh/scorpia-id_rsa] does NOT exist.
Key file [/home/lnevers/.ssh/niky-geni_key] does NOT exist.
{'username': 'lnevers1', 'hostname': '192.1.242.15', 'geni_status': 'ready', 'authentication': 'ssh-keys', 'client_id': 'VM-1', 'am_statu
{'username': 'lnevers2', 'hostname': '192.1.242.15', 'geni_status': 'ready', 'authentication': 'ssh-keys', 'client_id': 'VM-1', 'am_statu
{'username': 'lnevers', 'hostname': '192.1.242.15', 'geni_status': 'ready', 'authentication': 'ssh-keys', 'client_id': 'VM-1', 'am_status
{'username': 'inki', 'hostname': '192.1.242.15', 'geni_status': 'ready', 'authentication': 'ssh-keys', 'client_id': 'VM-1', 'am_status': 
{'username': 'lnevers1', 'hostname': '192.1.242.14', 'geni_status': 'ready', 'authentication': 'ssh-keys', 'client_id': 'VM-2', 'am_statu
{'username': 'lnevers2', 'hostname': '192.1.242.14', 'geni_status': 'ready', 'authentication': 'ssh-keys', 'client_id': 'VM-2', 'am_statu
{'username': 'lnevers', 'hostname': '192.1.242.14', 'geni_status': 'ready', 'authentication': 'ssh-keys', 'client_id': 'VM-2', 'am_status
{'username': 'inki', 'hostname': '192.1.242.14', 'geni_status': 'ready', 'authentication': 'ssh-keys', 'client_id': 'VM-2', 'am_status': 
{'username': 'lnevers1', 'hostname': '192.1.242.13', 'geni_status': 'ready', 'authentication': 'ssh-keys', 'client_id': 'VM-3', 'am_statu
{'username': 'lnevers2', 'hostname': '192.1.242.13', 'geni_status': 'ready', 'authentication': 'ssh-keys', 'client_id': 'VM-3', 'am_statu
{'username': 'lnevers', 'hostname': '192.1.242.13', 'geni_status': 'ready', 'authentication': 'ssh-keys', 'client_id': 'VM-3', 'am_status
{'username': 'inki', 'hostname': '192.1.242.13', 'geni_status': 'ready', 'authentication': 'ssh-keys', 'client_id': 'VM-3', 'am_status': 
{'username': 'lnevers1', 'hostname': '192.1.242.17', 'geni_status': 'ready', 'authentication': 'ssh-keys', 'client_id': 'VM-4', 'am_statu
{'username': 'lnevers2', 'hostname': '192.1.242.17', 'geni_status': 'ready', 'authentication': 'ssh-keys', 'client_id': 'VM-4', 'am_statu
{'username': 'lnevers', 'hostname': '192.1.242.17', 'geni_status': 'ready', 'authentication': 'ssh-keys', 'client_id': 'VM-4', 'am_status
{'username': 'inki', 'hostname': '192.1.242.17', 'geni_status': 'ready', 'authentication': 'ssh-keys', 'client_id': 'VM-4', 'am_status': 
Send command uptime to VM-4
Enter passphrase for key '/home/lnevers1/.ssh/id_rsa': 
```

Also Sarah and I looked into the user information returned by the aggregates and found
that they are returned in the following order for ExoGENI:
```
          <services>      
                  <login authentication="ssh-keys" hostname="192.1.242.13" port="22" username="lnevers1"/>      
                  <login authentication="ssh-keys" hostname="192.1.242.13" port="22" username="lnevers2"/>      
                  <login authentication="ssh-keys" hostname="192.1.242.13" port="22" username="lnevers"/>      
                  <login authentication="ssh-keys" hostname="192.1.242.13" port="22" username="inki"/>      
            </services>    
```
and in the following order for InstaGENI:
```
     "urn": "urn:publicid:IDN+ch.geni.net+user+lnevers", 
      "login": "lnevers"
          "key": "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAyMD500/PcBDJy8mecC66vS9eSzaqBtdEMteZ46rmNz+onyPUotxR1uUbExTpja3Hojkkti+9YuxRIUrIIvC
      "urn": "urn:publicid:IDN+pgeni.gpolab.bbn.com+user+lnevers2", 
      "login": "lnevers2"
          "key": "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAsVCr1B4DZOJvYKg9FEXb8fhLl07pSf5MeZsVGkXr5bDOwrqbqUgz2rldRZGBf9k3/XuqosujPXUyxWBgI4j
      "urn": "urn:publicid:IDN+pgeni.gpolab.bbn.com+user+lnevers1", 
      "login": "lnevers1"
```


_Trac comment by lnevers (github user: luisanevers) on 09-16-2013 at 17:01_

**Comment by seledwards** [comment]
Actually, the bits that look like this: `{'username': 'lnevers1', 'hostname': '192.1.242.15', 'geni_status': 'ready'..` are debugging output.

readyToLogin and remote-execute.py work as expected with the attached fix.

_Trac comment by sedwards (github user: seledwards) on 09-16-2013 at 17:31_

**Comment by seledwards** [comment]
Added #373 to indicate that `remote-execute.py` is confusing if there are multiple users and keys on the local machine. 

_Trac comment by sedwards (github user: seledwards) on 09-16-2013 at 17:35_

**Comment by seledwards** [comment]
Merged in readyToLogin.py to the 2.4 release branch.  And attached readyToLogin.2.py to this ticket.  Closing.

_Trac comment by sedwards (github user: seledwards) on 09-17-2013 at 09:58_
