### ISSUE TITLE
Several omni commands should support -o or --outputfile option

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-tools#371]
As my list of slices grows (287) and I am trying to sift through the output of the omni listmyslices commnad and I am finding that it would be helpful if the listmyslices command would support the --outputfile option, but it currently does not.
 
I also checked other omni commands for the clearinghouse/slice authority and found that these commands also do not support --outputfile:
 - get_ch_version 
 - listaggregates 
 - listmyslices 
 - listmykeys 
 - nicknames 

 _Imported from trac ticket [#371](http://trac.gpolab.bbn.com/gcf/ticket/371),  created by lnevers on 09-13-2013 at 11:29, last modified: 04-15-2014 at 11:45_

**Comment by ahelsing** [comment]
consider also the PG AM function listimages

_Trac comment by ahelsing on 04-14-2014 at 09:43_
