### ISSUE TITLE
create any directories needed in the path to agg_nick_cache

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#383]
omni.py not create any directories needed in the path to `agg_nick_cache`.

Currently see:
```
$ omni.py --AggNickCacheName ~/gcf2/agg_nick_cache  getversion -a ig-gpo
10:05:32 INFO     omni: Config file '/Users/sedwards/gcf2/agg_nick_cache' or '/Users/sedwards/gcf2/agg_nick_cache' does not exist
10:05:32 INFO     omni: Attempted to download latest `agg_nick_cache` from 'http://trac.gpolab.bbn.com/gcf/raw-attachment/wiki/Omni/agg_nick_cache' but could not.
```

 _Imported from trac ticket [#383](http://trac.gpolab.bbn.com/gcf/ticket/383),  created by sedwards on 09-25-2013 at 10:10, last modified: 02-13-2014 at 08:12_
   CCing: gpo-expt-support@...

**Comment by seledwards** [comment]
Added two things:
 * In `update_agg_nick_cache()`, create the directory if it doesn't already exist
 * If you created the `--AggNickCacheName` file, go ahead and use it.

Here's the output now:
```
$ rm -rf ~/gcf2
$ ls ~/gcf2
ls: /Users/sedwards/gcf2: No such file or directory
$ omni.py --AggNickCacheName ~/gcf2/agg_nick_cache  getversion -a ig-gpo
10:47:55 INFO     omni: Config file '/Users/sedwards/gcf2/agg_nick_cache' or '/Users/sedwards/gcf2/agg_nick_cache' does not exist
10:47:55 INFO     omni: Downloaded latest `agg_nick_cache` from 'http://trac.gpolab.bbn.com/gcf/raw-attachment/wiki/Omni/agg_nick_cache' and copied to '/Users/sedwards/gcf2/agg_nick_cache'.
10:47:55 INFO     omni: Loading agg_nick_cache file '/Users/sedwards/gcf2/agg_nick_cache'
```

_Trac comment by sedwards (github user: seledwards) on 09-25-2013 at 10:50_

**Comment by luisanevers** [comment]
Verified creation of agg_nick_cache in various success and failure scenario in version gcf-2.5-021214pm.

_Trac comment by lnevers (github user: luisanevers) on 02-13-2014 at 08:12_
