### ISSUE TITLE
If use --AggNickCacheName and can't read/write to the specified file, omni should fall back to `agg_nick_cach.base`

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#384]
If use `--AggNickCacheName` and can't read/write to the specified file, omni falls back to `~/.gcf/agg_nick_cache` but it should fall back to `agg_nick_cache.base`.

```
$ omni.py --AggNickCacheName ~/gcf2/agg_nick_cache  getversion -a ig-gpo
10:05:32 INFO     omni: Config file '/Users/sedwards/gcf2/agg_nick_cache' or '/Users/sedwards/gcf2/agg_nick_cache' does not exist
10:05:32 INFO     omni: Attempted to download latest `agg_nick_cache` from 'http://trac.gpolab.bbn.com/gcf/raw-attachment/wiki/Omni/agg_nick_cache' but could not.
10:05:32 INFO     omni: Loading agg_nick_cache file '/Users/sedwards/.gcf/agg_nick_cache'
```

In fixing this, added use of fallback if the file can't be read not just if it doesn't exist. 

 _Imported from trac ticket [#384](http://trac.gpolab.bbn.com/gcf/ticket/384),  created by sedwards on 09-25-2013 at 10:12, last modified: 02-13-2014 at 08:22_
   CCing: gpo-expt-support@...

**Comment by seledwards** [comment]
Added code so that you fall back to `agg_nick_cache.base` immediately if `--AggNickCacheName` fails.  Now it will fallback both if the file doesn't exist, but also if there is a problem reading the file.

Tested by trying to download `agg_nick_cache` from a url that doesn't exist and therefore generated a bad `agg_nick_cache` file.
File is downloaded, `omni` attempts to read it, fails, and falls back to the `agg_nick_cache.base` file distributed with omni.
```
$ rm -rf ~/gcf2; ls ~/gcf2
ls: /Users/sedwards/gcf2: No such file or directory
$ omni.py --AggNickCacheName ~/gcf2/agg_nick_cache  getversion -a ig-gpo --AggNickDefinitiveLocation=http://trac.gpolab.bbn.com/gcf/raw-attachment/wiki/Omni/agg_nick_cache2
11:52:55 INFO     omni: Downloaded latest `agg_nick_cache` from 'http://trac.gpolab.bbn.com/gcf/raw-attachment/wiki/Omni/agg_nick_cache2' and copied to '/Users/sedwards/gcf2/agg_nick_cache'.
11:52:55 INFO     omni: Loading agg_nick_cache file '/Users/sedwards/gcf2/agg_nick_cache'
11:52:55 ERROR    omni: agg_nick_cache file /Users/sedwards/gcf2/agg_nick_cache could not be parsed: File contains no section headers.
file: /Users/sedwards/gcf2/agg_nick_cache, line: 1
'<DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\n'
11:52:55 INFO     omni: Loading agg_nick_cache file '/Users/sedwards/projects/GENI/code/gcf/agg_nick_cache.base'
```

If I call `omni` again, it tries and fails to read the file from the existing cache and again falls back to the file distributed with `omni`.
```
$ omni.py --AggNickCacheName ~/gcf2/agg_nick_cache  getversion -a ig-gpo
11:56:58 INFO     omni: Loading agg_nick_cache file '/Users/sedwards/gcf2/agg_nick_cache'
11:56:58 ERROR    omni: agg_nick_cache file /Users/sedwards/gcf2/agg_nick_cache could not be parsed: File contains no section headers.
file: /Users/sedwards/gcf2/agg_nick_cache, line: 1
'<DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\n'
11:56:58 INFO     omni: Loading agg_nick_cache file '/Users/sedwards/projects/GENI/code/gcf/agg_nick_cache.base'
```

cache will time out in one day.  Instead use `--NoAggNickCache` to force the cache to be refreshed and this works.
```
$ omni.py --AggNickCacheName ~/gcf2/agg_nick_cache  getversion -a ig-gpo --NoAggNickCache
11:58:13 INFO     omni: Downloaded latest `agg_nick_cache` from 'http://trac.gpolab.bbn.com/gcf/raw-attachment/wiki/Omni/agg_nick_cache' and copied to '/Users/sedwards/gcf2/agg_nick_cache'.
11:58:13 INFO     omni: Loading agg_nick_cache file '/Users/sedwards/gcf2/agg_nick_cache'
```

_Trac comment by sedwards (github user: seledwards) on 09-26-2013 at 12:02_

**Comment by luisanevers** [comment]
Verified download of the agg_nick_cache in scenarios where the --AggNickCacheName cannot be accessed in version gcf-2.5-021214pm.

_Trac comment by lnevers (github user: luisanevers) on 02-13-2014 at 08:22_
