### ISSUE TITLE
Make readyToLogin.py work with multi-user slices at PG

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#389]
ProtoGENI/InstaGENI is adding multi-user login info to the manifest.  Make readyToLogin.py work with this new format:
 * get login info from the manifest
 * continue to get status from SliverStatus

 _Imported from trac ticket [#389](http://trac.gpolab.bbn.com/gcf/ticket/389),  created by sedwards on 10-07-2013 at 13:44, last modified: 10-10-2013 at 11:31_
   CCing: gpo-expt-support@...

**Comment by luisanevers** [comment]
_lnevers (luisanevers) attached [testlog-readyToLogin-orig.txt](http://trac.gpolab.bbn.com/gcf/attachment/ticket/389/testlog-readyToLogin-orig.txt) on 10-09-2013 at 16:28_

**Comment by seledwards** [comment]
_sedwards (seledwards) attached [readyToLogin.2.py](http://trac.gpolab.bbn.com/gcf/attachment/ticket/389/readyToLogin.2.py) on 10-10-2013 at 10:14_

**Comment by luisanevers** [comment]
_lnevers (luisanevers) attached [testlog-readyToLogin.txt](http://trac.gpolab.bbn.com/gcf/attachment/ticket/389/testlog-readyToLogin.txt) on 10-09-2013 at 16:26_

**Comment by seledwards** [comment]
_sedwards (seledwards) attached [readyToLogin.py](http://trac.gpolab.bbn.com/gcf/attachment/ticket/389/readyToLogin.py) on 10-09-2013 at 10:47_

**Comment by seledwards** [comment]
Did the following:
 * Have PG/IG pull login info from the manifest (like the orca case)
 * added `addNodeStatus()` code for the PG/IG case

_Trac comment by sedwards (github user: seledwards) on 10-07-2013 at 16:11_

**Comment by seledwards** [comment]
After some discussion we decided that this code should fallback to using login info from SliverStatus if the manifest doesn't contain all of the users.

Added a method and a note to the code:
```
    # 10/9/13 PG code is switching to include login info in manifest
    # a future release should remove the following line so that we don't fall back to SliverStatus
    amLoginInfo = addNodeStatusCheckForPGFallback( amLoginInfo, amSliverStat )
```



_Trac comment by sedwards (github user: seledwards) on 10-09-2013 at 10:26_

**Comment by seledwards** [comment]
Added a flag `--noFallbackToStatusForPG` to control whether to use the fallback or not.

For testing use a project with many Admins (like the GEC18 project) and reserve resources via the portal so that the keys will be loaded on the nodes.

Test the following items against an AM which hasn't implemented the fix (like `ig-gpo`)
```
# should list one user in both ssh_config and login sections
readyToLogin.py myslice -r GEC18  -a ig-gpo --noFallbackToStatusForPG 
# should list one user in both ssh_config and login sections
readyToLogin.py myslice -r GEC18  -a ig-gpo --noFallbackToStatusForPG --no-keys
# should list many users in ssh_config and one user in login section
readyToLogin.py myslice -r GEC18  -a ig-gpo 
# should list many users in both ssh_config and login sections
readyToLogin.py myslice -r GEC18  -a ig-gpo --no-keys
```

More test cases coming in the next comments....

_Trac comment by sedwards (github user: seledwards) on 10-09-2013 at 10:42_

**Comment by seledwards** [comment]
Test the following items against an AM which HAS implemented the fix (like pg-utah)
```
# should list many users in ssh_config and one user in login section
readyToLogin.py myslice -r GEC18  -a pg-gpo --noFallbackToStatusForPG 
# should list many users in both ssh_config and login sections
readyToLogin.py myslice -r GEC18  -a pg-gpo --noFallbackToStatusForPG --no-keys
# should list many users in ssh_config and one user in login section
readyToLogin.py myslice -r GEC18  -a pg-gpo 
# should list many users in both ssh_config and login sections
readyToLogin.py myslice -r GEC18  -a pg-gpo --no-keys
```

_Trac comment by sedwards (github user: seledwards) on 10-09-2013 at 10:45_

**Comment by luisanevers** [comment]
Picking up attached readyToLogin.py for initial evaluation.

_Trac comment by lnevers (github user: luisanevers) on 10-09-2013 at 10:53_

**Comment by seledwards** [comment]
Also test with multiple VMs at each aggregate.

_Trac comment by sedwards (github user: seledwards) on 10-09-2013 at 11:01_

**Comment by luisanevers** [comment]
Created multi-user and multi-keys slivers for the following scenarios:
 a. 4 XEN InstaGENI VM
 b. 1 XEN, 1 PC, 1 OpenVZ on InstaGENI
 c. 1 XEN, 1 PC, 1 OpenVZ on ProtoGENI
 d. 1 XEN, 1 PG on ExoGENI

Ran the following command on each of the above slivers:
 1. readyToLogin.py -a aggregate slice  --noFallbackToStatusForPG --no-keys
 2. readyToLogin.py -a aggregate slice  --noFallbackToStatusForPG 
 3. readyToLogin.py -a aggregate slice 
 4. Also compared to output from original readyToLogin.py

Have found that InstaGENI show incorrect output for command in '3' above for both experiment 'a' and 'b'.  Attaching a log that show the output from '3' and '4' for experiment 'a'.  

Please let me know if you need to see this.


_Trac comment by lnevers (github user: luisanevers) on 10-09-2013 at 16:24_

**Comment by luisanevers** [comment]
Two files have been attached:

 - testlog-readyToLogin.txt: output for 4 XEN InstaGENI VM  with new version of readyToLogin.py 
 - testlog-readyToLogin-orig.txt: output for 4 XEN InstaGENI VM  with original version  of readyToLogin.py 

_Trac comment by lnevers (github user: luisanevers) on 10-09-2013 at 16:31_

**Comment by seledwards** [comment]
Attached a new version.  Try this.

_Trac comment by sedwards (github user: seledwards) on 10-10-2013 at 10:14_

**Comment by luisanevers** [comment]
Re-ran all multi-user and multi-keys slivers for all readyToLogin.py option combinations and the output looks good.  Also verified remote-execute.py with each of the 4 slivers listed in earlier notes, no problems were found other than known issue with remote-execute.py to ExoGENI failing because first user in list is used.

A GCF release candidate version can be made for this change. 

_Trac comment by lnevers (github user: luisanevers) on 10-10-2013 at 10:47_
