### ISSUE TITLE
sttiching: make scs support monitoring style invocations

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#394]
Support using scs.py to monitor if the SCS is up.

See http://groups.geni.net/syseng/ticket/5351#comment:11

 _Imported from trac ticket [#394](http://trac.gpolab.bbn.com/gcf/ticket/394),  created by ahelsing on 10-09-2013 at 16:07, last modified: 02-13-2014 at 09:09_
   CCing: chaos@...

**Comment by luisanevers** [comment]
Verified the monitoring described in gcf-2.5-021214pm:
```
$ python ./src/gcf/omnilib/stitch/scs.py --monitoring
SUCCESS: SCS at  http://oingo.dragon.maxgigapop.net:8081/geni/xmlrpc  is running version:   Revision: 559   -  Date: 2013-06-18 12:11:06 -0700 (Tue, 18 Jun 2013)  
```
There is only one mismatch found the location of the script is different that described in  http://groups.geni.net/syseng/ticket/5351

_Trac comment by lnevers (github user: luisanevers) on 02-13-2014 at 08:37_

**Comment by ahelsing** [comment]
Right - the repackaging means the file location changed.

_Trac comment by ahelsing on 02-13-2014 at 09:09_
