### ISSUE TITLE
Expired certificates are not flagged as invalid

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#4]
The certificate validity checks need to include checks for expiration. There are notes in the code that it needs to be done. PlanetLab has recently patched this and the patch needs to be integrated into gcf.

 _Imported from trac ticket [#4](http://trac.gpolab.bbn.com/gcf/ticket/4),  created by tmitchel on 09-20-2010 at 16:44, last modified: 09-22-2010 at 14:43_

**Comment by ahelsing** [comment]
SFA has been moved to a git repo.  I'll check that out and update the files.

_Trac comment by jkarlin on 09-22-2010 at 14:10_

**Comment by ahelsing** [comment]
PlanetLab's git repo: http://git.planet-lab.org/

I have an account on the machine, and run:
git clone ssh://git.planet-lab.org/git/sfa.git

For development, I will create a branch (say 'geni') and push my branch to origin when I want the folks at Princeton to see what I've been working on.




_Trac comment by jkarlin on 09-22-2010 at 14:19_

**Comment by ahelsing** [comment]
I've pushed the new SFA files to origin and updated the README.txt in the SFA directory to reflect the new repository.

_Trac comment by jkarlin on 09-22-2010 at 14:43_
