### ISSUE TITLE
undefined variable in amhandler.py

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#408]
A user reported the following exception when running status on a slice with 4 slivers, each one with a different expiration time:
```
File "/gcf-2.4.1/src/omnilib/amhandler.py", line 3058, in status
    firstCount = len(sliverExps[time])
NameError: global name 'time' is not defined
```

User's comment:
  After taking a look at the code I realized that time isn't in fact defined. It seems that when summarizing the sliver expiration dates it first checks if the length of orderedDates is 1 or 0 and if not checks the len(sliverExps[time]) that fails.

The user confirms the following suggestions lets them work around the issue:
  You may be able to work around [issue](this) by commenting out the offending line and then removing “firstCount” from the log message on the next line (both in the format string and in the arguments).

 _Imported from trac ticket [#408](http://trac.gpolab.bbn.com/gcf/ticket/408),  created by tmitchel on 10-21-2013 at 11:21, last modified: 10-24-2013 at 14:59_

**Comment by ahelsing** [comment]
Ack. The variable name (from the line above) is firstTime, not time.


_Trac comment by ahelsing on 10-24-2013 at 14:58_
