### ISSUE TITLE
Support geni_extend_alap in GCF AMv3

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#414]
GCF should support the new `geni_extend_alap` option to `Renew` and `RenewSliver`.

 _Imported from trac ticket [#414](http://trac.gpolab.bbn.com/gcf/ticket/414),  created by ahelsing on 10-30-2013 at 15:03, last modified: 05-19-2014 at 08:13_

**Comment by ahelsing** [comment]
Added support in AM API v2

_Trac comment by ahelsing on 10-31-2013 at 11:58_

**Comment by MarshallBrinn** [comment]
Added support to GCF am3.py.

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-19-2014 at 08:13_
