### ISSUE TITLE
Use nicknames in addition to (or instead of) AM urls in output

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#424]
An experimenter suggested that it would be more helpful to identify the aggregate by nickname in omni's output than by URL.

Consider adding the nickname and/or replacing the URL with the nickname. 

Experimenter is cc'd on the ticket.

 _Imported from trac ticket [#424](http://trac.gpolab.bbn.com/gcf/ticket/424),  created by sedwards on 11-05-2013 at 15:27, last modified: 02-13-2014 at 09:14_
   CCing: szb53@..., gpo-expt-support@...

**Comment by luisanevers** [comment]
Compared gcf-2.4.1 and gcf-2.5-021214pm omni output for several commands and could not find instances where a URL was replaced by nicknames. Where should this change show up?


_Trac comment by lnevers (github user: luisanevers) on 02-13-2014 at 09:09_

**Comment by ahelsing** [comment]
As in this:
```
09:12:47 INFO     omni:  Completed getversion:
Args: getversion

  Result Summary: 
Got version for utah-pg (https://www.emulab.net:12369/protogeni/xmlrpc/am/2.0)
 
09:12:47 INFO     omni:  ======================================================
```

Note you only see this if Omni can figure out the nickname - using the agg nick cache.

_Trac comment by ahelsing on 02-13-2014 at 09:14_
