### ISSUE TITLE
missing copyright in ./windows_install/setup.py

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#426]
According to repocheck, the gcf source file:
```
./windows_install/setup.py
```
is missing a copyright notice.

 _Imported from trac ticket [#426](http://trac.gpolab.bbn.com/gcf/ticket/426),  created by chaos on 11-06-2013 at 12:23, last modified: 02-13-2014 at 09:18_

**Comment by seledwards** [comment]
Sorry about that.  I made the change and pushed it to develop.

Let me know if that doesn't do the trick.

_Trac comment by sedwards (github user: seledwards) on 11-06-2013 at 13:22_

**Comment by ahelsing** [comment]
Closing optimistically.  If repocheck complains again, i'll reopen.  Thanks!

_Trac comment by chaos on 11-06-2013 at 13:26_

**Comment by luisanevers** [comment]
Verified in gcf-2.5-021214pm and in Feb 7th early version of windows gcf.

_Trac comment by lnevers (github user: luisanevers) on 02-13-2014 at 09:18_
