### ISSUE TITLE
renew_slice should return actual new expiration, not requested

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#428]
renew_slice in the frameworks currently generally returns the date you requested when the command says it succeeded, without checking to see if that is what you got.

Query the SA and return the actual current slice expiration.

 _Imported from trac ticket [#428](http://trac.gpolab.bbn.com/gcf/ticket/428),  created by ahelsing on 11-08-2013 at 09:03, last modified: 02-13-2014 at 13:09_
   CCing: lnevers@...

**Comment by luisanevers** [comment]
Unable to verify that the date returned is actually the result of a successful renewslice. Compared renewslice in debug mode between gcf-2.4.1 and gcf-2.5-021214pm and both return the same messages.

Messages in renewslice in gcf-2.5-021214pm:
```
09:22:22 INFO     omni.pgch: Requesting new slice expiration '2014-02-21T00:00:00'
09:22:22 INFO     omni: Slice lnx now expires at 2014-02-21 00:00:00 UTC
```
Messages in reneslice in gcf-2.4.1:
```
09:21:03 INFO     omni.pgch: Requesting new slice expiration '2014-02-20T00:00:00'
09:21:03 INFO     omni: Slice lnx now expires at 2014-02-20 00:00:00 UTC
```

_Trac comment by lnevers (github user: luisanevers) on 02-13-2014 at 09:26_

**Comment by ahelsing** [comment]
You'll only see a difference if the time you get is different from the time you asked for.

For example:
```
...
09:31:21 INFO     omni.pgch: Requesting new slice expiration '3014-01-01T00:00:00'
09:31:22 INFO     omni: Slice newslice now expires at 2014-08-17 14:31:20 UTC
09:31:22 INFO     omni: Slice urn:publicid:IDN+ch.geni.net:ahscaletest+slice+newslice expires on 2014-08-17 14:31:20 UTC
09:31:22 INFO     omni:  ------------------------------------------------------
09:31:22 INFO     omni:  Completed renewslice:
Args: renewslice newslice 30140101

  Result Summary: Slice newslice now expires at 2014-08-17 14:31:20 UTC
Slice urn:publicid:IDN+ch.geni.net:ahscaletest+slice+newslice expires on 2014-08-17 14:31:20 UTC 
```


_Trac comment by ahelsing on 02-13-2014 at 09:31_

**Comment by luisanevers** [comment]
Verified that specifying a renewslice time of 188 days from today returns an expiration which is 180 from now. 

_Trac comment by lnevers (github user: luisanevers) on 02-13-2014 at 13:09_
