### ISSUE TITLE
add to omni, a command to list members of a slice

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#431]
After adding members to slices ([gcf 422](http://trac.gpolab.bbn.com/gcf/ticket/422)), it will be really nice to be able to list the members of the slices as well.

Same functionality would be nice for project as well.  

 _Imported from trac ticket [#431](http://trac.gpolab.bbn.com/gcf/ticket/431),  created by sedwards on 11-15-2013 at 11:14, last modified: 02-04-2014 at 23:22_
   CCing: gpo-expt-support@..., johren@..., manu@...

**Comment by ahelsing** [comment]
added function listslicemembers which lists members: their URN, email, and registered public SSH keys

Putting the request to list project members on a new ticket #495

_Trac comment by ahelsing on 02-04-2014 at 23:22_
