### ISSUE TITLE
Add support for GRAM to readyToLogin

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#444]
readyToLogin needs to make a small change to accept a new AM type: 

in `gcf 2.4.1` of `readytologin.py` line 815 currently reads:
```
if amType == "orca" or (amType == "protogeni”):
```

it should read:
```
if amType == "orca" or (amType == "protogeni") or (amType == "GRAM"):
```

Also, check to see if there is a more appropriate `else` statement to allow new aggregates that work as desired.

 _Imported from trac ticket [#444](http://trac.gpolab.bbn.com/gcf/ticket/444),  created by sedwards on 12-04-2013 at 10:50, last modified: 02-18-2014 at 16:44_
   CCing: dabideen@..., gpo-expt-support@...

**Comment by seledwards** [comment]
Marshall suggests:  "It might be nice to have a config file or something that defined all the 'known' or 'accepted' AM types rather than hard-coding it in the python, but its a small thing."

_Trac comment by sedwards (github user: seledwards) on 12-04-2013 at 11:20_

**Comment by seledwards** [comment]
Checked in the fixes Luisa has been using that seem to work with AM API v2.

v3 support is covered by #451.

Luisa should report if there are any other issues with readyToLogin against the v2 version of GRAM.



_Trac comment by sedwards (github user: seledwards) on 02-17-2014 at 17:00_

**Comment by luisanevers** [comment]
There are still issues with readyToLogin.py, it does not show the AM status for the nodes, which is the reason why remore-execute.py does not work. 

_Trac comment by lnevers (github user: luisanevers) on 02-18-2014 at 08:18_

**Comment by seledwards** [comment]
Ok.  Checked in new code for `readyToLogin` which is on `develop` which should work.

Note that it only shows one status message instead of two like on some other aggregates.

So the status looks like this:
```
my-node's geni_status is: ready
```

_Trac comment by sedwards (github user: seledwards) on 02-18-2014 at 12:39_

**Comment by luisanevers** [comment]
Using gcf-2.5-021814 verified readyToLogin with GRAM:
```
$ readyToLogin.py -a gram lngram
#========================================
#SSH CONFIGURATION INFO for User lnevers
#========================================
 
Host VM-2
  Port 3000
  HostName 128.89.72.121
  User lnevers 
  IdentityFile /home/lnevers/.ssh/geni_cert_portal_key 
  IdentityFile /home/lnevers2/.ssh/id_rsa 
  IdentityFile /home/lnevers1/.ssh/id_rsa 
  IdentityFile /home/hpd/.ssh/geni_key_portal 
 
Host VM-1
  Port 3001
  HostName 128.89.72.121
  User lnevers 
  IdentityFile /home/lnevers/.ssh/geni_cert_portal_key 
  IdentityFile /home/lnevers2/.ssh/id_rsa 
  IdentityFile /home/lnevers1/.ssh/id_rsa 
  IdentityFile /home/hpd/.ssh/geni_key_portal 

================================================================================
LOGIN INFO for AM: https://128.89.72.112:5002
================================================================================

For more login info, see the section entitled:
	 'Providing a private key to ssh' in 'readyToLogin.py -h'

VM-1's geni_status is: ready 
User lnevers logs in to VM-1 using:
	ssh -p 3001  -i /home/lnevers/.ssh/geni_cert_portal_key lnevers@128.89.72.121
	ssh -p 3001  -i /home/lnevers2/.ssh/id_rsa lnevers@128.89.72.121
	ssh -p 3001  -i /home/lnevers1/.ssh/id_rsa lnevers@128.89.72.121
	ssh -p 3001  -i /home/hpd/.ssh/geni_key_portal lnevers@128.89.72.121

VM-2's geni_status is: ready 
User lnevers logs in to VM-2 using:
	ssh -p 3000  -i /home/lnevers/.ssh/geni_cert_portal_key lnevers@128.89.72.121
	ssh -p 3000  -i /home/lnevers2/.ssh/id_rsa lnevers@128.89.72.121
	ssh -p 3000  -i /home/lnevers1/.ssh/id_rsa lnevers@128.89.72.121
	ssh -p 3000  -i /home/hpd/.ssh/geni_key_portal lnevers@128.89.72.121

NOTE: If your user is not listed, try using the --no-keys option.
```
Tried to verify remote-execute.py but it does not seem to work:
```
$ remote-execute.py -a gram lngram -m "uptime;hostname;date"
1. Find login Info for hosts in slice lngram
2. Send command 'uptime' to VM-1

 21:35:47 up 3 min,  0 users,  load average: 0.00, 0.00, 0.00
... Done with command 'uptime' at VM-1
2. Send command 'uptime' to VM-2

 21:35:55 up 2 min,  0 users,  load average: 0.00, 0.00, 0.00
... Done with command 'uptime' at VM-2
```
Also verify on InstaGENI.

_Trac comment by lnevers (github user: luisanevers) on 02-18-2014 at 16:43_

**Comment by luisanevers** [comment]
Replying to [lnevers](comment:7):

> Tried to verify remote-execute.py but it does not seem to work:

Please ignore the above sentence, the remote-login.py script was verified and there are no issue.


_Trac comment by lnevers (github user: luisanevers) on 02-18-2014 at 16:44_
