### ISSUE TITLE
renew slice fails when given a timezone

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#447]
If you call renew slice and supply a timezone, you get an error
```
23:35:04 ERROR    omni.pgch: Call for Renew Slice urn:publicid:IDN+ch-ah.gpolab.bbn.com:ahscaletest+slice+asdf failed.: TypeError: can't subtract offset-naive and offset-aware datetimes
```

 _Imported from trac ticket [#447](http://trac.gpolab.bbn.com/gcf/ticket/447),  created by ahelsing on 12-05-2013 at 23:45, last modified: 02-13-2014 at 10:18_

**Comment by luisanevers** [comment]
Renewed a slice to ""2014-02-22 00:00:00 PST" (Pacific Standard Time) but results show 
"2014-02-22 00:00:00 UTC" and do not reflect that PST=UTC-08, should it?

```
$ omni.py renewslice lnx "2014-02-22 00:00:00 PST"
09:46:16 INFO     omni: Loading agg_nick_cache file '/home/lnevers/.gcf/agg_nick_cache'
09:46:16 INFO     omni: Loading config file /home/lnevers/.gcf/omni_config
09:46:16 INFO     omni: Using control framework portal
09:46:16 INFO     omni.pgch: Requesting new slice expiration '2014-02-22T00:00:00'
09:46:17 INFO     omni: Slice lnx now expires at 2014-02-22 00:00:00 UTC
09:46:17 INFO     omni: Slice urn:publicid:IDN+ch.geni.net:ln-prj+slice+lnx expires on 2014-02-22 00:00:00 UTC
09:46:17 INFO     omni:  ------------------------------------------------------
09:46:17 INFO     omni:  Completed renewslice:
Args: renewslice lnx 2014-02-22 00:00:00 PST

  Result Summary: Slice lnx now expires at 2014-02-22 00:00:00 UTC
Slice urn:publicid:IDN+ch.geni.net:ln-prj+slice+lnx expires on 2014-02-22 00:00:00 UTC 
09:46:17 INFO     omni:  ======================================================
```


_Trac comment by lnevers (github user: luisanevers) on 02-13-2014 at 09:52_

**Comment by ahelsing** [comment]
Per the logs, Omni read your request as '2014-02-22T00:00:00', and that is the time it then gave you.

That is, it ignored 'PST' from your request string.

I've opened a separate ticket to track that issue.

http://trac.gpolab.bbn.com/gcf/ticket/503

Meanwhile, try doing something like "2014-02-22 00:00:00-08:00"

_Trac comment by ahelsing on 02-13-2014 at 10:18_
