### ISSUE TITLE
omni does not allow multiple slice credentials

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#46]
createsliver, for instance, assumes that the framework returns a single credential. It should be possible for frameworks to return an array of slice credentials instead. Omni could also support loading multiple slice credential files and packing them in an array so that a user could use a set of stored credentials.

 _Imported from trac ticket [#46](http://trac.gpolab.bbn.com/gcf/ticket/46),  created by tmitchel on 06-23-2011 at 17:07, last modified: 08-07-2013 at 13:48_

**Comment by tcmitchell** [comment]
The ABAC integration will probably need this feature.

_Trac comment by tmitchel (github user: tcmitchell) on 06-23-2011 at 17:08_

**Comment by tcmitchell** [comment]
This is not necessary for the 1.4 release. It should be included in a future release.

_Trac comment by tmitchel (github user: tcmitchell) on 09-02-2011 at 15:45_

**Comment by ahelsing** [comment]
perhaps we should add a `--cred` option (append action) for a list of files that have credentials.

Then supply all those credentials in any command that takes a credential.

And check the type of those credentials, wrapping in json as needed.


_Trac comment by ahelsing on 07-30-2013 at 17:01_

**Comment by ahelsing** [comment]
Added --cred option to pass other credentials. These are in addition to the normal user cred and slice cred.

These are passed in AM API methods, which take a list of credentials.

No support is added yet for getting a list of slice credentials from a framework when you ask for credentials. That will wait on a new CH API.

At the same time, gcf's cred_util was modified to log but skip over unparseable credentials.


_Trac comment by ahelsing on 08-07-2013 at 13:48_
