### ISSUE TITLE
stitcher: consider moving amlist file to ~/.gcf

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#462]
Vic argues that the stitcher amlist.txt file should go in ~/.gcf:
```
My guess is ~/.gcf might be better because: (1) One can issue the delete/sliverstatus/... from any directory, and (2) Experimenters aren't confused by a new file showing up in their cwd and they end up deleting it.
```

 _Imported from trac ticket [#462](http://trac.gpolab.bbn.com/gcf/ticket/462),  created by ahelsing on 12-28-2013 at 10:20, last modified: 05-23-2014 at 10:34_

**Comment by ahelsing** [comment]
Is this a config file that the user edits, or a cache file that GCF manages automatically? If the latter, it seems to me like it'd be better to put files like that into something like ~/.gcf/.cache, so they stay out of the way of people's personal configuration files.

_Trac comment by jbs on 12-30-2013 at 10:40_

**Comment by seledwards** [comment]
We should make sure the location of the amlist file is configurable on the command line for folks who will run stitcher as part of a another tool.

_Trac comment by sedwards (github user: seledwards) on 01-06-2014 at 10:44_

**Comment by ahelsing** [comment]
moved

_Trac comment by ahelsing on 05-23-2014 at 10:34_
