### ISSUE TITLE
allow specifying capacity for links stitcher adds

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#464]
When using the `fixedEndpoint` option, stitcher adds a link. This link needs a capacity in certain scenarios. Add an option to allow specifying this capacity.

 _Imported from trac ticket [#464](http://trac.gpolab.bbn.com/gcf/ticket/464),  created by ahelsing on 01-06-2014 at 12:58, last modified: 02-14-2014 at 09:19_

**Comment by ahelsing** [comment]
The issue we are working around is here: http://groups.geni.net/geni/ticket/1039

_Trac comment by ahelsing on 01-15-2014 at 09:01_

**Comment by ahelsing** [comment]
And here: http://groups.geni.net/geni/ticket/1101. Luisa notes: "stitching raw-pc at PG or IG site requires capacity in the RSpec for raw-pcs only. There is a default for OpenVZ and Xen VMs.   Stitcher can add a default capacity when raw-pc links do not have one defined."

For the earlier issue, Luisa's comment: "Whenever InstaGENI Utah is an end-point and Emulab is part of the path. Stitcher can add a default capacity if one is not specified. "

_Trac comment by ahelsing on 01-15-2014 at 09:02_

**Comment by ahelsing** [comment]
Add an option to stitcher to specify the default capacity you want on links, if one is not already specified. The default value for this default will be 20Gbps. Call this `--defaultCapacity`

At minimum, stitcher will add this on all links that have as one endpoint pg-utah, utah-ddc, ig-utah, PLUS any links where 1 interface is on an IG bare metal node.

Probably at first blush it will simply add this to _all_ stitched links, where there is no capacity already specified. 

Note that this will include checking that any existing property elements on the link specify a capacity.



_Trac comment by ahelsing on 02-12-2014 at 11:05_

**Comment by ahelsing** [comment]
So sticher will now ensure every stitchable link has 2 property elements each with a capacity. If no capacity is specified on the link, it uses the defaultCapacity.
Stitcher also now does some error checking of the property tags to see that they make a little sense.


_Trac comment by ahelsing on 02-12-2014 at 15:41_

**Comment by luisanevers** [comment]
Tried to use the new --defaultCapacity with a --fixedEndpoint topology that uses a raw-pc, which requires that capacity be set. It did not work, there was no capacity set:
```
$ stitcher.py createsliver atla-2-gpo-x1 stitch-ig-gpo-al2s-x1-losa.rspec --fixedEndpoint --defaultCapacity=20000 -o
10:22:43 INFO     stitcher: Loading agg_nick_cache file '/home/lnevers/.gcf/agg_nick_cache'
10:22:43 INFO     stitcher: Loading config file /home/lnevers/.gcf/omni_config
10:22:43 INFO     stitcher: Using control framework portal
10:22:44 INFO     stitcher: Checking that slice atla-2-gpo-x1 is valid...
10:22:44 INFO     stitcher: Slice urn:publicid:IDN+ch.geni.net:ln-prj+slice+atla-2-gpo-x1 expires on 2014-02-20 15:11:44 UTC
10:22:45 INFO     stitcher: Stitched reservation will include resources from these aggregates:
10:22:45 INFO     stitcher: 	<Aggregate ig-gpo>
10:22:45 INFO     stitcher: 	<Aggregate i2>
10:22:45 INFO     stitcher: Adding fake Node endpoint
10:22:45 INFO     stitcher: Adding fake iref endpoint on link <DOM Element: link at 0xa0c72ec>
10:22:45 INFO     stitch.Aggregate: Writing to '/tmp/atla-2-gpo-x1-createsliver-request-11-instageni-gpolab-bbn-com.xml'
10:22:45 INFO     stitch.Aggregate: 
	Stitcher doing createsliver at https://boss.instageni.gpolab.bbn.com:12369/protogeni/xmlrpc/am/2.0
10:22:59 ERROR    omni:  {'output': 'Could not verify topo', 'code': {'protogeni_error_log': 'urn:publicid:IDN+instageni.gpolab.bbn.com+log+c4eff463b72c503809a975950ee82af9', 'am_type': 'protogeni', 'geni_code': 2, 'am_code': 2, 'protogeni_error_url': 'https://boss.instageni.gpolab.bbn.com/spewlogfile.php3?logfile=c4eff463b72c503809a975950ee82af9'}, 'value': 0}
10:22:59 ERROR    stitcher: Stitching failed with an error: Reservation request impossible at <Aggregate ig-gpo>: AMAPIError: Error from Aggregate: code 2. protogeni AM code: 2: Could not verify topo....
Reservation request impossible at <Aggregate ig-gpo>: AMAPIError: Error from Aggregate: code 2. protogeni AM code: 2: Could not verify topo....
```

Attaching the stitching request RSpec atla-2-gpo-x1-createsliver-request-11-instageni-gpolab-bbn-com.xml.

_Trac comment by lnevers (github user: luisanevers) on 02-13-2014 at 10:26_

**Comment by luisanevers** [comment]
Verified that for non-fixedEndpoint topologies, the capacity is added properly vy stitcher.

The problem with --fixedEndpoint remains, no capacity is added


_Trac comment by lnevers (github user: luisanevers) on 02-13-2014 at 10:41_

**Comment by ahelsing** [comment]
ok, added that now

_Trac comment by ahelsing on 02-13-2014 at 21:11_

**Comment by luisanevers** [comment]
Verified ability to use "--fixedEndpoint" and "--defaultCapacity" for a fixed endpoint topology. 

Tested as follows:
```
$ stitcher.py createsliver atla-2-gpo-x1 stitch-ig-gpo-al2s-x1-losa.rspec --fixedEndpoint --defaultCapacity=20000 -o
09:11:34 INFO     stitcher: Loading agg_nick_cache file '/home/lnevers/.gcf/agg_nick_cache'
09:11:34 INFO     stitcher: Loading config file /home/lnevers/.gcf/omni_config
09:11:34 INFO     stitcher: Using control framework portal
09:11:35 INFO     stitcher: Checking that slice atla-2-gpo-x1 is valid...
09:11:35 INFO     stitcher: Slice urn:publicid:IDN+ch.geni.net:ln-prj+slice+atla-2-gpo-x1 expires on 2014-02-20 15:11:44 UTC
09:11:36 INFO     stitcher: Stitched reservation will include resources from these aggregates:
09:11:36 INFO     stitcher: 	<Aggregate ig-gpo>
09:11:36 INFO     stitcher: 	<Aggregate ion>
09:11:36 INFO     stitcher: Adding fake Node endpoint
09:11:36 INFO     stitcher: Adding fake interface_ref endpoint on link link-losa-ig-gpo
09:11:36 INFO     stitch.Aggregate: Writing to '/tmp/atla-2-gpo-x1-createsliver-request-11-instageni-gpolab-bbn-com.xml'
09:11:36 INFO     stitch.Aggregate: 
	Stitcher doing createsliver at https://boss.instageni.gpolab.bbn.com:12369/protogeni/xmlrpc/am/2.0
09:11:57 INFO     stitch.Aggregate: Allocation at <Aggregate ig-gpo> complete.
09:11:57 INFO     stitch.Aggregate: Writing to '/tmp/atla-2-gpo-x1-createsliver-request-11-ion-internet2-edu.xml'
09:11:57 INFO     stitch.Aggregate: 
	Stitcher doing createsliver at http://geni-am.net.internet2.edu:12346
09:12:41 INFO     stitch.Aggregate: DCN AM <Aggregate ion>: must wait for status ready....
09:12:41 INFO     stitch.Aggregate: Pause 30 seconds to let circuit become ready...
09:13:18 INFO     stitch.Aggregate: Pause 30 seconds to let circuit become ready...
09:13:55 INFO     stitch.Aggregate: DCN circuit 68031 is ready
09:14:02 INFO     stitch.Aggregate: Allocation at <Aggregate ion> complete.
09:14:02 INFO     stitch.launcher: All aggregates are complete.
09:14:02 INFO     stitcher: Saved combined reservation RSpec at 2 AMs to file atla-2-gpo-x1-manifest-rspec-stitching-combined.xml
Stitching success: Reserved resources in slice atla-2-gpo-x1 at 2 Aggregates (including 0 intermediate aggregate(s) not in the original request), creating 1 link(s).

```
The file /tmp/atla-2-gpo-x1-createsliver-request-11-instageni-gpolab-bbn-com.xml 
included the following link request with the specified capacity:
```
  <link client_id="link-losa-ig-gpo">
     <component_manager name="urn:publicid:IDN+instageni.gpolab.bbn.com+authority+cm"/>
        <interface_ref client_id="ig-gpo:if0"/>
     <component_manager name="urn:publicid:IDN+ion.internet2.edu+authority+am"/>
        <interface_ref client_id="fake:if0"/>
     <component_manager name="urn:publicid:IDN+fake+authority+am"/>
       <property capacity="20000" dest_id="fake:if0" source_id="ig-gpo:if0"/>
       <property capacity="20000" dest_id="ig-gpo:if0" source_id="fake:if0"/>
  </link>
```



_Trac comment by lnevers (github user: luisanevers) on 02-14-2014 at 09:19_
