### ISSUE TITLE
Sliver expiration needs to be more prominent in omni commads and portal

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-tools#465]
The current sliverstatus command prints the slice expiration in the summary results, while the sliver expiration is printed in the details (hundreds of lines).  This makes it easier to miss the actual sliver expiration and is a problem especially for PG and IG which defines the sliver expiration to be within a several hours of the creation time and is by default different than the slice expiration.

This is also a problem in the portal, where experimenter is shown the slice expiration and does not see the sliver expiration unless he/she chooses to view "Raw SliverStatus" which which gives hundred of lines for all known aggregates, and expiration is even easier to miss than in omni results.

Enhancement request:

 1. Modify omni slivestatus to notice if sliver expiration is different than slice expiration, and if different point this out in the summary results.  For portal, should also consider highlighting which aggregates have expiration dates that differ from slice.

 2. Add a new omni command equivalent to "print_slice_expiration" (maybe name it "print_sliver_expiration").

 _Imported from trac ticket [#465](http://trac.gpolab.bbn.com/gcf/ticket/465),  created by lnevers on 01-10-2014 at 11:30, last modified: 05-20-2014 at 12:00_

**Comment by ahelsing** [comment]
See #571, #572

_Trac comment by ahelsing on 04-02-2014 at 11:31_

**Comment by ahelsing** [comment]
Adding function print_sliver_expirations to print the expiration of slivers as reported by sliverstatus or status depending on the AM API version.

_Trac comment by ahelsing on 05-20-2014 at 12:00_
