### ISSUE TITLE
Timezone handling is inconsistent and documentation unclear

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#47]
AM API specifies you should supply a timezone in renewsliver.

AM API credential format says you don't have to specify a timezone.

If you aren't careful, you end up comparing times with a timezone to those without - sometimes in a local time and sometimes in UTC.

Original symptom:

When trying to renewslice at ProtoGENI:
```
$ src/omni.py -c ~/.gcf/omni-utah -a https://boss.emulab.net/protogeni/xmlrpc/am renewslice tmgec11 20110801T17:00
INFO:omni:Loading config file /home/tmitchel/.gcf/omni-utah
INFO:omni:Using control framework pg
Enter PEM pass phrase:
INFO:omni.protogeni:Requesting new slice expiration '2011-08-01T17:00:00'
INFO:omni:Slice tmgec11 now expires at 2011-08-01 17:00:00 UTC
Traceback (most recent call last):
 File "src/omni.py", line 1966, in <module>
   sys.exit(main())
 File "src/omni.py", line 1960, in main
   API_call(framework, config, args, opts, verbose=opts.verbose)
 File "src/omni.py", line 1787, in API_call
   result = handler._handle(args)
 File "src/omni.py", line 121, in _handle
   return getattr(self,call)(args[1:])
 File "src/omni.py", line 1252, in renewslice
   retVal +=self._print_slice_expiration(urn)
 File "src/omni.py", line 1455, in _print_slice_expiration
   if sliceexp <= now:
TypeError: can't compare offset-naive and offset-aware datetimes
```

 _Imported from trac ticket [#47](http://trac.gpolab.bbn.com/gcf/ticket/47),  created by tmitchel on 06-30-2011 at 15:02, last modified: 07-06-2011 at 09:50_
   CCing: ahelsing@..., sedwards@...

**Comment by tcmitchell** [comment]
ProtoGENI recently changed their slice credential to specify a timezone ("Z") in the expiration. I suspect omni is trying to compare that timezone-aware datetime with a timezone-naive datetime.

Note that it looks like the renew succeeded and omni is doing some checks on the new expiration.

_Trac comment by tmitchel (github user: tcmitchell) on 06-30-2011 at 15:04_

**Comment by tcmitchell** [comment]
I see a similar stack trace when trying to renew the sliver (now that the slice has been renewed):
```
$ src/omni.py -c ~/.gcf/omni-utah -a https://boss.emulab.net/protogeni/xmlrpc/am renewsliver tmgec11 20110707T17:00
INFO:omni:Loading config file /home/tmitchel/.gcf/omni-utah
INFO:omni:Using control framework pg
Enter PEM pass phrase:
Traceback (most recent call last):
  File "src/omni.py", line 1966, in <module>
    sys.exit(main())
  File "src/omni.py", line 1960, in main
    API_call(framework, config, args, opts, verbose=opts.verbose)
  File "src/omni.py", line 1787, in API_call
    result = handler._handle(args)
  File "src/omni.py", line 121, in _handle
    return getattr(self,call)(args[1:])
  File "src/omni.py", line 879, in renewsliver
    retVal += self._print_slice_expiration(urn, slice_cred) +"\n"
  File "src/omni.py", line 1455, in _print_slice_expiration
    if sliceexp <= now:
TypeError: can't compare offset-naive and offset-aware datetimes
```


_Trac comment by tmitchel (github user: tcmitchell) on 06-30-2011 at 15:06_

**Comment by tcmitchell** [comment]
I added a `naiveUTC` function to convert datetime objects to timezone-naive UTC. If the datetime is already naive, it is returned. If the datetime is timezone-aware, it is converted to UTC, then the timezone is stripped off making it timezone naive.

All comparisons are done using timezone-naive datetimes in UTC.


_Trac comment by tmitchel (github user: tcmitchell) on 06-30-2011 at 15:08_

**Comment by ahelsing** [comment]
Other places in the code that do time comparison and need fixes:
 * delegateSliceCred (lines 144 and 146)
 * ch.py (line 220 and 304)
 * am.py (around line 448 and 569)

Plus we should review the AM API wiki page, and the related cert & cred pages, to ensure we specify how times are interpreted
 - no TZ means UTC
 - do we prefer with or without a TZ specified?


_Trac comment by ahelsing on 07-01-2011 at 09:36_

**Comment by ahelsing** [comment]
Made appropriate edits.

Internally we'll be TZ naive in UTC
AM API specifies you must supply a TZ (RFC3339) in renewsliver. But the slice cred says ISO8601 (you can decide).
Note that slice authorities may be inconsistent in whether they interpret times in the specified timezone, always as UTC, or always as a local time wherever they are.


_Trac comment by ahelsing on 07-01-2011 at 11:05_

**Comment by luisanevers** [comment]
Verified that timezone is always UTC no matter what is specified for an argument:

  Args: renewslice llnn-slice11 20110712T12:00:00 [[BR]]
  Args: renewslice llnn-slice11 07/19/11 20:00:00 [[BR]]


_Trac comment by lnevers (github user: luisanevers) on 07-05-2011 at 17:48_

**Comment by luisanevers** [comment]
Replying to [lnevers](comment:6):
> Verified that timezone is always UTC no matter what is specified for an argument:
> 
>   Args: renewslice llnn-slice11 20110712T12:00:00 [[BR]]
>   Args: renewslice llnn-slice11 07/19/11 20:00:00 [[BR]]

Also verified:
    Args: renewslice llnn-slice22 2011-07-07 19:43:04+00:00


_Trac comment by lnevers (github user: luisanevers) on 07-06-2011 at 09:50_
