### ISSUE TITLE
PlanetLab PI's with a slice w/ same name as username will download wrong gid

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#49]
If the following are true, it is possible to download the wrong PlanetLab gid in Omni causing Omni to not work:
 1. the user is a PI
 2. the user has a slice with the same name as their username

Under these circumstances the user and the slice have the same hrn (eg plc.bbn.smith).  If a PI calls Resolve with this hrn, it returns a list of length > 1.  The code returns the first item in the list. The result is that if you don't have a user gid downloaded, when omni downloads it for you it won't work.

 _Imported from trac ticket [#49](http://trac.gpolab.bbn.com/gcf/ticket/49),  created by sedwards on 07-12-2011 at 09:04, last modified: 07-14-2011 at 14:26_
   CCing: ahelsing@..., tmitche@..., vthomas@...

**Comment by ahelsing** [comment]
Latest omni checks the type of the returned GIDs to ensure it uses user gids for users, sice gids for slices


_Trac comment by ahelsing on 07-14-2011 at 14:26_
