### ISSUE TITLE
add option to get member keys from the CH for reservations

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#491]
Add an option that causes createsliver and provision to retrieve all slice member keys from the CH and use those to augment the keys in the omni config file when passing the users struct to reserve resources

The same flag should also be honored by performoperationalaction when the action is `geni_update_users`

To do this, add a helper in amhandler or handler_utils that calls the listmembers function on the framework and turns the result into the proper struct, augmented with keys in your omni_config

 _Imported from trac ticket [#491](http://trac.gpolab.bbn.com/gcf/ticket/491),  created by ahelsing on 02-04-2014 at 16:16, last modified: 02-18-2014 at 13:52_
   CCing: gpo-expt-support@...

**Comment by seledwards** [comment]
Is this a duplicate of #278?

_Trac comment by sedwards (github user: seledwards) on 02-04-2014 at 17:50_

**Comment by ahelsing** [comment]
From consultations with Niky & Sarah:
{{{
 POA:
    If geni_update_users
        if JSON file, use that
        else try getting keys from CH. If get NotImplemented, then have no keys

    Q: Is there an option that disables trying to get keys from the CH?

  create/provision:
    Niky says default should be to use CH and have an option that says use omni_config. But maybe reverse that?
       If not option and CHAPI, use CH keys. Else use omni_config
         Q: Is it also and chapi CH lists some users/keys?


_Trac comment by ahelsing on 02-14-2014 at 16:19_

**Comment by ahelsing** [comment]
For GEC19, getting this in POA is the priority.
Also note that if this wasn't in the official 2.5 release but was available by the GEC, that would be OK.

_Trac comment by ahelsing on 02-14-2014 at 16:27_

**Comment by ahelsing** [comment]
Add this logic in amhandler._get_users_arg (at least for createsliver and provision), and then in poa call this

_Trac comment by ahelsing on 02-17-2014 at 23:05_

**Comment by ahelsing** [comment]
I think I want a single option `--useSliceMembers` that defaults to false, for all of createsliver, provision, and poa geni_update_users.

So
poa:
  if geni_update_users:
    If got json file on commandline, use that
    else if useSliceMembers and getMembersOfSlice does not raise NotImplementedError, use that
    else use the omni config

createsliver/provision:
    if useSliceMembers and getMembersOfSlice does not raise NotImplementedError, use that
    else use the omni config (current behavior)

This differs from what Niky wanted in a couple ways:
 1. For poa, you need to supply the useSliceMembers option to get it to query the CH for members
 2. Fore create/provision, you need to supply the useSliceMembers option to get it to query the CH for members

Reasoning
 - I like these being consistent, because I think it is less confusing
 - I'm wary of changing the default behavior of createsliver

Speak up if this really bothers anyone.


_Trac comment by ahelsing on 02-18-2014 at 09:38_

**Comment by ahelsing** [comment]
Sarah spoke up.

Sarah convinced me that you should be able to get members from _both_ the clearinghouse / your slice, _and_ from your omni_config.

So it is not if/else but rather 2 separate if blocks, accumulating users.

Additionally, we'll add a config option allowing you to disable reading users from your omni_config.

So
if useSliceMembers then get members from CH

if not ignoreConfigUsers then get members from omni_config

Sarah argued that useSliceMembers should default True. I'm nervous to do that now as it changes createsliver, and makes no sense at clearinghouses other than ours (and with other than the new chapi framework). 
So I think for now we do not default that to True.

However, we could add a config option in the omni_config that would change the default - essentially acting like you specified the option. Then if we want, running omni-configure could set that option.

I'll start by getting the logic in place.


_Trac comment by ahelsing on 02-18-2014 at 10:29_

**Comment by ahelsing** [comment]
Added --useSliceMembers (default false) and --ignoreConfigUsers (default False)

omni_config in the omni section accepts new lines to set those options
useslicemembers = True
ignoreconfigusers = True


_Trac comment by ahelsing on 02-18-2014 at 13:52_
