### ISSUE TITLE
make `stitcher.py` filenames compatible with Windows

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#497]
`gcf/src/omnilib/stitchhandler.py` uses a SLICRED_FILENAME variable which generates filenames which cause Windows stitcher to fail.

The error is:
```
Traceback (most recent call last):
  File "C:\gcf\src\stitcher.py", line 188, in <module>
    sys.exit(main())
  File "C:\gcf\src\stitcher.py", line 169, in main
    text, item = call(argv)
  File "C:\gcf\src\stitcher.py", line 160, in call
    return handler.doStitching(args)
  File "C:\gcf\src\omnilib\stitchhandler.py", line 167, in doStitching
    (sliceurn, sliceexp) = self.confirmSliceOK()
  File "C:\gcf\src\omnilib\stitchhandler.py", line 494, in confirmSliceOK
    handler_utils._save_cred(self, self.opts.slicecredfile[:trim], slicecred)
  File "C:\gcf\src\omnilib\util\handler_utils.py", line 622, in _save_cred
    with open(filename, 'w') as file:
IOError: [Errno 2] No such file or directory: '/tmp/slice-ch\\.geni\\.net.tutori
al.stitchtest-for-sedwards-cred.xml'
```
This is cause by this line:
```
# File in which we save the slice cred so omni calls don't have to keep re-fetching it
# Valid substitutions: %username, %slicename, %slicehrn
SLICECRED_FILENAME = '/tmp/slice-%slicehrn-for-%username-cred.xml'
```

Second, we get the following very similar error:
```
Traceback (most recent call last):
  File "C:\gcf\src\stitcher.py", line 188, in <module>
    sys.exit(main())
  File "C:\gcf\src\stitcher.py", line 169, in main
    text, item = call(argv)
  File "C:\gcf\src\stitcher.py", line 160, in call
    return handler.doStitching(args)
  File "C:\gcf\src\omnilib\stitchhandler.py", line 215, in doStitching
    self.saveAggregateList(sliceurn)
  File "C:\gcf\src\omnilib\stitchhandler.py", line 1019, in saveAggregateList
    with open (fname, 'w') as file:
IOError: [Errno 2] No such file or directory: 'ch\\.geni\\.net.tutorial.stitchte
st-amlist.txt'
```

 _Imported from trac ticket [#497](http://trac.gpolab.bbn.com/gcf/ticket/497),  created by sedwards on 02-05-2014 at 13:48, last modified: 02-05-2014 at 17:07_
   CCing: gpo-expt-support@..., rrhain@...

**Comment by seledwards** [comment]
The issue is pretty clearly the `\\` in the filename.

_Trac comment by sedwards (github user: seledwards) on 02-05-2014 at 14:25_

**Comment by seledwards** [comment]
The `\\` is due to the use of the slice hrn in the filename which I think will always or almost always result in the `\\`.

_Trac comment by sedwards (github user: seledwards) on 02-05-2014 at 14:32_

**Comment by ahelsing** [comment]
We should be able to translate "bad chars" in the hrn into harmless characters. See EG handler_utils line 419. That list of bad characters is probably too conservative for us here (no period or hyphen!), but is a decent code example

_Trac comment by ahelsing on 02-05-2014 at 14:48_

**Comment by seledwards** [comment]
I did what Aaron suggested and it seems to work.  

This appears to have been the only issue with running stitcher on Windows.

I tested createsliver, renewsliver, and deletesliver on both Windows and UNIX and they all worked.  

_Trac comment by sedwards (github user: seledwards) on 02-05-2014 at 17:07_
