### ISSUE TITLE
Support new SCS listaggregates method

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#501]
Xi says:
```
The new API method has been added to SCS. It lists all URN and URL of all aggregates known to SCS.
Please try it out. 

<?xml version="1.0"?>
 <methodCall>
 <methodName>ListAggregates</methodName>
 <params>
 </params>
 </methodCall>

```

 _Imported from trac ticket [#501](http://trac.gpolab.bbn.com/gcf/ticket/501),  created by ahelsing on 02-11-2014 at 13:09, last modified: 02-12-2014 at 11:23_

**Comment by ahelsing** [comment]
Added code to call it, docs in the README on how to call it, plus commented out code that would use it in the stitchandler to check the AMs you are using, but that is slow to little benefit.

_Trac comment by ahelsing on 02-11-2014 at 21:44_

**Comment by luisanevers** [comment]
On line 256, stitcher README instructs to use:

   $python src/omnilib/stich/scs.py --listaggregates


This is incorrect, the file is in a different path in the tar ball I just got. I had to use:

   $ python src/gcf/omnilib/stitch/scs.py --listaggregates

_Trac comment by lnevers (github user: luisanevers) on 02-12-2014 at 10:34_

**Comment by ahelsing** [comment]
oops. Will be fixed in next tarball.

_Trac comment by ahelsing on 02-12-2014 at 10:38_

**Comment by luisanevers** [comment]
Question: 

Stitching README include a "ION Aggregate" section, but does not have a "MAX aggregate section.  Should it?


_Trac comment by lnevers (github user: luisanevers) on 02-12-2014 at 10:43_

**Comment by ahelsing** [comment]
I'm not sure what it would say. How about I add under the 'ION Aggregate' a sentence:
```
This same software runs other aggregates for OSCARS networks,
specifically the MAX aggregate.
```


_Trac comment by ahelsing on 02-12-2014 at 10:54_

**Comment by luisanevers** [comment]
Sound good. Should we also tell the reader that these aggregates (ION, MAX) may show up as part of their paths and do not have any computation resources?


_Trac comment by lnevers (github user: luisanevers) on 02-12-2014 at 11:23_
