### ISSUE TITLE
add an option to just generate an expanded request

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#505]
Add an option to stitcher that doesn't do the reservations, just generates an expanded request RSpec. Useful for debugging if nothing else.

 _Imported from trac ticket [#505](http://trac.gpolab.bbn.com/gcf/ticket/505),  created by ahelsing on 02-14-2014 at 11:28, last modified: 02-17-2014 at 09:45_

**Comment by luisanevers** [comment]
Verified the new stitcher option --noReservation using gcf-2.5-021414 for multiple topologies including  fixed end-point topologies.  Verified description in README-stitching.txt and stitcher --help.  There is only one minor issue, there are 2 typos on line 211, need to fix "reservate" and "intead".


_Trac comment by lnevers (github user: luisanevers) on 02-17-2014 at 09:45_
