### ISSUE TITLE
omni should  have a delete slice member function

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-tools#515]
Currently omni has  "list" and "add" slice members commands.  But,there should be a "delete" slice member function to fully manage members from the command line. This function is available in the portal.

 _Imported from trac ticket [#515](http://trac.gpolab.bbn.com/gcf/ticket/515),  created by lnevers on 02-18-2014 at 10:49, last modified: 05-17-2014 at 16:25_

**Comment by seledwards** [comment]
Good point.  But I think it should be "remove" not "delete".

_Trac comment by sedwards (github user: seledwards) on 02-18-2014 at 11:01_

**Comment by luisanevers** [comment]
Existing omni commands use delete:

  - deletesliver <slicename> [API V1&2 only](AM) 
  - delete <slicename> [API V3 only](AM) 
  - deleteimage <imageurn> [creatorurn](optional:) [only](ProtoGENI/InstaGENI) 
  - deleteslice <slicename> 

There are no other "remove" commands.


_Trac comment by lnevers (github user: luisanevers) on 02-18-2014 at 11:10_

**Comment by seledwards** [comment]
Right, but unlike `deletesliver` or `deleteimage` you aren't deleting the user.  You are removing them from the slice.  The user still exists it's just not associated with that slice. 



_Trac comment by sedwards (github user: seledwards) on 02-18-2014 at 11:54_

**Comment by luisanevers** [comment]
The commands are not about adding and deleting a user, they are about modifying "membership" there is no mention of user in the command name.  

Anyways.... call it whatever you want.


_Trac comment by lnevers (github user: luisanevers) on 02-18-2014 at 13:02_

**Comment by ahelsing** [comment]
Jeanne says this would be really useful.

_Trac comment by ahelsing on 04-17-2014 at 11:23_

**Comment by ahelsing** [comment]
Hussam suggests a method 'modifySliceMembership' that takes a struct of some sort to add, remove, change roles all at once.

_Trac comment by ahelsing on 04-22-2014 at 11:02_

**Comment by MarshallBrinn** [comment]
removeslicemember added to omni and support added to framework_base and framework_chapi. I decided to call it that because it is consistent with the Federation API naming (members_to_remove).

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-17-2014 at 16:25_
