### ISSUE TITLE
Make `omni-configure.py` speak chapi to the portal instead of pgch

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#519]
Have `omni-configure.py` configure the portal as a `chapi` framework instead of a `pgch` framework.

Should this be optional is some way?  (Perhaps have a flag to maintain the current behavior?)

 _Imported from trac ticket [#519](http://trac.gpolab.bbn.com/gcf/ticket/519),  created by sedwards on 02-19-2014 at 14:05, last modified: 02-24-2014 at 16:04_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
The omni config section should include:
```
type = chapi
ch = https://ch.geni.net:8444/CH
ma = https://ch.geni.net/MA
sa = https://ch.geni.net/SA
authority = ch.geni.net
```
Plus the cert and key.

Note that the ma and sa entries are optional, but adding them eliminates an extra call to the CH.

You can consider whether to include (in the general omni section):
```
# Over-ride the commandline setting of --useSliceMembers to force it True
# useslicemembers = True
```


_Trac comment by ahelsing on 02-19-2014 at 14:12_

**Comment by seledwards** [comment]
Here's what I did:
 * `omni-configure` will now look in `omni-bundle.zip` for `omni_config_chapi` which contains the `chapi` config info.
 * If it exists, it uses that file.  If it doesn't exist, it looks for `omni_config` (which contains the `pgch` config info) in the zip file.
 * In addition there is a `--not-use-chapi` flag which forces you to skip the lookup for the `omni_config_chapi` file.
 * In addition, I set the `useslicemember` to true if the type of the framework is chapi. (I'll ponder this some more to see if that's actually right.)


_Trac comment by sedwards (github user: seledwards) on 02-21-2014 at 10:39_

**Comment by seledwards** [comment]
To test:
 * Download your `omni-bundle.zip` from the [Portal Profile page](https://portal.geni.net/secure/profile.php#omni)
 * make a copy of `omni-bundle.zip` (let's call the copy `omni-bundle-chapi.zip` for clarity here but you don't have to rename it)
 * unzip the `omni-bundle.zip`
 * make a copy of `omni_config` called `omni_config_chapi` 
 * in `omni_config_chapi` replace the portal section with the following:
```
[portal]
type = chapi
authority=ch.geni.net
ch=https://ch.geni.net:8444/CH
ma=https://ch.geni.net/MA
sa=https://ch.geni.net/SA

cert = /PATH/TO/YOUR/CERTIFICATE/AS/DOWNLOADED/FROM/PORTAL/geni-sedwards.pem
key = /PATH/TO/YOUR/CERTIFICATE/AS/DOWNLOADED/FROM/PORTAL/geni-sedwards.pem

useslicemembers = True

verbose=false
```
 * make a modified `omni-bundle-chapi.zip` by running the following command:
```
zip -r omni-bundle-chapi.zip omni_config_chapi
```
 * run `omni-configure` with the new bundle:
```
  omni-configure.py -z ~/Downloads/omni-bundle-chapi.zip  -c omni_config_chapi_test
```

 * test using the `-c` option:
```
omni.py -c omni_config_chapi_test listslicemembers monitor # works
omni.py -c omni_config_chapi_test getusercred -o # works
```
 * now run `omni-configure` on the original `omni-bundle.zip`
```
  omni-configure.py -z ~/Downloads/omni-bundle.zip  -c omni_config_portal_test
```
 * test using the `-c` option:
```
omni.py -c omni_config_portal_test listslicemembers monitor # gives a "not supported" error
omni.py -c omni_config_portal_test getusercred -o # works
```
 * test createsliver: slice members should be added to slivers by default (without using the `--useSliceMembers` flag)

_Trac comment by sedwards (github user: seledwards) on 02-21-2014 at 10:51_

**Comment by seledwards** [comment]
Actually the `[portal]` section of `omni_config_chapi` should be:
```
[portal]
type = chapi
authority=ch.geni.net
ch=https://ch.geni.net:8444/CH
ma=https://ch.geni.net/MA
sa=https://ch.geni.net/SA

cert = /PATH/TO/YOUR/CERTIFICATE/AS/DOWNLOADED/FROM/PORTAL/geni-sedwards.pem
key = /PATH/TO/YOUR/CERTIFICATE/AS/DOWNLOADED/FROM/PORTAL/geni-sedwards.pem

verbose=false
```

I don't know if it matters if we put in the [omni] section:
```
useslicemembers = True
```

_Trac comment by sedwards (github user: seledwards) on 02-21-2014 at 11:15_
