### ISSUE TITLE
`readyToLogin --useSliceAggregates` gives error

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#534]
Running `readyToLogin` with the --useSliceAggregates flag instead of the appropriate `-a` doesn't seem to work:
```
$ readyToLogin.py omnitest3 --useSliceAggregates
20:24:05 WARNING  omni: No resource listing returned!
20:24:05 WARNING  omni: No RSpec returned for slice omnitest3 from uky-emulab-net
Couldn't parse the manifest RSpec.
```

 _Imported from trac ticket [#534](http://trac.gpolab.bbn.com/gcf/ticket/534),  created by sedwards on 02-24-2014 at 20:26, last modified: 02-25-2014 at 11:30_

**Comment by ahelsing** [comment]
`--useSliceAggregates` relies on getting a slice name argument. It does not work at commands 'getversion', 'listimages', 'deleteimage', 'createsliver', 'allocate', 'provision'. 

And of course you need to provide a slice name argument.

Alternatively, you should be able to call handler_utils._listaggregates with an object that has an options element on which you have set the useSliceAggregates and sliceName options, plus a logger, and a config struct (to get the aggergate nicknames), and a framework (to call the CH for the list of aggregates)


_Trac comment by ahelsing on 02-24-2014 at 20:56_

**Comment by ahelsing** [comment]
Better: Call the new (chhandler) method listslivers before calling getversion. The keys of the return struct are the URNs of the AMs in the slice. If that list is empty and you have no -a arguments, exit. Else for each URN, use the utility function in handler_utils to lookupNickUrlbyURN (that's not the right name, but something like that). That should give you a URL or nickname to use for the value of the -a options to pass to getversion and the other methods.


_Trac comment by ahelsing on 02-24-2014 at 21:17_

**Comment by seledwards** [comment]
Thanks.

_Trac comment by sedwards (github user: seledwards) on 02-24-2014 at 21:38_

**Comment by seledwards** [comment]
For the curious, added this code before the call to getversion:

```
  # Find aggregates which have resources in this slice
  # Run equivalent of 'omni.py listslivers'
  argv = [slicename]('listslivers',)
  try:
    text, slivers = omni.call( argv, options )
  except (oe.AMAPIError, oe.OmniError) :
    print "ERROR: There was an error executing listslivers, review the logs."
    sys.exit(-1)

  aggregateURNs = slivers.keys()
  if len(aggregateURNs) == 0 and (not options.aggregate or (len(options.aggregate) == 0)):
    print "ERROR: There are no known resources at any aggregates. Try using '-a' to specify an aggregate."
    sys.exit(-1)      

  # construct a list of aggregates to 
  handler = CallHandler(framework,config,options)
  newAggURLs = [ lookupURL( handler.logger, config, urn )[1] for urn in aggregateURNs ] 
  if options.aggregate:
      options.aggregate = options.aggregate + newAggURLs
  else:
      options.aggregate = newAggURLs

```

This works really nicely now.  The new version means that you don't have to specify `-a` or even `--useSliceAggregates` to run `readyToLogin`.  Anything in `-a` should be checked in addition to everything the CH knows about.


_Trac comment by sedwards (github user: seledwards) on 02-24-2014 at 22:21_

**Comment by seledwards** [comment]
Since `remote-execute` relies on `readyToLogin` it's better for the use of `--useSliceAggregates` to be explicit.  Reopening.

_Trac comment by sedwards (github user: seledwards) on 02-25-2014 at 11:08_

**Comment by seledwards** [comment]
Fixing. Closing.

_Trac comment by sedwards (github user: seledwards) on 02-25-2014 at 11:30_
