### ISSUE TITLE
Add am_type and am_code to GCF AMs

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#568]
Implement change set N as part of our APIv3 AM, adding am_type and am_code values in getversion

 _Imported from trac ticket [#568](http://trac.gpolab.bbn.com/gcf/ticket/568),  created by ahelsing on 03-20-2014 at 09:09, last modified: 05-19-2014 at 11:47_

**Comment by MarshallBrinn** [comment]
Added to GCF am3.py. 

Note: We added a new file gcf_version.py to hold the current GCF version; this should should be updated on new releases (no longer the value in oscript.py which now imports from gcf_version).



_Trac comment by mbrinn (github user: MarshallBrinn) on 05-19-2014 at 11:47_
