### ISSUE TITLE
Tracking of FOAM slivers in the CH

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-tools#574]
I used gcf 2.5 to create FOAM slivers but when using the --useSliceAggregates flag the FOAM slivers are not included. I have run this in Ubuntu (using the src code) and in Mac using the application. 

Attached is a simple FOAM rspec for the wisconsin IG OF AM that I used to reproduce this on a single AM. What I did is:
 1. Create a slice
 2. Create a sliver with the attached rspec
 3. Checked the status using -a wisconsin-ig-of
 4. Tried to renew using --useSliceAggregates and got the following output
 ```
 12:11:15 WARNING  omni: No aggregates found: 0 aggregates known to have resources for slice testfoam
12:11:15 ERROR    omni: 
No Aggregates left to operate on.
```

 _Imported from trac ticket [#574](http://trac.gpolab.bbn.com/gcf/ticket/574),  created by nriga on 03-26-2014 at 12:11, last modified: 04-10-2014 at 16:22_

**Comment by innnkkki** [comment]
_nriga (innnkkki) attached [test-foam.rspec](http://trac.gpolab.bbn.com/gcf/attachment/ticket/574/test-foam.rspec) on 03-26-2014 at 12:12_

**Comment by ahelsing** [comment]
'omni listslivers' doesn't seem to list my FOAM slivers in general, either.

_Trac comment by jbs on 03-26-2014 at 12:14_

**Comment by ahelsing** [comment]
The problem likely has to do with aggregate nicknames and URNs: This functionality depends on being able to determine the URN of the aggregate consistently. I did not test that with FOAM.

_Trac comment by ahelsing on 03-26-2014 at 16:10_

**Comment by ahelsing** [comment]
Actually, the problem may be that the code relies on finding sliver_id attributes in the manifest RSpec to ID the slivers that have been created (and then to use that to ID the AM that gave these slivers). I don't know that the FOAM manifests do this.

_Trac comment by ahelsing on 03-27-2014 at 09:15_

**Comment by ahelsing** [comment]
Here's a FOAM manifest:

```
<rspec type="manifest" xmlns="http://www.geni.net/resources/rspec/3" xmlns:openflow="http://www.geni.net/resources/rspec/ext/openflow/3" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://www.geni.net/resources/rspec/3            http://www.geni.net/resources/rspec/3/manifest.xsd            http://www.geni.net/resources/rspec/ext/openflow/3            http://www.geni.net/resources/rspec/ext/openflow/3/of-resv.xsd">  

    <openflow:sliver description="gpoI15 UtahDDC InstaGENI OpenFlow resources.">    

        <openflow:controller type="primary" url="tcp:naxos.gpolab.bbn.com:13715"/>    

        <openflow:group name="utahddc-instageni-openflow-1750">      
            <openflow:datapath component_id="urn:publicid:IDN+openflow:foam:foam.utahddc.geniracks.net+datapath+06:d6:24:be:05:fe:43:00" component_manager_id="urn:publicid:IDN+openflow:foam:foam.utahddc.geniracks.net+authority+am"/>      
            <openflow:datapath component_id="urn:publicid:IDN+openflow:foam:foam.utahddc.geniracks.net+datapath+17:50:70:b3:d5:3e:10:05" component_manager_id="urn:publicid:IDN+openflow:foam:foam.utahddc.geniracks.net+authority+am"/>      
        </openflow:group>    

        <openflow:match>      

            <openflow:use-group name="utahddc-instageni-openflow-1750"/>      

            <openflow:packet>        
                <openflow:dl_type value="0x800,0x806"/>        
                <openflow:nw_dst value="10.137.15.0/24"/>        
                <openflow:nw_src value="10.137.15.0/24"/>        
            </openflow:packet>      

        </openflow:match>    

    </openflow:sliver>  

</rspec>
```

I don't see sliver_id in there. If it's supposed to be, can you open a FOAM ticket about it? (Or I can if you'd like.)

_Trac comment by jbs on 03-27-2014 at 10:12_

**Comment by ahelsing** [comment]
The of-resv v3 schema has no spot for a sliver_id. So there is no way for a FOAM AM to tell you the URN of the sliver(s) it is creating. Presumably however if I call sliverstatus later at a FOAM AM, I get a sliver URN? Maybe Omni will have to call sliverstatus at a FOAM AM after doing createsliver so it can learn about the sliver URNs to report.

_Trac comment by ahelsing on 03-27-2014 at 10:24_

**Comment by ahelsing** [comment]
sliverstatus has geni_urn:

```
10:27:10 INFO     omni: {
  "geni_status": "ready", 
  "geni_urn": "urn:publicid:IDN+ch.geni.net:gpo-infra+slice+gpoI15:5c215b6a-ed6f-46dd-99f3-09c80e10d71b", 
  "foam_pend_reason": [], 
  "foam_expires": "2014-05-15 23:00:00+00:00", 
  "geni_resources": [
    {
      "geni_urn": "urn:publicid:IDN+ch.geni.net:gpo-infra+slice+gpoI15:5c215b6a-ed6f-46dd-99f3-09c80e10d71b", 
      "geni_error": "", 
      "geni_status": "ready"
    }
  ], 
  "foam_status": "approved"
}
```

_Trac comment by jbs on 03-27-2014 at 10:28_

**Comment by ahelsing** [comment]
In that example, was your slice name "gpoI15"? Or that full longer thing with the URN appended?

This looks to me like a slice URN, not a sliver URN. In particular, it does not name the aggregate, nor list the type of the URN as a sliver URN. So this doesn't help me.

Additionally, this is a bug in FOAM.
Per the spec, that field should be a sliver URN: http://groups.geni.net/geni/wiki/GAPI_AM_API_V2_DETAILS#MembersoftheSliverStatusvaluereturnstruct

Can you open a ticket on FOAM?


_Trac comment by ahelsing on 03-27-2014 at 10:33_

**Comment by ahelsing** [comment]
My slice name is gpoI15. I think urn:publicid:IDN+ch.geni.net:gpo-infra+slice+gpoI15:5c215b6a-ed6f-46dd-99f3-09c80e10d71b is the sliver URN, and urn:publicid:IDN+ch.geni.net:gpo-infra+slice+gpoI15 is my slice URN.

It does look like that doesn't match http://groups.geni.net/geni/wiki/GeniApiIdentifiers, though.

I created https://openflow.stanford.edu/bugs/browse/FOAM-423 for this, let me know if I got the description of the problem right.

_Trac comment by jbs on 03-27-2014 at 10:40_

**Comment by ahelsing** [comment]
Given current state of FOAM, Omni will have to
 - pull out the first component_manager_id from the datapath. Use that as the AM URN
 - call sliverstatus. Pull out the geni_urn. Take the bit after what we know to be the slice_urn, pull off the leading colon. Use the rest to construct a sliver urn
  - If the geni_urn does not start with the slice_urn, then use it as a sliver URN itself.


_Trac comment by ahelsing on 03-27-2014 at 11:16_

**Comment by ahelsing** [comment]
Nick says that sample manifest above is wrong, relative to the latest FOAM. In the latest FOAM, there is no component_id or component_manager_id in the manifest, although Nick has agreed to add in the component_manager_id in the manifest somewhere in future.

So for now, Omni would have to know the AM URN in advance (from the agg_nick_cache. And if it doesn't have it, it skips reporting. Then, Omni can either 
 - make up a sliver URN (based on the current time and the slice URN, or with a UID)
 - get that UID from sliverstatus as above


_Trac comment by ahelsing on 03-27-2014 at 13:34_

**Comment by ahelsing** [comment]
I'll make up a sliver URN using a UID for now.

_Trac comment by ahelsing on 04-10-2014 at 16:19_
