### ISSUE TITLE
Add `addMemberToSliceAndSlivers` to both Windows and Mac distributions

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#585]
The new `gcf/examples/addMemberToSliceAndSlivers.py` should be added to both the Mac and Windows distributions for the next release.

 _Imported from trac ticket [#585](http://trac.gpolab.bbn.com/gcf/ticket/585),  created by sedwards on 04-01-2014 at 15:55, last modified: 04-11-2014 at 15:51_
   CCing: gpo-expt-support@..., rrhain@...

**Comment by ahelsing** [comment]
Regina will work on the Mac application.

_Trac comment by vthomas on 04-02-2014 at 12:35_

**Comment by ahelsing** [comment]
Touched the windows files that should make this happen: setup.py and package_builder.iss and the mac files which are makeMacdmg.sh and addAliases.sh so it should work for the next omniTools release.

_Trac comment by rrhain on 04-11-2014 at 10:35_
