### ISSUE TITLE
ReadyToLogin exception for FIU slice only

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-tools#598]
Created a sliver at FIU with 1 VM and 1 Bare Metal, attempts to run `readyToLogin.py` continue to fail (12 minutes) after sliver creation:
```
$ readyToLogin.py -a fiu-eg EG-CT-2-fiu 
Key file [/home/lnevers/.ssh/arendia-id_rsa] does NOT exist.
Key file [/home/lnevers/.ssh/sendaria-id_rsa] does NOT exist.
Traceback (most recent call last):
  File "/home/lnevers/gcf-2.5/examples/readyToLogin.py", line 902, in <module>
    sys.exit(main())
  File "/home/lnevers/gcf-2.5/examples/readyToLogin.py", line 889, in main
    loginInfoDict, keyList = main_no_print(argv=argv)
  File "/home/lnevers/gcf-2.5/examples/readyToLogin.py", line 873, in main_no_print
    amLoginInfo = getInfoFromSliceManifest(amUrl)
  File "/home/lnevers/gcf-2.5/examples/readyToLogin.py", line 226, in getInfoFromSliceManifest
    maniInfo = getInfoFromManifest(manifest)
  File "/home/lnevers/gcf-2.5/examples/readyToLogin.py", line 136, in getInfoFromManifest
    geni_status = gsi_el.attrib['state']
KeyError: 'state'
```

Attaching the list resources output for the sliver that cause this exception.  Note other slivers exist at the site and am able to get readyToLogin info on other slices.

 _Imported from trac ticket [#598](http://trac.gpolab.bbn.com/gcf/ticket/598),  created by lnevers on 04-09-2014 at 14:53, last modified: 10-15-2014 at 12:52_

**Comment by luisanevers** [comment]
_lnevers (luisanevers) attached [EG-CT-2-fiu-manifest-rspec-exogeni-net-fiuvmsite.xml](http://trac.gpolab.bbn.com/gcf/attachment/ticket/598/EG-CT-2-fiu-manifest-rspec-exogeni-net-fiuvmsite.xml) on 04-09-2014 at 14:53_

**Comment by ahelsing** [comment]
Looks like this has since been fixed.

_Trac comment by ahelsing on 10-15-2014 at 12:52_
