### ISSUE TITLE
Update the protogeni rspec/omnispec conversion

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#6]
We never built a real ProtoGENI Omnispec.  The first thing we can do is at least make it possible for users to allocate machines that are selected by protogeni.  For instance, say "I want 3 machines running this OS image please".

Perhaps we should also add some simple links between the nodes.

Then down the road we can add more options for fancy features.

 _Imported from trac ticket [#6](http://trac.gpolab.bbn.com/gcf/ticket/6),  created by jkarlin on 09-23-2010 at 16:49, last modified: 09-27-2010 at 21:42_
   CCing: tmitchel@..., ahelsing@...

**Comment by ahelsing** [comment]
So far I've added the ability to add hosts selected by protogeni. 

An omnispec looks like this for each aggregate:
```
    "https://www.emulab.net/protogeni/xmlrpc/am": {
        "urn": "urn:publicid:IDN+emulab.net+authority+cm", 
        "type": "rspec_pg", 
        "resources": {
            "RandomNode": {
                "name": "RandomNode", 
                "misc": {
                    "used nodes": 456, 
                    "free nodes": 123
                }, 
                "allocate": false, 
                "allocated": false, 
                "type": "RandomPC", 
                "options": {
                    "number": 1, 
                    "virtual": true, 
                    "startup command": "/bin/ls > /dev/null"
                }, 
                "description": "Let Protogeni select available nodes for you"
            }
        }
    }, 
```

I need to add the ability to choose images and handle XML issues with the ">" sign in the startup command.

_Trac comment by jkarlin on 09-23-2010 at 16:52_

**Comment by tcmitchell** [comment]
The initial task of creating an Omnispec for the PG RSpec is complete with just nodes.

OS images are on issue #12. Links are on issue #13. Fancy features will be specified in the future.

_Trac comment by tmitchel (github user: tcmitchell) on 09-27-2010 at 21:42_
