### ISSUE TITLE
Add remote-execute.py to the mac release

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-tools#601]
This will make the mac release different from the windows one. 

 _Imported from trac ticket [#601](http://trac.gpolab.bbn.com/gcf/ticket/601),  created by nriga on 04-22-2014 at 18:18, last modified: 06-06-2014 at 13:36_

**Comment by ahelsing** [comment]
Done.

_Trac comment by rrhain on 06-06-2014 at 13:36_
