### ISSUE TITLE
Support CH API v2

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#613]
Support v2 of the Common Federation / Clearinghouse API.

 _Imported from trac ticket [#613](http://trac.gpolab.bbn.com/gcf/ticket/613),  created by ahelsing on 05-12-2014 at 17:02, last modified: 05-22-2014 at 15:55_

**Comment by ahelsing** [comment]
I'm made the start of some local changes for this - adding a config variable to say if the CH supports v2, in which case we use it. But I haven't now made all the API calls use v2 yet.

_Trac comment by ahelsing on 05-13-2014 at 08:54_

**Comment by MarshallBrinn** [comment]
Added V2 version for all create, lookup, update, delete, modify_membership, lookup_for_members, lookup_members calls as well as changing some V1 calls to not take advantage of V2 calls. All tested and seems to work fine.

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-22-2014 at 15:55_
