### ISSUE TITLE
Acceptance tests should remove pgeni and introduce portal

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-tools#617]
Using gcf2-2.6 (05/15/2014 version)

Both the README-accept-AMAPI.txt and the sample omni_config in tha AM API Acceptance tests should remove pgeni.gpolab.bbn.com and introduce the portal as the default framework.

 _Imported from trac ticket [#617](http://trac.gpolab.bbn.com/gcf/ticket/617),  created by lnevers on 05-21-2014 at 09:04, last modified: 05-27-2014 at 11:08_

**Comment by luisanevers** [comment]
Also example RSpecs provided for acceptance testing have GPO MyPLC nots that should no longer be used.

_Trac comment by lnevers (github user: luisanevers) on 05-21-2014 at 09:24_

**Comment by ahelsing** [comment]
Using utahddc resources and Portal accounts

_Trac comment by ahelsing on 05-27-2014 at 11:08_
