### ISSUE TITLE
Acceptance test scripts not documented

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-tools#618]
The scripts am_api_accept_nagios.py and am_api_accept_scaling.py are not documented in the README-accept-AMAPI.txt.

These were in gcf-2.5, but I missed their addition.

 _Imported from trac ticket [#618](http://trac.gpolab.bbn.com/gcf/ticket/618),  created by lnevers on 05-22-2014 at 10:15, last modified: 05-27-2014 at 11:08_

**Comment by ahelsing** [comment]
adding minimal documentation

_Trac comment by ahelsing on 05-27-2014 at 11:08_
