### ISSUE TITLE
AM API Acceptance delegate slice does not create output delegation file

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-tools#619]
As user "lnevers1" created a slice, added resources, got slice credential and tried to delegate to user "lnevers", but there is no output delegation file.

Here is the command sequence issued as lnevers1:
```
$ omni.py createslice ln1deleg
$ omni.py createsliver ln1deleg ./request.xml -a am-undertest
$ omni.py getslicecred  ln1deleg -o
$ delegateSliceCred.py --cert ~/.ssl/geni_cert_portal.pem --key /tmp/lnevers-geni_cert_portal.pem --delegeegid /tmp/lnevers-geni_cert_portal.pem --slicecred ./ln1deleg-cred.xml 
INFO:delegateSlice:Getting slice credential from file ./ln1deleg-cred.xml
INFO:delegateSlice:Delegated cred will expire at same time as original: 2014-05-29 15:03:06 UTC
Slice says not all privileges are delegatable
```

Not sure which privileges are not delegatable, also checked directory and no delegation output file had been created.

 _Imported from trac ticket [#619](http://trac.gpolab.bbn.com/gcf/ticket/619),  created by lnevers on 05-22-2014 at 11:18, last modified: 05-22-2014 at 11:55_

**Comment by ahelsing** [comment]
I'll fix the error messages. But in fact, slice credentials from chapi are not delegatable currently. http://trac.gpolab.bbn.com/chapi/ticket/297


_Trac comment by ahelsing on 05-22-2014 at 11:53_
