### ISSUE TITLE
Helpful Omni error message about Expedient is unhelpful

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#66]
If a user uses a URL for an AM that Omni thinks looks like an incorrect Expedient URL, it tries to give the user a correct Expedient URL. If the user was actually trying to enter a FOAM URL (or something else other than Expedient), this can be confusing.

 _Imported from trac ticket [#66](http://trac.gpolab.bbn.com/gcf/ticket/66),  created by jbs on 11-07-2011 at 11:24, last modified: 12-08-2011 at 17:06_

**Comment by ahelsing** [comment]
I personally think that it would be better if Omni didn't try to figure out what the user meant and offer helpful suggestions, at least in this case. If we want to keep doing that, though, we should at least take into account that the user may have entered an incorrect Expedient URL when they meant to enter a FOAM URL.

_Trac comment by jbs on 11-07-2011 at 11:25_

**Comment by tcmitchell** [comment]
Original email from Josh:
```

When Luisa tried to run

 ./src/omni.py -n -a https://mallorea.gpolab.bbn.com:3626/openflow/gapi sliverstatus foamln

recently, Omni helpfully said

 WARNING:omni.protogeni:Likely invalid Expedient URL https://mallorea.gpolab.bbn.com:3626/openflow/gapi. Expedient AM runs at /openflow/gapi/ - try url https://mallorea.gpolab.bbn.com:3626/openflow/gapi/

That seems overly helpful, and in this case entirely misleading -- the
problem is that the URL is invalid, but the alternative it offers is also
wrong, because she's trying to talk to FOAM, not Expedient.

Should Omni really be trying to be this helpful? It seems to me like it
has too much potential for confusion.

This particular example is certainly confusing right now, anyway. Software
folks, should I make a GPO-SW ticket?

(Copying gpo-tech in case anyone else runs into this in the course of
migrating experimenters from Expedient to FOAM, once we start doing that.)
```


_Trac comment by tmitchel (github user: tcmitchell) on 11-08-2011 at 12:48_

**Comment by tcmitchell** [comment]
Some questions:
 * Did omni halt the operation with the "likely invalid URL" warning, or did it continue by trying to make the connection?
 * What is the correct URL that should have been used?


_Trac comment by tmitchel (github user: tcmitchell) on 11-08-2011 at 12:49_

**Comment by ahelsing** [comment]
It continued (and then failed later, because the URL was actually invalid). Here's the full output that Luisa had sent along:

```
$ ./src/omni.py -n -a https://mallorea.gpolab.bbn.com:3626/openflow/gapi sliverstatus foamln
INFO:omni:Loading config file omni_config
INFO:omni:Using control framework pgeni
INFO:omni:Slice urn:publicid:IDN+pgeni.gpolab.bbn.com+slice+foamln expires on 2011-12-12 00:42:41 UTC
WARNING:omni.protogeni:Likely invalid Expedient URL https://mallorea.gpolab.bbn.com:3626/openflow/gapi. Expedient AM runs at /openflow/gapi/ - try url https://mallorea.gpolab.bbn.com:3626/openflow/gapi/
INFO:omni:Status of Slice urn:publicid:IDN+pgeni.gpolab.bbn.com+slice+foamln:
ERROR:omni.protogeni:Call for Sliver status of urn:publicid:IDN+pgeni.gpolab.bbn.com+slice+foamln at https://mallorea.gpolab.bbn.com:3626/openflow/gapi failed.: ProtocolError: <ProtocolError for mallorea.gpolab.bbn.com:3626/openflow/gapi: 404 NOT FOUND>
ERROR:omni.protogeni:    ..... Run with --debug for more information
INFO:omni: ------------------------------------------------------------
INFO:omni: Completed sliverstatus:

  Options as run:
                aggregate: https://mallorea.gpolab.bbn.com:3626/openflow/gapi
                framework: pgeni
                native: True

  Args: sliverstatus foamln

  Result Summary: Slice urn:publicid:IDN+pgeni.gpolab.bbn.com+slice+foamln expires on 2011-12-12 00:42:41 UTC

Failed to get SliverStatus on foamln at AM https://mallorea.gpolab.bbn.com:3626/openflow/gapi: ProtocolError: <ProtocolError for mallorea.gpolab.bbn.com:3626/openflow/gapi: 404 NOT FOUND>
Returned status of slivers on 0 of 1 possible aggregates. 
INFO:omni: ============================================================
```

In this case, the correct URL should've been https://mallorea.gpolab.bbn.com:3626/foam/gapi -- she got the path wrong. But if she'd actually been trying to talk to Expedient, and gotten the *port* wrong, the correct URL would've been https://mallorea.gpolab.bbn.com:1443/openflow/gapi/ ... Which is why I'm skeptical that Omni should be trying to guess what URL the user might've meant.


_Trac comment by jbs on 11-08-2011 at 12:55_

**Comment by luisanevers** [comment]
The following is the output from the failed command:
```
$ ./src/omni.py -n -a https://mallorea.gpolab.bbn.com:3626/openflow/gapi sliverstatus foamln
INFO:omni:Loading config file omni_config
INFO:omni:Using control framework pgeni
INFO:omni:Slice urn:publicid:IDN+pgeni.gpolab.bbn.com+slice+foamln expires on 2011-12-12 00:42:41 UTC
WARNING:omni.protogeni:Likely invalid Expedient URL https://mallorea.gpolab.bbn.com:3626/openflow/gapi. Expedient AM runs at /openflow/gapi/ - try url https://mallorea.gpolab.bbn.com:3626/openflow/gapi/
INFO:omni:Status of Slice urn:publicid:IDN+pgeni.gpolab.bbn.com+slice+foamln:
ERROR:omni.protogeni:Call for Sliver status of urn:publicid:IDN+pgeni.gpolab.bbn.com+slice+foamln at https://mallorea.gpolab.bbn.com:3626/openflow/gapi failed.: ProtocolError: <ProtocolError for mallorea.gpolab.bbn.com:3626/openflow/gapi: 404 NOT FOUND>
ERROR:omni.protogeni:    ..... Run with --debug for more information
INFO:omni: ------------------------------------------------------------
INFO:omni: Completed sliverstatus:

  Options as run:
                aggregate: https://mallorea.gpolab.bbn.com:3626/openflow/gapi
                framework: pgeni
                native: True

  Args: sliverstatus foamln

  Result Summary: Slice urn:publicid:IDN+pgeni.gpolab.bbn.com+slice+foamln expires on 2011-12-12 00:42:41 UTC

Failed to get SliverStatus on foamln at AM https://mallorea.gpolab.bbn.com:3626/openflow/gapi: ProtocolError: <ProtocolError for mallorea.gpolab.bbn.com:3626/openflow/gapi: 404 NOT FOUND>
Returned status of slivers on 0 of 1 possible aggregates. 
INFO:omni: ============================================================
$
```

The correct URL that I should have used was:
```
https://mallorea.gpolab.bbn.com:3626/foam/gapi/
```

_Trac comment by lnevers (github user: luisanevers) on 11-08-2011 at 12:57_

**Comment by innnkkki** [comment]
Just to add to the comments that this improvement was made because, expedient and maybe even myPlc gave an in comprehensive error message when omitting the final '/'. Maybe Omni could try contacting the AM with the '/' before actually printing the suggestion.  

_Trac comment by nriga (github user: innnkkki) on 11-08-2011 at 16:16_

**Comment by ahelsing** [comment]
I agree this isn't helping.

We added this to try to address, as Niky says, a very unhelpful error message.

I think there are 2 options
 - Do nothing so 'clever' - backing out this addition
 - Refactor Omni so it can try the given URL, and then either make some guesses on the correct URL, or just fail


_Trac comment by ahelsing on 11-09-2011 at 10:08_

**Comment by ahelsing** [comment]
For now, I'll remove the code that has these AM specific URL checks. Apparently they are just confusing for now, and the Expedient one is irrelevant shortly.

In future perhaps Omni will test URLs (like when it checks/caches the version of the AM API running at each AM).


_Trac comment by ahelsing on 11-09-2011 at 14:46_

**Comment by ahelsing** [comment]
Commented out that confusing code

_Trac comment by ahelsing on 11-09-2011 at 15:03_
