### ISSUE TITLE
Support configurable authorization mechanisms in GCF AM

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-tools#660]
We should provide mechanisms in GCF to allow for AMs to provide their own authorization mechanisms. The default should be the current SFA-based authorization. But one could write their own code, or write one that parses externalized policies. 

First step is to add an authorization object (which can be overridden) which is specified in gcf_config and used authorizing all AM calls.

 _Imported from trac ticket [#660](http://trac.gpolab.bbn.com/gcf/ticket/660),  created by mbrinn on 06-30-2014 at 11:47, last modified: 12-11-2014 at 15:44_

**Comment by ahelsing** [comment]
Added a new ABAC authorization module. Description in README-authorization.txt

Added support for scheduling in the GCF AM. Description in README-scheduling.txt


_Trac comment by ahelsing on 12-11-2014 at 15:42_

**Comment by ahelsing** [comment]
merged onto develop

_Trac comment by ahelsing on 12-11-2014 at 15:44_
