### ISSUE TITLE
`clearpassphrases` fails for Windows users with iMinds accounts

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#664]
Niky reports that `clearpassphrases` fails for Windows users.

3-4 people with iMinds accounts experienced the same thing.

When they runs `clearpassphrases` with a specific location for the pem file, the script exits with a "File does not exist".  However it is not clear which file does not exist (the input file? output file?). 

Note, this may be an issue with internationalization as the users were all in Europe and so their paths might have different characters.

At least one user was using Windows 7.

 _Imported from trac ticket [#664](http://trac.gpolab.bbn.com/gcf/ticket/664),  created by sedwards on 07-07-2014 at 13:00, last modified: 09-15-2014 at 16:20_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
On Windows 7, I tested reading/writing files in directories whose name has a space (no problems) and which contain non ASCII characters (mostly worked).

I did not run into the 'File does not exist' error. 
I do note that printouts mangled the non ASCII characters, but things worked:

```
E:\GENI\gcf>python src\clear-passphrases.py -f pchapi -k "C:\tmp\vihreä\nyePriva
teKey_enc.key"
Do you want to remove the passphrase from the private key of your SSL cert (C:\t
mp\vihreΣ\nyePrivateKey_enc.key) [Y,n]?
INFO:clearcert:
        THIS SCRIPT WILL REPLACE 'C:\tmp\vihreΣ\nyePrivateKey_enc.key' WITH AN U
NENCRYPTED CERT KEY. A BACKUP OF THE ORIGINAL CERT WILL BE CREATED.
```

But in the end the proper output files were created.

_Trac comment by ahelsing on 09-15-2014 at 11:26_

**Comment by ahelsing** [comment]
When the file has a cert and path has a non ASCII character I reproduced the issue (or at least, got _an_ issue):
```
INFO:clearcert:Removing passphrase from private key of SSL cert...
DEBUG:clearcert:Run command: ['rsa', '-in', 'C:\\tmp\\vihre\xe4\\nye-
ahelsing-combo.pem', '-out', 'C:\\tmp\\vihre\xe4\\nye-ahelsing-combo.pem.tmp']('openssl',)
ERROR:clearcert:Failed to call openssl to remove passphrase: Command: [, 'rsa', '-in', 'C:\\tmp\\vihre\xe4\\nye-ahelsing-combo.pem', '-out', 'C:\\tmp\\
vihre\xe4\\nye-ahelsing-combo.pem.tmp']('openssl'). Error: [Error 2] The system cannot find
 the file specified
Traceback (most recent call last):
  File "src\clear-passphrases.py", line 453, in <module>
    sys.exit(main())
  File "src\clear-passphrases.py", line 428, in main
    removeSSLPassphrase(opts.prcertkey)
  File "src\clear-passphrases.py", line 386, in removeSSLPassphrase
    clearCert(prcertkey)
  File "src\clear-passphrases.py", line 166, in clearCert
    p = Popen(command, stdout=PIPE)
  File "C:\Python27\lib\subprocess.py", line 709, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```


_Trac comment by ahelsing on 09-15-2014 at 12:03_

**Comment by ahelsing** [comment]
Hmm. No, that's not it. The problem is that openssl is not on the path.

The script requires that openssl be found on your path. This is problematic, as I don't believe we deliver openssl itself in the windows binaries

_Trac comment by ahelsing on 09-15-2014 at 12:32_

**Comment by ahelsing** [comment]
Turns out the SFA libraries can read and write the cert/key and remove the passphrase. So rewrote the clearCert method to use the SFA libraries. Now we don't depend on the openssl binary. And the function works on Windows.

_Trac comment by ahelsing on 09-15-2014 at 16:19_
