### ISSUE TITLE
Remove dependence on "pg_manifest" field of sliver status return

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#665]
Protogeni and Instageni aggregates return the full manifest as part of the return from sliver status. That feature is going away because it can cause problems due to the volume of data.

Remove the dependence on "pg_manifest" in readyToLogin.py. Consider retrieving the manifest directly via list resources if the data is necessary.

 _Imported from trac ticket [#665](http://trac.gpolab.bbn.com/gcf/ticket/665),  created by tmitchel on 07-11-2014 at 14:29, last modified: 07-14-2014 at 10:55_

**Comment by seledwards** [comment]
Removed dependency on `pg_manifest` except in the `addNodeStatusCheckForPGFallback()`.  

_Trac comment by sedwards (github user: seledwards) on 07-14-2014 at 10:55_
