### ISSUE TITLE
Change the default of --useSliceMembers

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-tools#667]
Currently the default in omni is --useSliceMember = False, but omni-configure changes the default in a non-standard way by adding a line in the omni_config making it hard
for a user to figure out what is the default behavior of omni.

If omni-configure sets this to true which makes it the de-facto default, should we just change the default? 

 _Imported from trac ticket [#667](http://trac.gpolab.bbn.com/gcf/ticket/667),  created by nriga on 07-16-2014 at 06:57, last modified: 09-19-2014 at 13:26_

**Comment by ahelsing** [comment]
* useSliceMembers option is now deprecated - a no-op (if you supply it, you get a log message telling you the option is deprecated)
 * Added option noSliceMembers to change to old behavior
 * omni_config setting also accepts useslicemembers=False

Also moved the slice member options down to the developer/advanced section (they don't feel basic any more)


_Trac comment by ahelsing on 09-19-2014 at 13:26_
