### ISSUE TITLE
omni not honoring `omni_config` option `useslicemembers=true`

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#671]
It seems to me that omni is not honoring the `omni_config` option `useslicemembers=true`.

It appears that the offending code is in `gcf/src/gcf/oscript.py`:
```
    if hasattr(opts,'useslicemembers') and config['omni'].has_key('useslicemembers'):
```
Should be
```
    if hasattr(opts,'useSliceMembers') and config['omni'].has_key('useslicemembers'):
```

To test make sure `omni_config` has `useslicemembers=True` (which is the default).

Reserve a node.  All members of your slice should get an account WITHOUT setting the `--useSliceMembers` flag.

Looks like `ignoreconfigusers` has the same problem so I've added the fix for it which should also be tested.

 _Imported from trac ticket [#671](http://trac.gpolab.bbn.com/gcf/ticket/671),  created by sedwards on 07-20-2014 at 10:42, last modified: 07-21-2014 at 11:57_
   CCing: gpo-expt-support@...

**Comment by seledwards** [comment]
Looks like this changed was introduced on May 30: 
http://trac.gpolab.bbn.com/gcf/changeset/20d2d09ede09c6e7d5c15c487932849d531aeda4/src/gcf/oscript.py

_Trac comment by sedwards (github user: seledwards) on 07-20-2014 at 10:57_

**Comment by seledwards** [comment]
Changes are committed on branch `tkt671-useslicemembers` but need to be tested which I don't have time to do right this second.

_Trac comment by sedwards (github user: seledwards) on 07-20-2014 at 10:59_

**Comment by ahelsing** [comment]
changes look good

_Trac comment by ahelsing on 07-21-2014 at 11:46_
