### ISSUE TITLE
Have InstaGENI remove `pg_manifest` from `SliverStatus` after 2.7 release

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#674]
The inclusion of `pg_manifest` causes large SliverStatus calls to fail.  #665 removes the dependency on `pg_manifest` in `readyToLogin`.   This code has been tested on a dev rack with the `pg_manifest` removed from SliverStatus return. 

Once omni 2.7 is released, ask InstaGENI to remove `pg_manifest` from SliverStatus on all racks permanently.

 _Imported from trac ticket [#674](http://trac.gpolab.bbn.com/gcf/ticket/674),  created by sedwards on 07-31-2014 at 13:02, last modified: 11-14-2014 at 11:33_

**Comment by ahelsing** [comment]
Sarah - time to do this?

_Trac comment by ahelsing on 10-28-2014 at 09:16_

**Comment by ahelsing** [comment]
Leigh says this change will go out on 11/21

_Trac comment by ahelsing on 11-14-2014 at 11:11_

**Comment by ahelsing** [comment]
Leigh committed the fix: http://git-public.flux.utah.edu/?p=emulab-devel.git;a=commitdiff;h=340c576

_Trac comment by ahelsing on 11-14-2014 at 11:33_
