### ISSUE TITLE
Output of omni --version

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-tools#690]
when running omni --version the output says omni.py:
```
dhcp89-73-45:ovstools inki$ omni --version
omni.py: GENI Omni Command Line Aggregate Manager Tool Version 2.6
Copyright (c) 2014 Raytheon BBN Technologies
```

Consider whether there is away to make this consistent. 

 _Imported from trac ticket [#690](http://trac.gpolab.bbn.com/gcf/ticket/690),  created by nriga on 09-09-2014 at 17:54, last modified: 09-10-2014 at 13:52_

**Comment by ahelsing** [comment]
I don't think this is possible. Omni is already using sys.argv[0] which is as close to what you used as I think a program can get. The user could have aliased Omni to "that-crazy-thing-Niky-makes-me-use". There's no way that I know of for Omni to know this.

_Trac comment by ahelsing on 09-10-2014 at 13:52_
