### ISSUE TITLE
Create an AM API acceptance test framework

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#70]
Create a framework for AM API acceptance tests. Initially, support parts of [AM API v1](http://groups.geni.net/geni/wiki/GAPI_AM_API) plus [Changeset A](http://groups.geni.net/geni/wiki/GAPI_AM_API_DRAFT#ChangeSetA).

 _Imported from trac ticket [#70](http://trac.gpolab.bbn.com/gcf/ticket/70),  created by tmitchel on 12-06-2011 at 16:21, last modified: 12-08-2011 at 17:57_

**Comment by seledwards** [comment]
This is done.  It is part of gcf-1.5.  See gcf-1.5/acceptance_tests/AM_API_v1.

Test covered include:
 * GetVersion
 * ListResources 
 * CreateSliver
 * ListResources (with a bad credential)

_Trac comment by sedwards (github user: seledwards) on 12-08-2011 at 17:57_
