### ISSUE TITLE
Ensure both avail ranges are identical at PG

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#721]
At PG AMs, if >2 hops on same link, then the availRanges must be identical.

In particular, if we exclude unavail tags on one hop, we must exclude them on all other hops at this AM on this path.

 _Imported from trac ticket [#721](http://trac.gpolab.bbn.com/gcf/ticket/721),  created by ahelsing on 10-06-2014 at 11:13, last modified: 10-08-2014 at 10:21_

**Comment by luisanevers** [comment]
_lnevers (luisanevers) attached [ig-utahddc-ig-max-log.txt](http://trac.gpolab.bbn.com/gcf/attachment/ticket/721/ig-utahddc-ig-max-log.txt) on 10-08-2014 at 10:22_

**Comment by luisanevers** [comment]
_lnevers (luisanevers) attached [stitcher.log.1](http://trac.gpolab.bbn.com/gcf/attachment/ticket/721/stitcher.log.1) on 10-08-2014 at 10:22_

**Comment by ahelsing** [comment]
Jon says the avail ranges for this AM _and_ the ranges for the facing AMs must all agree. So Utah IG, Utah PG, and ION would all have to agree.

_Trac comment by ahelsing on 10-06-2014 at 11:37_

**Comment by ahelsing** [comment]
This is a per path thing. Each path must be consistent.

_Trac comment by ahelsing on 10-06-2014 at 12:18_

**Comment by ahelsing** [comment]
To clarify the issue:

PG was re-picking a VLAN tag that I thought we had marked unavailable / excluded from the range we requested. This was seen specifically when ION gave VLAN_PCE error. The symptom is that stitcher exits, complaining that the AM picked an unavail tag.

The fix adds logic to the code that handles the VLAN_PCE errors to try to ensure we exclude the failed tag from the range requests at the failed hop, at the hops at the PG AM (both if 2), and at the hop on the far side of the PG AM, if any.

Open questions:
 - Do I need to ensure no hops list the failed tag as suggested?
  - I'm guessing no
 - Do I need to make all these 2 or 4 hops have range_request that is the intersection - so identical?
  - I'm guessing no
 - Elsewhere we have logic that says that a 2nd hop using same URNs must _also_ exclude the failed tag. The VLAN PCE block doesn't do this. Must it?
  - Currently, I don't do this. But I suspect it is more correct to do so.
 - Is there a non VLAN PCE case where the code needs similar logic?
  - I suspect there could be: some other failure at an AM that depends on PG that is a VLAN unavail error. Currently the code doesn't do anything here, but it probably should



_Trac comment by ahelsing on 10-07-2014 at 16:18_

**Comment by ahelsing** [comment]
- In the multiple link case, we're not editing the suggested/avail range fields on the AM that failed (ION). Which would be the single tag PG picked last time. The result is PG might end up picking the same tag again. That's not a bad thing, but likely not intended. So probably we need to reset non failed hops same URN to scs_range_request less unavail (after adding failedHop's tag to unavail)


_Trac comment by ahelsing on 10-07-2014 at 16:52_

**Comment by ahelsing** [comment]
Now resetting hops with same URN on other paths, and also resetting suggested tag on the hops on the path that failed.

I am not intersecting the ranges - and it doesn't appear to be necessary.

And I have not tried to do anything similar in a non PCE case - mostly because I think it may not be necessary. The non PCE case would be where we try to redo only at the current AM I think. But if the AM was asked for 'any', then a failure is worse.

To test, try a circuit from Utah DDC or IG across PG Utah and ION with a couple links, and see if you can get a VLAN PCE failure at ION. Or at least confirm that in the non PCE case nothing goes wrong.


_Trac comment by ahelsing on 10-07-2014 at 22:37_

**Comment by luisanevers** [comment]
Replying to [ahelsing](comment:5):
> 
> To test, try a circuit from Utah DDC or IG across PG Utah and ION with a couple links, and see if you can get a VLAN PCE failure at ION. Or at least confirm that in the non PCE case nothing goes wrong.

I have been able to get a 'VLAN PCE' create failure at MAX, not ION.  Are you interested in this?

_Trac comment by lnevers (github user: luisanevers) on 10-08-2014 at 10:04_

**Comment by ahelsing** [comment]
It's better than nothing. But MAX picks the VLAN tag, not its neighbors (ION and MAX-IG), so it isn't really the same case.

I'm interested in that I want to be sure stitcher does the right thing afterwards, but it doesn't exercise this issue.

_Trac comment by ahelsing on 10-08-2014 at 10:18_

**Comment by luisanevers** [comment]
After the initial attempt, the next attempt succeeded, attaching log and the stitcher command output.


_Trac comment by lnevers (github user: luisanevers) on 10-08-2014 at 10:21_
