### ISSUE TITLE
Exception merging manifests

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#723]
Sarah had a run where manifests were being merged, and then she saw:
```
Traceback (most recent call last): File "/usr/share/geni-ch/portal/gcf/src/stitcher_php.py", line 73, in sys.exit(main()) File "/usr/share/geni-ch/portal/gcf/src/stitcher_php.py", line 60, in main raise e AttributeError: Element instance has no attribute 'name'
```

The last debug log message is:
```
10/06 11:04:04 DEBUG    ManifestRSpecCombiner.py:139 <Aggregate illinois-ig> manifest had new top level element: '<flack:slice_info view="graph"/>'...
```

This suggest it was doing 'combineOthers' in the manifest combiner.

 _Imported from trac ticket [#723](http://trac.gpolab.bbn.com/gcf/ticket/723),  created by ahelsing on 10-06-2014 at 12:13, last modified: 10-08-2014 at 11:05_

**Comment by ahelsing** [comment]
When we got an exception xmlifying 'other' elements in merging manifests, we tried to print the node 'name', but it should be 'nodeName'.


_Trac comment by ahelsing on 10-06-2014 at 12:37_

**Comment by luisanevers** [comment]
Tried several stitching experiments that used RSpec generated in flack, no issue found.
Are there any special flack defenitions that should be tested?

_Trac comment by lnevers (github user: luisanevers) on 10-08-2014 at 10:23_

**Comment by ahelsing** [comment]
No particular definitions that I know of.

_Trac comment by ahelsing on 10-08-2014 at 11:05_
