### ISSUE TITLE
Support AM API testing by allowing Omni to NOT reject sliver renewal times which aren't allowed.

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#78]
Omni reject bad sliver renewal times (in the past, after slice expiration) before it is seen at the AM making it hard to use Omni to test how the AM deals with these invalid times.

 _Imported from trac ticket [#78](http://trac.gpolab.bbn.com/gcf/ticket/78),  created by sedwards on 12-09-2011 at 13:24, last modified: 08-29-2012 at 09:11_
   CCing: gpo-sw-dev@...

**Comment by ahelsing** [comment]
Added new `--devmode` option, which causes omni to warn about bad inputs, but then pass them along anyhow

_Trac comment by ahelsing on 08-29-2012 at 09:11_
