### ISSUE TITLE
fixedEndpoint should only update stitched links

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-tools#790]
Niky wants to have a fixed endpoint for a link from an AM, but also wants a link within the same AM.

Stitcher is adding the fake endpoint on any link without 2 AMs, so links within an AM or with a shared VLAN are getting the fake endpoint, which is wrong.

 _Imported from trac ticket [#790](http://trac.gpolab.bbn.com/gcf/ticket/790),  created by nriga on 03-16-2015 at 11:59, last modified: 03-16-2015 at 16:54_

**Comment by ahelsing** [comment]
_ahelsing attached [niky-ptch](http://trac.gpolab.bbn.com/gcf/attachment/ticket/790/niky-ptch) on 03-16-2015 at 12:02_

**Comment by ahelsing** [comment]
When choosing links to add the fake interface, only add them to stitching links (listed in the stitching extension is a good measure).

As a side note, note that experimenters may explicitly put properties on the link to the fake interface to set the BW. Such properties may only list the source as the real AM, and the right thing seems to happen, although stitcher will warn you.


_Trac comment by ahelsing on 03-16-2015 at 12:01_

**Comment by ahelsing** [comment]
I ended up using the existing code in objects.py to traverse the already parsed RSpec, rather than re-parse it. But still just looking for links with no stitching path.

_Trac comment by ahelsing on 03-16-2015 at 16:54_
