### ISSUE TITLE
omni-configure doesn't find pkcs#8 private keys

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#799]
SSL private keys come in a couple formats.
Default for openssl has been PKCS#1 ("BEGIN RSA PRIVATE KEY"). Starting with openssl v1.0.0, the default is PKCS#8 ("BEGIN PRIVATE KEY").

The portal updated to v1.0.0 recently.

So people who generate their outside certs for the first time since then will get keys in this new format. People who generated their keys earlier will keep using their old keys.

omni-configure looks for the explicit PKCS#1 string. So it doesn't find the private key without this fix.

Symptom:
```
Private SSL key not in '/tmp/sslkey'.
    Either place your key in the above file or use
     the '-k' option to specify a custom location for the key.
```

 _Imported from trac ticket [#799](http://trac.gpolab.bbn.com/gcf/ticket/799),  created by ahelsing on 04-10-2015 at 15:17, last modified: 05-01-2015 at 09:35_

**Comment by seledwards** [comment]
See a temporary fix:
http://trac.gpolab.bbn.com/gcf/raw-attachment/wiki/Omni/omni-configure.py

_Trac comment by sedwards (github user: seledwards) on 04-16-2015 at 10:40_

**Comment by ahelsing** [comment]
That fix is actually committed. 

_Trac comment by ahelsing on 04-20-2015 at 15:31_

**Comment by ahelsing** [comment]
To test:
download your omni bundle.
Look inside.
If your private key (may be in the single .pem file or in a separate .key file) is prefaced by "BEGIN PRIVATE KEY", then:

With the old omni-configure, you would see the symptom listed above:
`Private SSL key not in '/tmp/sslkey'.`

The the new omni-configure, all works well.

If your private key in your omni-bundle instead is prefaced by "BEGIN RSA PRIVATE KEY", then with both the old and the new omni-configure, you should see the same behavior.

If your Portal SSL keys were generated before April 1 2015 (renewing your keys later doesn't count), then you should have 'BEGIN RSA PRIVATE KEY', and you will not see this error. However, if your keys were generated after April 1, you will see this issue.

For testing purposes, ideally both cases would be tested.


_Trac comment by ahelsing on 04-27-2015 at 13:18_
