### ISSUE TITLE
Cache aggregate API version

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#81]
Omni should cache the API version from GetVersion so that it knows which API version to speak to a given aggregate. This will require a file to record the cached information and the ability to refresh the data after a tunable timeout. Once in place, the calls to an individual aggregate should automatically switch between API versions based on the information in the cache.

 _Imported from trac ticket [#81](http://trac.gpolab.bbn.com/gcf/ticket/81),  created by tmitchel on 12-13-2011 at 15:04, last modified: 08-29-2012 at 08:42_

**Comment by ahelsing** [comment]
Added a new GetVersion Cache: the results of GetVersion are
   cached locally as serialed JSON. ListResources an other calls that
   require information from GetVersion may use this cache instead.
   GetVersion does not use the cache by default. Cache entries
   have a max age, after which we always re-query the AM.

_Trac comment by ahelsing on 08-29-2012 at 08:42_
