### ISSUE TITLE
Add v2 error handling in do_ssl

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#82]
do_ssl handles a variety of known errors in special ways. For instance, if an aggregate is busy, do_ssl will retry. GENI AM API v2 reports errors differently from v1, so do_ssl error handling can be updated to handle the new error returns and maybe even handle more known error conditions.

 _Imported from trac ticket [#82](http://trac.gpolab.bbn.com/gcf/ticket/82),  created by tmitchel on 12-13-2011 at 15:14, last modified: 06-20-2014 at 16:16_

**Comment by ahelsing** [comment]
I think do_ssl does as much of this as is needed.

_Trac comment by ahelsing on 06-20-2014 at 16:16_
