### ISSUE TITLE
Add omni degraded mode when no agg_nick_cache is available

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#822]
If there is no agg_nick_cache in `$HOME/.gcf` and no agg_nick_cache found in the parent dir (as will happen if running from the source tree), omni halts with an error. Instead it could go into degraded mode. In degraded mode, aggregate nicknames would not be honored and operations that would normally update the sliver info service at the clearinghouse would not be able to do so.

This should be a rare occurrence which would indicate that the user is running from a package install and has never been able to contact the central distribution point for agg_nick_cache.

**Comment by ahelsing** [comment]
now log an error and continue
