### ISSUE TITLE
omni-configure has problem with concurrent executions by different users on the same system

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-tools#843]
omni-configure uses /tmp as its scratchpad but does not ensure that different executions will get different names. As a result if two users on the same system execute omni-configure at the same time they will conflict.

**Comment by tcmitchell** [comment]
Is there any reason to not use `tempdir.mkdtemp()` for this? As the code stands it's still quite possible, although unlikely, that two users can conflict. `tempdir.mkdtemp()` is part of the standard library and is designed to do exactly this job.

```
import tempfile
d = tempfile.mkdtemp('-omconf')
```

On a Linux host that results in "/tmp/tmpOgyPK7-omconf".

**Comment by nbastin** [comment]
I'm pretty sure there's no reason to write tempfiles at all.  When I was going through omni-configure last all it did was unzip the contents into files and then move them.  Zipfile can present them to you as file-like objects that you can just read() and write() them into their real destinations (this is what geni-lib does in its bundle script).

**Comment by innnkkki** [comment]
tmitchel: Did not know about mkdteamp, I can definetely do that even easier. 

nbastin: I have to go back to the code and see but there was a reason why this was neessary and we couldn't just use the zip functionality, or maybe when the script was written back in the day there was some reason of something not working the way expected.

**Comment by ahelsing** [comment]
See pull request #877
