### ISSUE TITLE
Omni passes 't' or 'f' instead of Boolean to common federation API

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-tools#856]
Bug report from geni-users:

OMNI passes 'f' or 't' as values for 'SLICE_EXPIRED' field (e.g., in slice lookup method call). However according to [Common Federation API v2](http://groups.geni.net/geni/wiki/CommonFederationAPIv2), the type of 'SLICE_EXPIRED' field must be BOOLEAN.

**Comment by ahelsing** [comment]
A quick test suggests that Omni only uses 'f', but that at the GENI CH using `False` works as it should.

**Comment by ahelsing** [comment]
Note the issue exists with `PROJECT_EXPIRED` as well.
