### ISSUE TITLE
Fatal exception thrown in expire_slivers() in am3

### ISSUE THREAD

**Issue by EduardoMiravalls** [GENI-NSF/geni-tools#863]
This bug is present both in master and develop branches.

## Description
In am3, when expiring any sliver, an exception is raised in expire_slivers() and crashes the am.

Note that the code that deletes the expired slivers in expire_slivers() is fairly similar to last 12-15 lines in Delete(), but the following 2 lines are missing in expire_slivers():

    self._agg.deallocate(the_slice.urn, slivers)
    self._agg.deallocate(user_urn, slivers)

### Last log entries during crash:

    DEBUG:gcf.am3:Expring sliver urn:publicid:IDN+EDITED+sliver+8f129534-c845-44f5-8fa7-6b75c901d1d5 (expiration = datetime.datetime(2015, 9, 17, 13, 56, 5, 77882)) at datetime.datetime(2015, 9, 17, 13, 56, 9, 249084)
    INFO:gcf.am3:Expiring 1 slivers
    ERROR:gcf.am3:Generic Error in ListResources_V3
    Traceback (most recent call last):
      File "/opt/gcf-2.9/src/gcf/geni/am/am3.py", line 1236, in ListResources
        self._delegate.ListResources(credentials, amc._options)
      File "/opt/gcf-2.9/src/gcf/geni/am/am3.py", line 337, in ListResources
        self.expire_slivers()
      File "/opt/gcf-2.9/src/gcf/geni/am/am3.py", line 1095, in expire_slivers
        slyce.delete_sliver(sliver)
      File "/opt/gcf-2.9/src/gcf/geni/am/am3.py", line 257, in delete_sliver
        sliver.delete()
      File "/opt/gcf-2.9/src/gcf/geni/am/am3.py", line 208, in delete
        self._resource.deprovision()
      File "/opt/gcf-2.9/src/gcf/geni/am/fakevm.py", line 37, in deprovision
        self._agg.deallocate(container=None, resources=[self])
      File "/opt/gcf-2.9/src/gcf/geni/am/aggregate.py", line 70, in deallocate
        if r in c:
      File "/opt/gcf-2.9/src/gcf/geni/am/resource.py", line 81, in __eq__
        return self.id == other.id
    AttributeError: 'Sliver' object has no attribute 'id'
    WARNING:gcf.am3:'Sliver' object has no attribute 'id'

## Steps to reproduce:
 1. Allocate a sliver
 2. Provision it
 3. Let it expire
 4. Call any api method that executes expire_slivers()

To easily reproduce apply the following patch:

    diff --git a/src/gcf/geni/am/am3.py b/src/gcf/geni/am/am3.py
    index 23f0ef6..8f29441 100644
    --- a/src/gcf/geni/am/am3.py
    +++ b/src/gcf/geni/am/am3.py
    @@ -617,7 +617,7 @@ class ReferenceAggregateManager(object):
                                           and options['geni_end_time']))
             for sliver in slivers:
                 # Extend the lease and set to PROVISIONED
    -            expiration = min(sliver.endTime(), max_expiration)
    +            expiration = now
                 sliver.setEndTime(expiration)
                 sliver.setExpiration(expiration)
                 sliver.setAllocationState(STATE_GENI_PROVISIONED)

Note that the patch will make your sliver to be expired the same moment Allocate finishes so you can immediately call, for example, ListResources, and cause the Exception.

**Comment by ahelsing** [comment]
The problem appears to be that Aggregate.py expects the collections it keeps to be collections of Resource objects, not Sliver objects. am2.py does this correctly. am3.py does not (or not consistently).

A Resource indeed has a .id field.

Delete() has no error because it falls into a different clause in the if/else.

**Comment by ahelsing** [comment]
Fixed. Thanks for identifying the problem.

**Comment by EduardoMiravalls** [comment]
You're welcome. And thank *you* for fixing it so swiftly.
