### ISSUE TITLE
Fix for EGRE/GRE links in geni-tools/src/gcf/omnilib/stitch/ManifestRSpecCombiner.py

### ISSUE THREAD

**Issue by hussamnasir** [GENI-NSF/geni-tools#879]
listresources  operation using stitcher to get a combined manifest return back a manifest with incomplete link information. It was always missing one interface_ref information. The patch below solves.
[egre.patch.zip](https://github.com/GENI-NSF/geni-tools/files/57367/egre.patch.zip)

**Comment by ahelsing** [comment]
Hussam's full fix is here:
https://github.com/hussamnasir/geni-tools/commit/4b5226f02bf062866cc3ce9aa5c119fcfb5c6b3c
and
https://github.com/hussamnasir/geni-tools/commit/48e35a1f31db52c249d1a470b0138b52ea412ebc

**Comment by hussamnasir** [comment]
Actually hussamnasir@4b5226f would be the correct patch.

**Comment by ahelsing** [comment]
fixed via #880
