### ISSUE TITLE
ucdavis-eg site no longer exists

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-tools#913]
The site ucdavis-eg no longer exists.  The following clean up is needed:

1. Remove from agg_nick_cache file
2. Remove from up/down status  page in portal:  https://portal.geni.net/amstatus.php
3. Remove from the list of EG sites when Adding Resources to a slice in the portal.

**Comment by tcmitchell** [comment]
Thanks for letting us know.

* For removing from agg_nick_cache, I'll process the pull request whenever you post it. Note that the pull request will need to be against the [master branch](https://github.com/GENI-NSF/geni-tools/tree/master), not develop. @asydney has become an expert and can provide assistance.
* For removing from portal displays (status, jacks, etc.) the aggregate(s) will have to be removed from the service registry. That requires a [new geni-ch issue](https://github.com/GENI-NSF/geni-ch/issues/new).

**Comment by luisanevers** [comment]
https://github.com/GENI-NSF/geni-ch/issues/564 tracks the removal of item 2 and 3 in the bug description.
