### ISSUE TITLE
SFA 2.0.9 no longer supports get_aggregates() call.  Remove dependance on same.

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#94]
Tony reports that SFA 2.0.9 does not support the get_aggregates() call which is used as a last report by omni to determine which aggregates to contact.  

get_aggregates() is also used in the `listaggregates` call.

The error looks like: 

```
2012-01-18 12:11:45,141 - ERROR - XmlrpcApi.handle has caught Exception BEG TRACEBACK
Traceback (most recent call last):
 File "/usr/lib/python2.5/site-packages/sfa/server/xmlrpcapi.py", line 153, in handle
   result = self.call(source, method, *args)
 File "/usr/lib/python2.5/site-packages/sfa/server/xmlrpcapi.py", line 122, in call
   function = self.callable(method)
 File "/usr/lib/python2.5/site-packages/sfa/server/xmlrpcapi.py", line 105, in callable
   raise SfaInvalidAPIMethod, method
SfaInvalidAPIMethod: <Fault 13: u'Invalid method get_aggregates'>
```

I emailed Tony asking for what the replacement is.

 _Imported from trac ticket [#94](http://trac.gpolab.bbn.com/gcf/ticket/94),  created by sedwards on 01-18-2012 at 13:13, last modified: 02-09-2012 at 16:18_

**Comment by seledwards** [comment]
Tony reports that: 

```
The SFA Slice Manager's GetVersion() method returns a version struct that contains a field named 'peers'. The 'peers' field contains the list of federated aggregates. Unfortunately the version struct returned by the SFA Aggregate interface does not contain this 'peers' field. I can go ahead an add this field to the Aggregate's version struct if it makes things easier.
```

_Trac comment by sedwards (github user: seledwards) on 01-18-2012 at 14:36_

**Comment by tcmitchell** [comment]
In theory, this should amount to updating the `list_aggregates` method in `framework_sfa.py`. That method currently invokes `get_aggregates()` on the SFA registry. Instead, it probably needs to invoke `GetVersion()` on the `slicemgr` and then extract the relevant info from the resulting data structure.

_Trac comment by tmitchel (github user: tcmitchell) on 01-18-2012 at 15:34_

**Comment by seledwards** [comment]
We fielded a question from an experimenter about this today (meaning that at least two people have noticed and had to ask questions about this).

_Trac comment by sedwards (github user: seledwards) on 02-01-2012 at 15:52_

**Comment by seledwards** [comment]
Implemented as suggested above.

Closing.

_Trac comment by sedwards (github user: seledwards) on 02-03-2012 at 22:07_
