### ISSUE TITLE
Remove omnispecs

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#97]
omnispecs are no longer required. All existing and future aggregates honor standard RSpecs. Remove omnispecs from omni.

 _Imported from trac ticket [#97](http://trac.gpolab.bbn.com/gcf/ticket/97),  created by tmitchel on 01-24-2012 at 16:17, last modified: 08-29-2012 at 09:12_

**Comment by ahelsing** [comment]
Gone

_Trac comment by ahelsing on 08-29-2012 at 09:12_
